### ISSUE TITLE
Feature Request - SMBRelay logging

### ISSUE THREAD

**Issue by Lexus89** [CoreSecurity/impacket#100]
Logging failed relaying attempts (for example when a user has no access to the system you are relaying to) can be used to try and crack the password based on the challenge/response (and user/domain). During pentests this could be really helpful to have multiple shots at each received connection request with chall/resp. Right now i sometimes switch between relaying and the Metasploit SMB capture module (and HTTP NTLM capture/relaying).

**Comment by asolino** [comment]
Hey @Lexus89.. give it a try to the referenced commit and let me know how it goes. If all OK please close this FR.

**Comment by Lexus89** [comment]
@asolino Hey thanks for the quick update! I tried to check out the changes but i am receiving the following error (already present before the output file changes). Do you perhaps recognize this?:

[*] SMBD: Received connection from x.x.x.x, attacking target x.x.x.x
[-] SessionSetup Error!
[-] processRequest (0x73,("'NoneType' object has no attribute '__getitem__'", 'When unpacking field \' | "NTLMSSP\x00 | None[:8]\''))
[*] Handle: ("'NoneType' object has no attribute '__getitem__'", 'When unpacking field \' | "NTLMSSP\x00 | None[:8]\'')
[*] Closing down connection (x.x.x.x,50366)
[*] Remaining connections ['SMBRelay']
[*] Incoming connection (x.x.x.x,65322)
[*] SMBD: Received connection from x.x.x.x, attacking target x.x.x.x
[-] processRequest (0x73,exceptions must be old-style classes or derived from BaseException, not str)
[*] Handle: exceptions must be old-style classes or derived from BaseException, not str

**Comment by asolino** [comment]
@Lexus89 That error means there was a problem sending an Negotiate request to the target system. I just changed that logging to reflect what the error is like. Please git pull, retest and send me back the output.

Btw, what is the target OS you're trying to relay credentials to?

**Comment by Lexus89** [comment]
My bad, i made a typo in the IP and was relaying to a *nix system. Now the following info is output, which is actually nice to have and good for debugging purposes:

STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)

Still, when i relay to a (Win2k8 RC1 SP1) server i still get the following error:

[*] SMBD: Received connection from x.x.x.x, attacking target x.x.x.x
[-] processRequest (0x73,exceptions must be old-style classes or derived from BaseException, not str)
[*] Handle: exceptions must be old-style classes or derived from BaseException, not str

I also tested the auth success logging and it is working great, thanks!

**Comment by asolino** [comment]
Good to know the logging works well.

With regards to the old-style exception, I just made a minor change. Please pull, retest and let me know if that changed.
If not, another thing you can do is to uncomment https://github.com/CoreSecurity/impacket/blob/master/impacket/smbserver.py#L4010 and https://github.com/CoreSecurity/impacket/blob/master/impacket/smbserver.py#L4011 so you we get the location where the raise happened.

thanks.

**Comment by Lexus89** [comment]
I just retested and the errors seem to be gone now, since the logging also works fine i'll close this FR.

Thanks again and great job!

**Comment by asolino** [comment]
thanks for your bug report. cheers!
