### ISSUE TITLE
Wmiexec hangs if a previous execution is blocked, solution provided

### ISSUE THREAD

**Issue by jammer3d** [CoreSecurity/impacket#108]
The named pipe (variable named OUTPUT_FILENAME) is static which causes the file to be locked whenever an execution is in process.  If the session is terminated prematurely from the server side, wmiexec will hang on subsequent executions.  Changing the output_filename to be something dynamic instead of __ would resolve this issue. 

Changing the filename to be dynamic also allows for multiple concurrent sessions. 

To reproduce use wmiexec to execute cmd.exe and then run wmiexec to execute any other command (i.e. hostname)

A simple solution (I am not a python programmer):

--- /tmp/wmiexec.py     2015-11-10 15:02:30.257029595 -0500
+++ /bin/wmiexec.py     2015-11-10 14:58:57.305595672 -0500
@@ -35,7 +35,7 @@
 from impacket.dcerpc.v5.dcom import wmi
 from impacket.dcerpc.v5.dtypes import NULL

-OUTPUT_FILENAME = '__'
+OUTPUT_FILENAME = '__' + str(time.time())

 class WMIEXEC:
     def __init__(self, command = '', username = '', password = '', domain = '', hashes = None, aesKey = None, share = None, noOutput=False, doKerberos=False):

**Comment by mubix** [comment]
I've run into this issue as well, cool fix. I'll try it out
