### ISSUE TITLE
AttributeError: 'module' object has no attribute 'init'

### ISSUE THREAD

**Issue by agentc4** [CoreSecurity/impacket#109]
Hello,

when I run the following command:

python smbrelayx.py -h 10.10.10.6 -e /root/smb_rev.exe

I get the following output:

Traceback (most recent call last):
  File "smbrelayx.py", line 823, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'

This is version 0.9.13

**Comment by agentc4** [comment]
I have tried the same thing with version 0.9.11 and it seems to be working ok though, so not sure why about 0.9.13

**Comment by asolino** [comment]
Hey sorry for the delay.

Looks like you're using a newer `smbrelax.py` version for your 0.9.13 installation. 
If you have 0.9.13 installed use [this version](https://github.com/CoreSecurity/impacket/blob/impacket_0_9_13/examples/smbrelayx.py).

If you git clone master, then you can use the [latest version](https://github.com/CoreSecurity/impacket/blob/master/examples/smbrelayx.py).

Let me know if this fixes your issue and close this one.

**Comment by codelearnern** [comment]
Please do `pip install pygame`.  If that doesn't work do `python -m pip install pygame`.  If that doesn't work do `py -m pip install pygame`.
