### ISSUE TITLE
Ability to load kerberos ticket from Windows

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#113]
Hello there,

I just opened an issue (or rather a feature request) for CrackMapExec related to the **ability to load kerberos tickets, grabbed/generated with mimikatz from Windows hosts**, instead of your current implementation with the `$KRB5CCNAME` env var.

It might interest you, let me know if you could do something about it:
https://github.com/byt3bl33d3r/CrackMapExec/issues/45

Cheers.

**Comment by asolino** [comment]
Yup.. this should be nice to have :). PR welcomed ;)

You can use [kirbikator](https://github.com/gentilkiwi/kekeo/tree/master/kirbikator) in the meantime. Check @carnal0wnage [blog post](http://carnal0wnage.attackresearch.com/2015/09/ways-to-load-kerberos-tickets.html) too.

**Comment by maaaaz** [comment]
Check-out the PR https://github.com/CoreSecurity/impacket/pull/122 !

Cheers.
