### ISSUE TITLE
WMI is not thread safe?

### ISSUE THREAD

**Issue by mfrlin** [CoreSecurity/impacket#114]
I have two methods (simplified here):

    def get_client():
         dcom = DCOMConnection(address, username, password, domain)
        iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login, wmi.IID_IWbemLevel1Login)
        iWbemLevel1Login = wmi.IWbemLevel1Login(iInterface)
        _iWbemServices = iWbemLevel1Login.NTLMLogin(namespace, NULL, NULL)
        iWbemLevel1Login.RemRelease()
        return _iWbemServices

and

    def exec_query(self, query):
        iEnum = _iWbemServices.ExecQuery(query)
        while True:
            try:
                pEnum = iEnum.Next(0xffffffff, 1)[0]
                ....

when querying same ip with same credentials in two different threads simultaneous I get very weird errors.

Traceback (most recent call last):
  File "wmic.py", line 23, in __init__
    self._iWbemServices = iWbemLevel1Login.NTLMLogin(namespace, NULL, NULL)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 3059, in NTLMLogin
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1260, in request
    resp = dce.request(req, uuid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 820, in request
    answer = self.recv()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1250, in recv
    sec_trailer = SEC_TRAILER(data = auth_data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 82, in __init__
    self.fromString(data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 147, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 302, in unpack
    return self.unpack(two[0],data)
  File "/usr/local/lib/python2.7/dist-packages/impacket/structure.py", line 356, in unpack
    return unpack(format, data)[0]
error: ('unpack requires a string argument of length 1', "When unpacking field 'auth_type | B=10 | ''[:1]'")

and 

  File "wmic.py", line 23, in __init__
    self._iWbemServices = iWbemLevel1Login.NTLMLogin(namespace, NULL, NULL)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 3059, in NTLMLogin
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1260, in request
    resp = dce.request(req, uuid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 842, in request
    raise exception
DCERPCSessionError: WMI SessionError: unknown error code: 0x5e6b
] (<class 'impacket.dcerpc.v5.dcom.wmi.DCERPCSessionError'>, DCERPCSessionError(), <traceback object at 0x407db90>)
Traceback (most recent call last):
  File "/home/sc/smartsno/backend/protocol/wmic.py", line 23, in __init__
    self._iWbemServices = iWbemLevel1Login.NTLMLogin(namespace, NULL, NULL)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 3059, in NTLMLogin
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1260, in request
    resp = dce.request(req, uuid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 842, in request
    raise exception
DCERPCSessionError: WMI SessionError: unknown error code: 0x5e6b

**Comment by asolino** [comment]
That is a good question I don't have an answer for. Never tried an scenario like that. However, those errors are weird indeed. Could you provide a sample script I could run myself so I can reproduce and debug this issue?

thanks

**Comment by mfrlin** [comment]
Here you go:


```python
import threading

from impacket.dcerpc.v5.dtypes import NULL
from impacket.dcerpc.v5.dcom import wmi
from impacket.dcerpc.v5.dcomrt import DCOMConnection


namespace = '//./root/cimv2'
domain = ''
username = 'FILL THIS IN'
password = 'FILL THIS IN'
address = 'FILL THIS IN'

class WMIException(Exception): pass

def get_client():
    dcom = DCOMConnection(address, username, password, domain)
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login, wmi.IID_IWbemLevel1Login)
    iWbemLevel1Login = wmi.IWbemLevel1Login(iInterface)
    _iWbemServices = iWbemLevel1Login.NTLMLogin(namespace, NULL, NULL)
    iWbemLevel1Login.RemRelease()
    return _iWbemServices

def exec_query(self, query):
        iEnum = self._iWbemServices.ExecQuery(query)
        while True:
            try:
                pEnum = iEnum.Next(0xffffffff, 1)[0]
                record = pEnum.getProperties()
                for key in record:
                    print key, record[key]['value'])
            except wmi.DCERPCSessionError as e:
                if 'WBEM_S_FALSE' in str(e):
                    break  # end of records
                elif 'WBEM_E_INVALID_NAMESPACE' in str(e):
                    raise WMIException('Query error: invalid namespace')
                elif 'WBEM_E_INVALID_CLASS' in str(e):
                    raise WMIException('Query error: invalid class')
                elif 'WBEM_E_INVALID_QUERY' in str(e):
                    raise WMIException('Query error: invalid property or syntax error')
            except Exception as e:
                if 'timed out' in str(e):
                    raise WMIException('Connection error: time out')
                else:
                    raise WMIException('Unknown error: {}'.format(e))
        iEnum.RemRelease()


def start_wmi():
    get_client().exec_query('SELECT Name, PercentProcessorTime FROM Win32_PerfFormattedData_Counters_ProcessorInformation')

for _ in range(2):
    t = threading.Thread(target=start_wmi)
    t.start()
```
If it is hard to copy and paste from my comment here is a pastebin:
http://pastebin.com/c6HzzFaC

**Comment by asolino** [comment]
Hey mate.. thanks for the code.. I managed to reproduce this issue. Clearly there's something wrong and clearly WMI is not thread safe. I will need to dig deeper to understand where the issue is. Help is welcome.

**Comment by asolino** [comment]
@mfrlin mate, can you give it a try at this [patch.txt](https://github.com/CoreSecurity/impacket/files/49776/patch.txt)?.. I'm not fully convinced this to be the final solution, but first I want to be sure it works on your side.

**Comment by mfrlin** [comment]
I can not apply patch to my version of impacket==0.9.13

Code at line 1068 can not be patched. I searched for line 1066: `if INTERFACE.CONNECTIONS.has_key(self.__target):` but there isn't line like that in the file.

**Comment by asolino** [comment]
Ohh.. no no.. the patch I sent you is for `0.9.14-dev`.

You will need to `git clone` and install the impacket development version.

**Comment by asolino** [comment]
Okey.. here you have the [patch](https://github.com/CoreSecurity/impacket/files/50768/patch-0.9.13.txt) for 0.9.13. I haven't tested it much (I'd recommend you switch to the dev version if possible). Let me know how it goes.

**Comment by mfrlin** [comment]
Looks good. I'd like to test this in the bigger application we are building but I don't know if I can patch our environment. What is you next step, will you include this in dev version so I can pip install from github?

Thanks for another patch but I managed to patch dev version :)

Sorry for sending you a broken test script, I copy pasted something together very quick and did not test it through.

**Comment by asolino** [comment]
I just committed the changes to the dev version. Give it a try and close this issue if it works for you.

No worries about the script.. It just needed a minimal change ;)

**Comment by mfrlin** [comment]
Everything seems to be running fine. If I hit any problems or performance issues I'll let you know.

**Comment by asolino** [comment]
Excellent. Thanks mate.
