### ISSUE TITLE
Anonymous connections

### ISSUE THREAD

**Issue by hegusung** [CoreSecurity/impacket#115]
Hi,

is it possible to perform anonymous connections like smbclient does ?

thanks !

**Comment by asolino** [comment]
Hey @hegusung 

All the example scripts support anonymous connection. Just don't set a username/password when calling them. E.g.:
`python smbclient.py 172.16.123.100`
will connect anonymously to `172.16.123.100`.

Programmatically, when creating an [SMBConnection](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbconnection.py#L27) instance, you can then call the [SMBConnection.login()](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbconnection.py#L196) method with `username = ''` and `password = ''`. That will do it.

Let me know if you need extra help.

**Comment by hegusung** [comment]
Hi,
During an audit I was able to list users with an anonymous connection with winexe but I got an LOGIN_FAILURE with impacket. 
Aparently impacket sends a NegTokenInit structure even with an anonymous login, whereas winexe don't.
