### ISSUE TITLE
smbclient.py: can not handle Junction(directory symbol link) in shared folder

### ISSUE THREAD

**Issue by QianJin2013** [CoreSecurity/impacket#119]
My Windows 2016 Domain Server shares a folder named SYSVOL, there is a junction _DOMAIN_FULL_NAME_(win2016.com) there:
````
C:\Windows\SYSVOL\sysvol> dir
...
2015/12/16  15:12    <JUNCTION>     win2016.com [C:\Windows\SYSVOL\domain]
````

I can use normal domain user to browse the folder \\\win2016_dc\sysvol\win2016.com in Windows File Explorer, and samba's utility smbclient also works,
but smbclient.py failed to view the junction:
````
$ smbclient.py win2016.com/q@192.168.99.2
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

Password:
Type help for list of commands
# shares 
ADMIN$
C$
IPC$
NETLOGON
SYSVOL
# use SYSVOL
# ls
drw-rw-rw-          0  Wed Dec 16 15:12:38 2015 .
drw-rw-rw-          0  Wed Dec 16 15:12:38 2015 ..
drw-rw-rw-          0  Wed Dec 16 15:12:38 2015 win2016.com
# cd win2016.com
[-] SMB SessionError: STATUS_ACCESS_DENIED({Access Denied} A process has requested access to an object but has not been granted those access rights.)
````

I will check it when i am free, i think it's is because too much permission requested to the junction.
JUNCTION often cause such problem for traditional program.

**Comment by asolino** [comment]
That is an interesting finding.. I'll try to reproduce it as well. We should also check whether that behaviour happens with SMB1 connections. 

Help is appreciated.

**Comment by asolino** [comment]
Plus.. if you can send me a pcap of the session when the error is triggered that'd be great too.

**Comment by asolino** [comment]
Fixed by @QianJin2013 with PR https://github.com/CoreSecurity/impacket/pull/120
