### ISSUE TITLE
Impacket examples scripts compiled for Windows

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#128]
Hey @asolino,

This issue isn't one. I just wanted to inform you that I [**compiled the `examples` scripts for Windows**](https://github.com/maaaaz/impacket-examples-windows), as I realized recently that there **wasn't an easy way to use them** on a internal assessment, for instance after compromising a box or simply when you're forced to use a third-party machine and you don't want to go for a burdensome installation of Python and the requirements :)
Well all in all, I wanted to make **these great scripts portable.**

I obviously credited you & your company and ain't taking any profit in any way from it.
**Tell me if something bothers you about it !**

(By the way, I also realized that you haven't a logo for that project ?! (willing to use it as .exe icon))

Cheers.

**Comment by asolino** [comment]
Hey @maaaaz, 

That is great news.. I already saw and tweeted your repository ;). Great to know you find the examples useful. I'm wondering why the mssql* examples cannot be compiled.. 

Another alternative to the binaries I can think of is to import impacket into [pupy](https://github.com/n1nj4sec/pupy) and then port the examples into pupy's modules. 

> I obviously credited you & your company and ain't taking any profit in any way from it.
> Tell me if something bothers you about it !

Strictly speaking you should follow what impacket's [license](https://github.com/CoreSecurity/impacket/blob/master/LICENSE) states.  I would put a link to the license (or the license itself) into the repository. 
As you can see the license is very permissive and let the users play and modify it at will as long as you maintain the original LICENSE information.

( no logo indeed ;).. never thought about it to be honest ;) )

cheers!

**Comment by maaaaz** [comment]
I'm glad that you like the idea of compiling these scripts.
And of course I'll add the impacket licence into the repo !

Cheers.

**Comment by asolino** [comment]
Thanks again @maaaaz  closing this one.

**Comment by maaaaz** [comment]
You're welcome.
