### ISSUE TITLE
Add "stop after success" with smbrelayx

### ISSUE THREAD

**Issue by ropnop** [CoreSecurity/impacket#132]
Was just playing around with smbrelayx and Responder and got relay working for WPAD requests (great tool btw!)

However, my spoofed victim started firing off requests for WPAD very quickly and smbrelayx uploaded my payload and ran the service every time a request came through. I had to kill smbrelayx and Responder after getting something like 15 Empire agents calling back to me from the same host!

When using smbrelayx with the "-h" flag, would it be possible to add a "stop after success" option? Or when not using the "-h" flag, maybe some logic to detect if the host has already been accessed and the payload executed? I can't think of many use cases where I would want to relay creds and upload a payload multiple times to a single host.

Thanks for the good work!

**Comment by asolino** [comment]
Fixed at https://github.com/CoreSecurity/impacket/commit/07f19817d6ca2a819265814b519d271c30657d5c. Use -one-shot parameter

**Comment by ropnop** [comment]
Hey buddy!

Finally got some time to play around with this. Thanks for the update!

The "-one-shot" parameter is great, but it stops after a host has already been attacked (regardless of whether it's been succesful or not)

To test it I left it running and spoofed an unprivileged user. The relay happened and the authentication succeeds, but the payload doesn't execute (no privs)
`[-] DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied`

I then immediately followed it up with a request from an Administrator, but the tool says:
`[*] HTTPD: Received connection from 10.9.122.5, skipping 10.9.122.10, already attacked`

Ideally, it wouldn't skip it until the command has successfully executed. The use-case would be during a pentest to let Responder and smbrelayx run continuously to capture hashes. If you get "lucky" and a captured hash is a local admin on the target, the payload executes and you can stop.

I'm trying to find a good way to track whether the command executes or whether you get an RPC access denied error, but I can't find a good way of doing it. I tried just adding a "_success" variable inside the the doAttack class (https://github.com/ropnop/impacket/commit/1d241c04b5a38723c68a4c2b1fd63e8c8a021f03), but I think the problem is the variable is not toggled to "True" in time for the check to add it to the attacked set. I suppose we could pause and wait for the thread to complete before moving on, but that might break cases where you get a subsequent request before the previous has been attempted.

Any thoughts? Should I open a new issue?

Ronnie

**Comment by asolino** [comment]
Hey @ropnop 

Indeed the script is currently stopping after a successful SMB Authentication, regardless of the user having admin privileges or not. The use case you mention is valid so I would go ahead and create an issue for it.

Don't know exactly how to solve it tho, but we'll figure it out ;). Ideally `doAttack()` should let us know everything went well.
