### ISSUE TITLE
Secretsdump error

### ISSUE THREAD

**Issue by troland123** [CoreSecurity/impacket#133]
secretsdump.py -ntds ntds.dit -history -system system LOCAL
Impacket v0.9.15-dev - Copyright 2002-2016 Core Security Technologies

[*] Target system bootKey: 0x666b2934c9bf6debd5245026eb194abf
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[-] ('unpack requires a string argument of length 2', "When unpacking field 'LocalPageKeyS
ize | <H=0 | ''[:2]'")
[*] Cleaning up...

I test version from 0.9.11 to 0.9.15
Other ntds.dit file dump correct, but this is biger 770MB

**Comment by asolino** [comment]
hey @troland123 

Run it with `-debug` to check if there's anything that might give us a hint.

Did you try other tools to check whether that NTDS.DIT has an specific problem?

**Comment by troland123** [comment]
secretsdump.py -ntds ntds.dit -history -system system -debug  LOCAL
Impacket v0.9.15-dev - Copyright 2002-2016 Core Security Technologies

[+] Retrieving class info for JD
[+] Unknown type 0xd
[+] Retrieving class info for Skew1
[+] Unknown type 0x2
[+] Retrieving class info for GBG
[+] Unknown type 0x6
[+] Retrieving class info for Data
[+] Unknown type 0x2
[*] Target system bootKey: 0x666b2934c9bf6debd5245026eb194abf
[+] Checking NoLMHash Policy
[+] LMHashes are NOT being stored
[+] Mounting DB...
[+] Trying to fetch page -1 (0x0)
[+] Database Version:0x620, Revision:0x11
[+] Page Size: 8192
[+] Total Pages in file: 94720
[+] Trying to fetch page 4 (0xa000)
[+] Trying to fetch page 19 (0x28000)
[+] Trying to fetch page 20 (0x2a000)
[+] Trying to fetch page 21 (0x2c000)
[+] Trying to fetch page 22 (0x2e000)
[+] Trying to fetch page 23 (0x30000)
[+] Trying to fetch page 44 (0x5a000)
[+] Trying to fetch page 64 (0x82000)
[+] Trying to fetch page 65 (0x84000)
[+] Trying to fetch page 66 (0x86000)
[+] Trying to fetch page 69 (0x8c000)
[+] Trying to fetch page 67 (0x88000)
[+] Trying to fetch page 71 (0x90000)
[+] Trying to fetch page 73 (0x94000)
[+] Trying to fetch page 68 (0x8a000)
[+] Trying to fetch page 70 (0x8e000)
[+] Trying to fetch page 72 (0x92000)
[+] Trying to fetch page 257 (0x204000)
[+] Trying to fetch page 1375 (0xac0000)
[+] Trying to fetch page 179 (0x168000)
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Searching for pekList, be patient
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTh590442, returning raw results
[+] Multivalue detected in column ATTb131079, returning raw results
[+] Trying to fetch page 35803 (0x117b8000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTh590442, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 1455 (0xb60000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc590020, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc590020, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 180 (0x16a000)
[+] Multivalue detected in column ATTc590021, returning raw results
[+] Multivalue detected in column ATTc590020, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 181 (0x16c000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 182 (0x16e000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 183 (0x170000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 184 (0x172000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 185 (0x174000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 186 (0x176000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 187 (0x178000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 188 (0x17a000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 189 (0x17c000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 190 (0x17e000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 191 (0x180000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 192 (0x182000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 193 (0x184000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 194 (0x186000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 195 (0x188000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 196 (0x18a000)
[-] ('unpack requires a string argument of length 2', "When unpacking field 'LocalPageKeyS
ize | <H=0 | ''[:2]'")
[*] Cleaning up...

I update NTDS.DIT, eq result. Befor 2 mounth (this server, but smaller NTDS.DIT ~500MB) work ok
Do you mean specific tool for test ?

**Comment by troland123** [comment]
sorry
correct end is:
[+] Trying to fetch page 195 (0x188000)
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Multivalue detected in column ATTc0, returning raw results
[+] Trying to fetch page 196 (0x18a000)
[-] ('unpack requires a string argument of length 2', "When unpacking field 'LocalPageKeyS
ize | <H=0 | ''[:2]'")
[*] Cleaning up...

**Comment by troland123** [comment]
[ - ] ('unpack requires a string argument of length 2', "When unpacking field 'LocalPageKeyS
ize | <H=0 | ''[:2]'") translate to -

**Comment by troland123** [comment]
('unpack requires a string argument of length 2', "When unpacking field 'LocalPageKeyS
ize | <H=0 | ''[:2]'") translate to -

**Comment by asolino** [comment]
hmm.. no idea.. sounds like a corrupt NTDS.DIT. 

I was thinking about `http://www.ntdsxtract.com/` or similar tools.

Just in case.. you know you can skip all this NTDS.DIT stuff and dump the hashes directly from the remote system using DRSUAPI right?

**Comment by troland123** [comment]
hm...
root@pt:~/libesedb-20140406/esedbtools# ./esedbexport /adc/ntds.dit
esedbexport 20140406

Opening file.
Exporting table 1 (MSysObjects) out of 12.
Exporting table 2 (MSysObjectsShadow) out of 12.
Exporting table 3 (MSysUnicodeFixupVer2) out of 12.
Exporting table 4 (datatable) out of 12.
Unable to export file.
libesedb_page_tree_read_page_value: local key size exceeds page value size.
libesedb_page_tree_read_node_value: unable to read page: 1476 value: 1.
libfdata_tree_get_node_value: unable to read node at offset: 12083316.
libfdata_tree_node_read_leaf_node_values: unable to retrieve node value.
libfdata_tree_node_get_number_of_leaf_nodes: unable to retrieve node value.
libfdata_tree_node_read_leaf_node_values: unable to retrieve number of leaf nodes from sub node: 0.
libfdata_tree_node_get_number_of_leaf_nodes: unable to retrieve node value.
libfdata_tree_node_read_leaf_node_values: unable to retrieve number of leaf nodes from sub node: 51.
libfdata_tree_node_get_number_of_leaf_nodes: unable to retrieve node value.
libfdata_tree_node_read_leaf_node_values: unable to retrieve number of leaf nodes from sub node: 2.
libfdata_tree_node_get_number_of_leaf_nodes: unable to retrieve node value.
libfdata_tree_get_number_of_leaf_nodes: unable to retrieve number of leaf nodes from root node.
libesedb_table_get_number_of_records: unable to retrieve number of leaf nodes from table values tree.
export_handle_export_table: unable to retrieve number of records.
export_handle_export_file: unable to export table: 3.

**Comment by troland123** [comment]
c:\>PT\esentutl /g ntds.dit

Extensible Storage Engine Utilities for Microsoft(R) Windows(R)
Version 6.1
Copyright (C) Microsoft Corporation. All Rights Reserved.

Initiating INTEGRITY mode...
        Database: ntds.dit
  Temp. Database: TEMPINTEG1240.EDB

Checking database integrity.

                     Scanning Status (% complete)

          0    10   20   30   40   50   60   70   80   90  100
          |----|----|----|----|----|----|----|----|----|----|
          ...................................................


Integrity check completed.  Database is CORRUPTED!

ADC have BIG problem... Thank you
