### ISSUE TITLE
Using special characters in password

### ISSUE THREAD

**Issue by indigosax** [CoreSecurity/impacket#134]
when using special char like $ in password string it is converting.

Example:

./crackmapexec.py -d localhost -u theuser -p Pa$$w0rd --mimikatz 10.11.1.11

localhost\theuser:Pa51375w0rd SMB SessionError: STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)

**Comment by sho-luv** [comment]
Yeah I had to use combo file to get around that.

Leon Johnson

**Comment by asolino** [comment]
@indigosax hola mate.. hope you're well..

is this happening with impacket as well? (e.g. when running psexec.py / wmiexec.py / etc )

If not, this should be reported as a [CrackMapExec issue](https://github.com/byt3bl33d3r/CrackMapExec/issues).

**Comment by indigosax** [comment]
Yeah... Just exited em... Figured it's a cleanup that others may scratch
head on. Pa\$\$word worked.

**Comment by byt3bl33d3r** [comment]
@indigosax just fyi, if you wrap the password in single quotes it works ;)
