### ISSUE TITLE
mssqlclient.py fails silently if pyOpenSSL is not installed

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#135]
Hey man!
Just FYI, as the title says mssqclient.py and anything that imports tds.py fails silently if pyOpenSSL isn't installed.

The offending code in tds.py
```python
try:
    import OpenSSL
    from OpenSSL import SSL, crypto
except:
    LOG.critical("pyOpenSSL is not installed, can't continue")
    sys.exit(1)
```

**Comment by byt3bl33d3r** [comment]
Since tds.py is a library this should probably raise an exception

**Comment by asolino** [comment]
Hey @byt3bl33d3r !

Jeez that's nasty.. yeah.. changing that now.. don't know why did I do it that way (shy face )

**Comment by byt3bl33d3r** [comment]
@asolino closing! thanks!
