### ISSUE TITLE
Cannot access (CLI) shares from Windows 8.1 / 2012R2 / 10

### ISSUE THREAD

**Issue by sharon-sultan** [CoreSecurity/impacket#136]
from **command line** try to access shared folder, for instance:

`>dir \\192.168.2.9\tmp`

results with:

```
Volume in drive \\192.168.2.9\tmp has no label.
 Volume Serial Number is ABCD-EFAA

 Directory of \\192.168.2.9\tmp

File Not Found
```
While share does exist, and it is not empty.

Win 7/2008 cmd client works well.

I used SimpleSMBServer initiated using examples/smbserver.py as follows:
`./smbserver.py  -smb2support tmp /tmp/`

**Comment by asolino** [comment]
hey @sharon-sultan 

did you try it from windows explorer?

**Comment by sharon-sultan** [comment]
Hey @asolino 

windows explorer worked from windows 8.1 and 2012R2
did not work from windows 10

cmd.exe failed for all.

**Comment by asolino** [comment]
@sharon-sultan gotcha.

without `smb2support` all good right? Looks like this is SMB >= 2 related problem.

**Comment by sharon-sultan** [comment]
yep @asolino, without smb2support it is all good.

**Comment by liadga** [comment]
Hey @asolino 
I think I found the issue:
When windows 8.1 queries the directory via cmd, it sends flag SL_RETURN_SINGLE_ENTRY which cause the loop to break in the smb2QueryDirectory function,
but the previous FullDirectoryInfo['NextEntryOffset'] which already was added to the output still has value (instead of 0 like  expected in SMB protocol). 
As I saw this issue may also occur in other windows version in case the folder contains lot of sub folders / files which are more than the buffer supplied by the client.

I think this code will fix it:

`@staticmethod
    def smb2QueryDirectory(connId, smbServer, recvPacket):
        connData = smbServer.getConnectionData(connId)
        respSMBCommand = smb2.SMB2QueryDirectory_Response()
        queryDirectoryRequest   = smb2.SMB2QueryDirectory(recvPacket['Data'])

        respSMBCommand['Buffer'] = '\x00'

        # The server MUST locate the tree connection, as specified in section 3.3.5.2.11.
        if connData['ConnectedShares'].has_key(recvPacket['TreeID']) is False:
            return [smb2.SMB2Error()], None, STATUS_NETWORK_NAME_DELETED

        # Next, the server MUST locate the open for the directory to be queried
        # If no open is found, the server MUST fail the request with STATUS_FILE_CLOSED
        if str(queryDirectoryRequest['FileID']) == '\xff'*16:
            # Let's take the data from the lastRequest
            if  connData['LastRequest'].has_key('SMB2_CREATE'):
                fileID = connData['LastRequest']['SMB2_CREATE']['FileID']
            else:
                fileID = str(queryDirectoryRequest['FileID'])
        else:
            fileID = str(queryDirectoryRequest['FileID'])

        if connData['OpenedFiles'].has_key(fileID) is False:
            return [smb2.SMB2Error()], None, STATUS_FILE_CLOSED

        # If the open is not an open to a directory, the request MUST be failed
        # with STATUS_INVALID_PARAMETER.
        if os.path.isdir(connData['OpenedFiles'][fileID]['FileName']) is False:
            return [smb2.SMB2Error()], None, STATUS_INVALID_PARAMETER

        # If any other information class is specified in the FileInformationClass
        # field of the SMB2 QUERY_DIRECTORY Request, the server MUST fail the
        # operation with STATUS_INVALID_INFO_CLASS.
        if queryDirectoryRequest['FileInformationClass'] not in (smb2.FILE_DIRECTORY_INFORMATION,smb2.FILE_FULL_DIRECTORY_INFORMATION,smb2.FILEID_FULL_DIRECTORY_INFORMATION, smb2.FILE_BOTH_DIRECTORY_INFORMATION, smb2.FILEID_BOTH_DIRECTORY_INFORMATION, smb2.FILENAMES_INFORMATION):
            return [smb2.SMB2Error()], None, STATUS_INVALID_INFO_CLASS

        # If SMB2_REOPEN is set in the Flags field of the SMB2 QUERY_DIRECTORY
        # Request, the server SHOULD<326> set Open.EnumerationLocation to 0
        # and Open.EnumerationSearchPattern to an empty string.
        if queryDirectoryRequest['Flags'] & smb2.SMB2_REOPEN:
            connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] = 0
            connData['OpenedFiles'][fileID]['Open']['EnumerationSearchPattern'] = ''

        # If SMB2_RESTART_SCANS is set in the Flags field of the SMB2
        # QUERY_DIRECTORY Request, the server MUST set
        # Open.EnumerationLocation to 0.
        if queryDirectoryRequest['Flags'] & smb2.SMB2_RESTART_SCANS:
            connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] = 0

        # If Open.EnumerationLocation is 0 and Open.EnumerationSearchPattern
        # is an empty string, then Open.EnumerationSearchPattern MUST be set
        # to the search pattern specified in the SMB2 QUERY_DIRECTORY by
        # FileNameOffset and FileNameLength. If FileNameLength is 0, the server
        # SHOULD<327> set Open.EnumerationSearchPattern as "*" to search all entries.

        pattern = queryDirectoryRequest['Buffer'].decode('utf-16le')
        if  connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] == 0 and \
            connData['OpenedFiles'][fileID]['Open']['EnumerationSearchPattern'] == '':
            if pattern == '':
                pattern = '*'
            connData['OpenedFiles'][fileID]['Open']['EnumerationSearchPattern'] = pattern

        # If SMB2_INDEX_SPECIFIED is set and FileNameLength is not zero,
        # the server MUST set Open.EnumerationSearchPattern to the search pattern
        # specified in the request by FileNameOffset and FileNameLength.
        if queryDirectoryRequest['Flags'] & smb2.SMB2_INDEX_SPECIFIED and \
           queryDirectoryRequest['FileNameLength'] > 0:
            connData['OpenedFiles'][fileID]['Open']['EnumerationSearchPattern'] = pattern

        pathName = os.path.join(os.path.normpath(connData['OpenedFiles'][fileID]['FileName']),pattern)
        searchResult, searchCount, errorCode = findFirst2(os.path.dirname(pathName),
                  os.path.basename(pathName),
                  queryDirectoryRequest['FileInformationClass'],
                  smb.ATTR_DIRECTORY, isSMB2 = True )

        if errorCode != STATUS_SUCCESS:
            return [smb2.SMB2Error()], None, errorCode

        if searchCount > 2 and pattern == '*':
            # strip . and ..
            searchCount -= 2
            searchResult = searchResult[2:]

        if searchCount == 0 and connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] == 0:
            return [smb2.SMB2Error()], None, STATUS_NO_SUCH_FILE

        if  connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] < 0:
            return [smb2.SMB2Error()], None, STATUS_NO_MORE_FILES

        totalData = 0
        respData = ''
        badIndex = 0

        if queryDirectoryRequest['Flags'] & smb2.SL_RETURN_SINGLE_ENTRY:
           badIndex = 0
        else:
            for nItem in range(connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'], searchCount):
                data = searchResult[nItem].getData()
                lenData = len(data)
                padLen = (8-(lenData % 8)) %8
                if (totalData+lenData + padLen) >= queryDirectoryRequest['OutputBufferLength']:
                    break
                badIndex += 1

        totalData = 0
        index = 0
        for nItem in range(connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'], searchCount):
            connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] += 1
            if (index == badIndex):
                searchResult[nItem]['NextEntryOffset'] = 0

            data = searchResult[nItem].getData()
            lenData = len(data)
            padLen = (8-(lenData % 8)) %8

            if (totalData+lenData + padLen) >= queryDirectoryRequest['OutputBufferLength']:
                connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] -= 1
                break
            else:
                respData += data + '\x00'*padLen
                totalData += lenData + padLen

            if queryDirectoryRequest['Flags'] & smb2.SL_RETURN_SINGLE_ENTRY:
                break

            index +=1

        if connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] >= searchCount:
             connData['OpenedFiles'][fileID]['Open']['EnumerationLocation'] = -1

        respSMBCommand['OutputBufferOffset'] = 0x48
        respSMBCommand['OutputBufferLength'] = totalData
        respSMBCommand['Buffer'] = respData

        smbServer.setConnectionData(connId, connData)
        return [respSMBCommand], None, errorCode`

**Comment by asolino** [comment]
hey @liadga 

that is great!.. would mind creating a pull request so I can play with it?

**Comment by asolino** [comment]
Hey folks, please `git pull` and check if the last commit fixes the issue. Thanks @liadga for giving the tip about clearing `NextEntryOffset`. That saved a lot of time!

If it works on your side please close this issue.

**Comment by asolino** [comment]
Any news on this @liadga, could you recheck?

**Comment by asolino** [comment]
No answer from @liadga, closing
