### ISSUE TITLE
Use secretdump.py to dump ntds.dit located on linux desktop

### ISSUE THREAD

**Issue by lukewatson01** [CoreSecurity/impacket#138]
I underestand you can use secretdump.py to dump ntds.dits from remote machines, but how can you tell it to dump ntds.dit located on your linux desktop?

**Comment by asolino** [comment]
hey @lukewatson01 

You need both the `ntds.dit` and `system` registry hive. Let's assume your `DIT` is called `ndts.dit` and your hive is called `system.save`,  then run `secretsdump.py` this way:

`secretsdump.py -system system.save -ntds ntds.dit LOCAL` 

Let  me know if it works on your side and close this issue

**Comment by asolino** [comment]
any news on this @lukewatson01?

**Comment by asolino** [comment]
No answer, closing. @lukewatson01, open it if you have further questions.
