### ISSUE TITLE
Feature Request - NTLM relaying to LDAP

### ISSUE THREAD

**Issue by Lexus89** [CoreSecurity/impacket#139]
It would be great to have a feature to relay NTLM authentication to an LDAP server, especially since domain controllers do not have LDAP signing enabled by default (unlike SMB signing). This way you can not only get domain information (e.g. all users) but even change passwords or add new users (instant domain admin ftw). 

This feature was already implemented before (ZackAttack and Intercepter-NG) however they are not practical (Windows) or out-dated. http://sniff.su https://github.com/urbanesec/ZackAttack I also find it quite hard to find documentation on this..

Possibly you can also relay to Remote Desktop servers since it also supports NTLM authentication? Support for more protocols for relaying is awesome, Metasploit's HTTP NTLM relay also gives you the http response back when relaying, really helpful.

**Comment by asolino** [comment]
Hey @Lexus89 

Definitely great idea.. I'll leave it open until we start coding something around this. I have some ideas in mind already.

**Comment by asolino** [comment]
> Metasploit's HTTP NTLM relay also gives you the http response back when relaying, really helpful.

I didn't understand this one, please elaborate.

**Comment by Lexus89** [comment]
Metasploit contains HTTP -> HTTP NTLM relaying, perhaps this is something interesting for smbrelayx as well. Handy for getting access to webapps with NTLM authentication support such as Sharepoint. For example by grabbing the HTML source code that contains sensitive data. 

In theory it should be possible to relay to all NTLM supported protocols from FTP to Telnet HTTP RDP LDAP etc. 

Another handy tool btw but unfortunately not updated for a long time: https://github.com/purpleteam/snarf

**Comment by asolino** [comment]
Now it makes sense, thanks @Lexus89 !

**Comment by dirkjanm** [comment]
This one can be closed I think, functionality is now in ntlmrelayx via #163

**Comment by asolino** [comment]
Closing! Thanks @dirkjanm!
