### ISSUE TITLE
Feature Request - From relaying to rpc commands exec

### ISSUE THREAD

**Issue by Lexus89** [CoreSecurity/impacket#143]
During pentests you often get machine accounts (HOSTNAME$) and low privilege users however they seem useless and you keep on waiting. Trying to dump SAM hashes or starting binary as a service will fail without the needed privs. However, with these accounts (including the machine accounts) you are able to execute RPC commands such as can be done with rpcclient.

It would be nice to relay the authentication to a server and get a prompt like rpcclient where you can execute supported rpc commands. This can help you to enumerate the domain users and password policy to help you find your first point of entry. You can also add new users + place them in certain groups this way. Nice when relaying Domain Admins -> adding a new Domain Admin directly.

**Comment by asolino** [comment]
Yup.. agreed on its usefulness @Lexus89.

This will be part of https://github.com/CoreSecurity/impacket/issues/82 once I get to start it :)

**Comment by asolino** [comment]
Already part of the [relay-experimental](https://github.com/CoreSecurity/impacket/tree/relay-experimental) branch. Closing.
