### ISSUE TITLE
secretsdump fails against renamed domains

### ISSUE THREAD

**Issue by gentilkiwi** [CoreSecurity/impacket#150]
When using ``secretsdump.py`` against a domain which has been renamed, the script fails with ``ERROR_DS_DIFFERENT_REPL_EPOCHS``

```
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Using the DRSUAPI method to get NTDS.DIT secrets
[+] Session resume file will be sessionresume_nNVwDhfV
[+] DRSBind() answer
DRSBindResponse
ppextServer:
    cb:                              52
    rgb:
        [
             ...
             '{',
             '\x00',
             '\x00',
             '\x00',
             ...
        ]
phDrs:                           '\x00\x00\x00\x00\xfc\x82\xdcV`I<K\xbd\xac"}\x14\xf2\xe7\\'
ErrorCode:                       0


[+] DRSDomainControllerInfo() answer
DRSDomainControllerInfoResponse
pdwOutVersion:                   2
pmsgOut:
    tag:                             2
    V2:
        cItems:                          1
        rItems:
            [

                NetbiosName:                     u'WIN-G7GAOCSNTTE\x00'
                DnsHostName:                     u'WIN-G7GAOCSNTTE.lab2.local\x00'
                SiteName:                        u'Default-First-Site-Name\x00'
                SiteObjectName:                  u'CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=lab2,DC=local\x00'
                ComputerObjectName:              u'CN=WIN-G7GAOCSNTTE,OU=Domain Controllers,DC=lab2,DC=local\x00'
                ServerObjectName:                u'CN=WIN-G7GAOCSNTTE,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=lab2,DC=local\x00'
                NtdsDsaObjectName:               u'CN=NTDS Settings,CN=WIN-G7GAOCSNTTE,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=lab2,DC=local\x00'
                fIsPdc:                          1
                fDsEnabled:                      1
                fIsGc:                           1
                SiteObjectGuid:                  '\x06\xdd\xf9i{\xddtK\x81:\x93\xb4oB\x00\xcf'
                ComputerObjectGuid:              '\xfaDP\xd2\xe5\x90rI\xb7\ri\xcd>a\xb9\xeb'
                ServerObjectGuid:                '\xbb\x98u7\xd9\x03\x95L\x83\xe6s|\xfa\xa2.K'
                NtdsDsaObjectGuid:               '\x9f\xc4\x05\xb7#\xdb%F\xbdwO\xdd\x81\xde\x8bM' ,
            ]
ErrorCode:                       0

[-] DRSR SessionError: code: 0x2191 - ERROR_DS_DIFFERENT_REPL_EPOCHS - The directory service cannot perform the requested operation because the servers involved are of different replication epochs (which is usually related to a domain rename that is in progress).
[*] Something wen't wrong with the DRSUAPI approach. Try again with -use-vss parameter
```

Thanks to @rmbolger (https://github.com/MichaelGrafnetter/DSInternals/issues/15), then @MichaelGrafnetter (https://github.com/gentilkiwi/mimikatz/issues/35) and now me (what a share !), you now know that you must deal with [msDS-ReplicationEpoch](https://msdn.microsoft.com/en-us/library/cc221218.aspx).

According to the [documentation](https://msdn.microsoft.com/en-us/library/cc228293.aspx):
> If the client is a DC, **it reads the value of msDS-ReplicationEpoch from its nTDSDSA object and assigns this value to the dwReplEpoch field of the DRS_EXTENSIONS_INT structure**; otherwise, it sets the dwReplEpoch field of the DRS_EXTENSIONS_INT structure to zero.

You can have the ``dwReplEpoch`` value with a first ``DsBind``, then make the good structure for the second one.

To reproduce, only modify ``msDS-ReplicationEpoch`` from ``NTDS Settings`` of the targeted domain controller (no need to really renamed a domain).

**Comment by asolino** [comment]
Hey @gentilkiwi thanks for the report!

Of course, making it extensive to @rmbolger and @MichaelGrafnetter. Looks like we are the brotherhood of [MS-DRSR] :P 
@gentilkiwi, you made it really easy for me to fix it with your repro steps. 

Committing in a few seconds and closing this issue.

Thanks again guys!

**Comment by asolino** [comment]
Fixed in https://github.com/CoreSecurity/impacket/commit/7c34db9948dd48275d85b6cee7675a2ac1d079b9, closing!
