### ISSUE TITLE
smbexec and shares

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#156]
@asolino, it seems `smbexec` can't work with user-specified shares (or I didn't get the idea behind it):
```
(venvcrackmapexec)root@kali:~/Partage/impacket_fork/examples# python smbclient.py '<login>:<pass>@192.168.11.144' 
Impacket v0.9.15-dev - Copyright 2002-2016 Core Security Technologies

Type help for list of commands
# shares
ADMIN$
C$
IPC$
NETLOGON
share
SYSVOL
àéyoloshare
# exit
```

So I'd like to use `ADMIN$` or even non-administrative shares such as `àéyoloshare` (for utf-8 testing :p) or even `share` (yes, the share is named share, I like to live dangerously)
```
$ python smbexec.py '<login>:<pass>@192.168.11.144' -share 'ADMIN$' -debug
Impacket v0.9.15-dev - Copyright 2002-2016 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[-] SMB SessionError: STATUS_OBJECT_PATH_NOT_FOUND({Path Not Found} The path %hs does not exist.)
```
It has to be noted that using a user-defined share works with `wmiexec`.

Cheers!

**Comment by maaaaz** [comment]
I just like to add that maybe `smbexec` isn't opsec safe (writing executables etc.) but there are a lot of context where you, the attacker, only sees 445/SMB and no 135/139 as the latter is network filtered so you can't use wmi execution 
=> smbexec stays crucial :)

**Comment by asolino** [comment]
Hey @maaaaz 

Take a look at the latest version and close this issue if fixed on your side.

**Comment by maaaaz** [comment]
Thanks @asolino, it seems to work:
```
(venvcrackmapexec)root@kali:~/Partage/impacket_fork/examples# python smbexec.py '<login>:<pass>@192.168.11.144' -debug -share admin$
Impacket v0.9.15-dev - Copyright 2002-2016 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[+] Executing %COMSPEC% /Q /c echo cd  ^> \\127.0.0.1\admin$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
[!] Launching semi-interactive shell - Careful what you execute
C:\Windows\system32>whoami
[+] Executing %COMSPEC% /Q /c echo whoami ^> \\127.0.0.1\admin$\__output 2^>^&1 > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
nt authority\system
```

But now there's an utf-8 issue :) (reported in  #154).
