### ISSUE TITLE
bug in dcomrt connection

### ISSUE THREAD

**Issue by Bella-Jaguar** [CoreSecurity/impacket#158]
hi

there is a bug in the connect method of INTERFACE in dcerpc/v5/dcomrt.py:
When choosing the string binding, the method first checks if the target is in the string binding. If the string doesn't contain the target, it assumes its a FQDN address, and takes only the first part (before the first dot) and checks it.

the problem is, that when using IP, it could fetch the wrong ip address. for example:
lets say my target has two IP addresses:
192.168.1.100
100.1.1.1

My computer's IP address is 100.1.1.2.

I try to connect to the target using dcomrt, and it returns its hostname and both IPs, where 192.168.1.100 comes first.

So when the method checks for the right string binding, it cheks if 100.1.1.1 is in the target, and it isn't.
Then, it takes the first part of the target i used, which is 100, and checks again, and it is (192.168.1.**100**).

Now, impacket tries to connect to 192.168.1.100, and fails.

To fix it, the method should check whether the string binding address is an IP or a hostname, and then check for FQDN only if it's a hostname.

Bella

**Comment by asolino** [comment]
hey @Bella-Jaguar 

Give it a try to the changset just committed and close this one if working on your side.

thanks

**Comment by asolino** [comment]
@Bella-Jaguar were you able to test this out?

**Comment by asolino** [comment]
No answer from @Bella-Jaguar, closing.
