### ISSUE TITLE
Add ability to specify kdcHost for DCERPC/DCOM

### ISSUE THREAD

**Issue by ropnop** [CoreSecurity/impacket#160]
As discussed in this issue here https://github.com/CoreSecurity/impacket/issues/157

Would be great to have the ability to specify the kdcHost when it can't be reliably determined

**Comment by asolino** [comment]
hey @ropnop give it a try at these changes and close both issues if working on your side.

**Comment by ropnop** [comment]
Thanks @asolino!

Just checked out a verified it's working. I'm testing it in my lab where I only have one DC but the -dc-ip is working as expected! You rock!
