### ISSUE TITLE
GetUserSPNs.py and pyasn1 > 0.1.7 incompatibility

### ISSUE THREAD

**Issue by sk3w** [CoreSecurity/impacket#162]
The GetUserSPNs.py tool does not appear to work for me with pyasn1 0.1.8 or 0.1.9. I get the below message dumped to stdout and the script exits.

`Component value is tag-incompatible: BindRequest(componentType=NamedTypes(NamedType('version', Integer7Bit()), NamedType('name', LDAPDN()), NamedType('authentication', AuthenticationChoice(componentType=NamedTypes(NamedType('simple', AuthSimple()), NamedType('sasl', SaslCredentials(componentType=NamedTypes(NamedType('mechanism', LDAPString()), OptionalNamedType('credentials', OctetString())))), NamedType('sicilyPackageDiscovery', SicilyPackageDiscovery()), NamedType('sicilyNegotiate', SicilyNegotiate()), NamedType('sicilyResponse', SicilyResponse())))))).setComponents(Integer7Bit(3), LDAPDN('***REDACTED***'), AuthenticationChoice(componentType=NamedTypes(NamedType('simple', AuthSimple()), NamedType('sasl', SaslCredentials(componentType=NamedTypes(NamedType('mechanism', LDAPString()), OptionalNamedType('credentials', OctetString())))), NamedType('sicilyPackageDiscovery', SicilyPackageDiscovery()), NamedType('sicilyNegotiate', SicilyNegotiate()), NamedType('sicilyResponse', SicilyResponse()))).setComponents(None, None, None, SicilyNegotiate(hexValue='***REDACTED***')))  vs ProtocolOp(componentType=NamedTypes(NamedType('bindRequest', BindRequest(componentType=NamedTypes(NamedType('version', Integer7Bit()), NamedType('name', LDAPDN()), NamedType('authentication', AuthenticationChoice(componentType=NamedTypes(NamedType('simple', AuthSimple()), NamedType('sasl', SaslCredentials(componentType=NamedTypes(NamedType('mechanism', LDAPString()), OptionalNamedType('credentials', OctetString())))), NamedType('sicilyPackageDiscovery', SicilyPackageDiscovery()), NamedType('sicilyNegotiate', SicilyNegotiate()), NamedType('sicilyResponse', SicilyResponse()))))))), NamedType('bindResponse', BindResponse(componentType=NamedTypes(NamedType('resultCode', ResultCode()), NamedType('matchedDN', LDAPDN()), NamedType('diagnosticMessage', LDAPString()), OptionalNamedType('referral', Referral()), OptionalNamedType('serverSaslCreds', ServerSaslCreds())))), NamedType('searchRequest', SearchRequest(componentType=NamedTypes(NamedType('baseObject', LDAPDN()), NamedType('scope', Scope()), NamedType('derefAliases', DeRefAliases()), NamedType('sizeLimit', IntegerPositive()), NamedType('timeLimit', IntegerPositive()), NamedType('typesOnly', Boolean()), NamedType('filter', Filter(componentType=NamedTypes(NamedType('and', And(componentType=None)), NamedType('or', Or(componentType=None)), NamedType('not', Not(componentType=None, tagSet=TagSet((), Tag(tagClass=0, tagFormat=32, tagId=17)))), NamedType('equalityMatch', EqualityMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AttributeValue())))), NamedType('substrings', SubstringFilter(componentType=NamedTypes(NamedType('type', AttributeDescription()), NamedType('substrings', SubStrings())))), NamedType('greaterOrEqual', GreaterOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AttributeValue())))), NamedType('lessOrEqual', LessOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AttributeValue())))), NamedType('present', Present()), NamedType('approxMatch', ApproxMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AttributeValue())))), NamedType('extensibleMatch', MatchingRuleAssertion(componentType=NamedTypes(OptionalNamedType('matchingRule', MatchingRuleId()), OptionalNamedType('type', TypeDescription()), NamedType('matchValue', matchValueAssertion()), NamedType('dnAttributes', Boolean('False')))))))), NamedType('attributes', AttributeSelection())))), NamedType('searchResEntry', SearchResultEntry(componentType=NamedTypes(NamedType('objectName', LDAPDN()), NamedType('attributes', Attributes())))), NamedType('searchResDone', SearchResultDone(componentType=NamedTypes(NamedType('resultCode', ResultCode()), NamedType('matchedDN', LDAPDN()), NamedType('diagnosticMessage', LDAPString()), OptionalNamedType('referral', Referral())))), NamedType('searchResRef', SearchResultReference())))`

Downgrading to pyasn1 0.1.7 appears to resolve this issue for me. It looks like there were lots of changes in 0.1.8; I don't have the time to dig into it right now, but might be related to this one:

>"Constructed types now verify their consistency by invoking isSameTypeWith(matchTags=True, matchConstraints=False) and isSuperTypeOf(matchTags=False, matchConstraints=True) for each of their components rather than isSuperTypeOf() as it used to be. Constriants check could be enforced to isSameTypeWith() with the strictConstraints=True constructed classes attribute."

**Comment by asolino** [comment]
Hey @sk3w thanks a lot for the report! Helped me a lot to understand the issue.

Let me know if it is working on your side now and close this issue if so.

thanks!

**Comment by sk3w** [comment]
Works like a charm with pyasn 1.0.8 and 1.0.9, thanks @asolino!

**Comment by InfoSecured** [comment]
When I run this, I'm getting "Filter instance has no attribute 'setComponents'" I'm running pyasn1 0.1.7. When I run it on 0.1.9, I get an 'LDAPSearchError'.  Any thoughts on this?
