### ISSUE TITLE
New release on Pypi ETA

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#164]
Hey mate,
I just finished making CME portable and it's now up on Pypi! \o/

The current problem I'm facing though is that CME requires a lot of the changes which are currently on github but not in the 0.9.14 release which is up on Pypi. I was just wondering if you have an ETA on when you'll be releasing the 0.9.15 version on Pypi. 

Thanks!

**Comment by asolino** [comment]
Hola mate!

I don't have a ETA in mind.. usually I tag twice a year. But given your
issue I can tag 0.9.15 and put it on pypi. I can probably do that in the
next two weeks (I'm not completely sure tho). Let me know if this works.

cheers

**Comment by byt3bl33d3r** [comment]
That would be awesome, thanks man.I thought i could get around this by using the dependeny_links attribute in the [setup.py file](https://github.com/byt3bl33d3r/CrackMapExec/blob/master/setup.py) but that's apparently being deprecated.

Thanks again!

**Comment by asolino** [comment]
There you go [0.9.15](https://pypi.python.org/pypi/impacket/0.9.15)

**Comment by byt3bl33d3r** [comment]
@asolino Noice! Thanks man! :D
