### ISSUE TITLE
secretsdump.py uninitialised local variable

### ISSUE THREAD

**Issue by tautology0** [CoreSecurity/impacket#167]
On dumping the hashes from NTDS from secretsdump.py taken from trunk, I get this error for a selection of hashes:

`local variable 'cipherText' referenced before assignment`

I then tried an old version of impacket (0.9.13) and it processed the same ntds file perfectly.

**Comment by asolino** [comment]
Hey @tautology0, thanks for the report.

When you say `dumping the hashes from NTDS` you mean specifying the NTDS.DIT file through the command line so it extracts the hashes?

**Comment by asolino** [comment]
@tautology0 could you please recheck against your environment to verify this solves the original issue?

**Comment by tautology0** [comment]
Yeah, sorry I meant ntds.dit. Just going to refresh and retry

**Comment by tautology0** [comment]
Not getting the error now, so it looks like it fixed it for me!

**Comment by asolino** [comment]
That is great to know @tautology0, thanks for checking it up! Closing.
