### ISSUE TITLE
Can't manage to perform LDAP search with SubstringFilter

### ISSUE THREAD

**Issue by the-useless-one** [CoreSecurity/impacket#170]
Hi guys,

I'm trying to perform an LDAP request against a Windows Domain Controller with a substring filter. Here's how I build the filter:

```
# Performing a search with filter "(samAccountName=*admin*)"
filter = ldapasn1.Filter()
filter['substrings'] = ldapasn1.SubstringFilter()
filter['substrings']['type'] = ldapasn1.AttributeDescription('samAccountName')
filter['substrings']['substrings'] = ldapasn1.SubStrings()
filter['substrings']['substrings'][0] = ldapasn1.SubString().setComponentByName('any', ldapasn1.AnyAssertion('admin'))
```

However, when I try to perform this search, I get this error message from the LDAP server:

```
r00000057: LdapErr: DSID-0C0C09B4, comment: The server was unable to decode a search request filter, data 0, v2580
1.3.6.1.4.1.1466.20036
```

Am I not building the substring filter correctly?

Thanks for your help and for this tool!

Cheers,

Yannick

**Comment by asolino** [comment]
Hey @the-useless-one thanks for the report.

You were building it correctly.. just found out a bug in the ASN1 definition. Please re-check and close the issue if fixed.

**Comment by the-useless-one** [comment]
Great, it works perfectly now! Thanks for the fix and your fast answer.

Cheers,

Yannick
