### ISSUE TITLE
timeout option in smbconnection doesn't work

### ISSUE THREAD

**Issue by hegusung** [CoreSecurity/impacket#173]
During a new SMBConnection call, the timeout parameter passed is not respected, and it hangs for quite a long time.

I believe the issue is due to the socket having not any default timeout value set in nmb.py

I added socket.setdefaulttimeout(timeout) in NetBIOSSession __init__ and it solved my problem

**Comment by asolino** [comment]
hey @hegusung thanks for the report.

Could you please send us a piece of code for us to reproduce this issue? I want to be sure he hit your specific problem.

thanks

**Comment by hegusung** [comment]
Well the piece of code is pretty simple : 

```
from impacket.smbconnection import SMBConnection, SessionError
ip = "8.8.8.8"
timeout = 15
smb = SMBConnection(ip, ip, None, timeout=timeout)
```

On my network outgoing packets are dropped, which means the SYN packet never receives any answer, so the default socket timeout is reached. However in your code you don't call socket.setdefaulttimeout function to change the socket default timeout value to the one specified in argument.

**Comment by asolino** [comment]
thanks for your explanation @hegusung. Please give it a try again and close this issue if fixed.

**Comment by hegusung** [comment]
Seems perfect to me, thanks !
