### ISSUE TITLE
hSamrEnumerateGroupsInDomain response incomplete

### ISSUE THREAD

**Issue by the-useless-one** [CoreSecurity/impacket#174]
Hi guys,

i'm trying to make a samr request to get local groups present on a Windows computer. Here is how I build my request:

```python
# We build the DCE RPC
rpctransport = transport.DCERPCTransportFactory(r'ncacn_np:10.0.0.1[\PIPE\samr]')
dce = rpctransport.get_dce_rpc()
dce.connect()
dce.bind(samr.MSRPC_UUID_SAMR)

# We first get a handle to the server
resp = samr.hSamrConnect(dce)
server_handle = resp['ServerHandle']

# Then we enumerate the domains, so as to get a handle to the local domain
resp = samr.hSamrEnumerateDomainsInSamServer(dce, server_handle)
domains = resp['Buffer']['Buffer']
resp = samr.hSamrLookupDomainInSamServer(dce, server_handle, domains[0]['Name'])
resp = samr.hSamrOpenDomain(dce, serverHandle=server_handle, domainId=resp['DomainId'])
domain_handle = resp['DomainHandle']

# Then we can finally enumerate the groups
enumeration_context = 0
groups = list()
while True:
    resp = samr.hSamrEnumerateGroupsInDomain(dce, domain_handle,
                    enumerationContext=enumeration_context)
    groups += resp['Buffer']['Buffer']

    enumeration_context = resp['EnumerationContext']
    if resp['ErrorCode'] != STATUS_MORE_ENTRIES:
        break

for g in groups:
    print g.dumpRaw()
```

My Windows machine has several local groups:

```
PS C:\Windows\system32> net localgroup

Aliases for \\USELESSERVER01

-------------------------------------------------------------------------------
*Access Control Assistance Operators
*Administrators
*Backup Operators
*Certificate Service DCOM Access
*Cryptographic Operators
*Distributed COM Users
*Event Log Readers
*Guests
*Hyper-V Administrators
*IIS_IUSRS
*Network Configuration Operators
*Performance Log Users
*Performance Monitor Users
*Power Users
*Print Operators
*RDS Endpoint Servers
*RDS Management Servers
*RDS Remote Access Servers
*Remote Desktop Users
*Remote Management Users
*Replicator
*UselessLocalGroup
*Users
*WinRMRemoteWMIUsers__
The command completed successfully.
```

However, my script returns only one group, with RID 513:

```
SAMPR_RID_ENUMERATION

RelativeId:{
    Data: {513}
}

Name:{
    Length: {8}
    MaximumLength: {32}

    Data:{
        ReferentID: {131080}

        Data:{
            MaximumCount: {16}
            Offset: {0}
            ActualCount: {4}
            Data: {u'None'}
        }
    }
}
None
```

If I query aliases instead of groups, I also get partial results:

```
SAMPR_RID_ENUMERATION

RelativeId:{
    Data: {1002}
}

Name:{
    Length: {34}
    MaximumLength: {34}

    Data:{
        ReferentID: {131080}

        Data:{
            MaximumCount: {17}
            Offset: {0}
            ActualCount: {17}
            Data: {u'UselessLocalGroup'}
        }
    }
}
None

SAMPR_RID_ENUMERATION

RelativeId:{
    Data: {1000}
}

Name:{
    Length: {42}
    MaximumLength: {42}

    Data:{
        ReferentID: {131084}

        Data:{
            MaximumCount: {21}
            Offset: {0}
            ActualCount: {21}
            Data: {u'WinRMRemoteWMIUsers__'}
        }
    }
}
None
```

Two groups are returned, but the others are missing.

Is there something I'm not doing correctly? Is this not the correct way to proceed?

Thanks for your help!

Cheers,

Yannick

**Comment by asolino** [comment]
Hey @the-useless-one 

Best way to know what's going on is trying to sniff traffic over the wire when you do something like that. If you sniff traffic when you do `net localgroup /domain` for a domain joined machine you'll see that:

1. A list of target domains is asked with `SamrEnumerateDomainsInSamServer`
2. A domainName to domain SID is done for *ALL* domains returned by means of `SamrLookupDomainInSamServer`
3. Each domainSid is opened with `SamrOpenDomain`
4.  `SamrEnumerateAliasesInDomain` is used to list the domain's groups.

You were actually very close Yannick!.. Just needed to open both domains (including 'Builtin') and use Aliases instead of Groups.
Take a look at this code.. slightly modified from yours.

```python
from impacket.dcerpc.v5 import samr
from impacket.dcerpc.v5 import transport
from impacket.nt_errors import STATUS_MORE_ENTRIES

# We build the DCE RPC
TARGET = '10.0.0.1'
USERNAME = 'yourusername'
PASSWORD = 'yourpassword'
rpctransport = transport.DCERPCTransportFactory(r'ncacn_np:%s[\PIPE\samr]'%TARGET)
rpctransport.set_credentials(USERNAME,PASSWORD)
dce = rpctransport.get_dce_rpc()
dce.connect()
dce.bind(samr.MSRPC_UUID_SAMR)

# We first get a handle to the server
resp = samr.hSamrConnect(dce)
server_handle = resp['ServerHandle']

# Then we enumerate the domains, so as to get a handle to the local domain
resp = samr.hSamrEnumerateDomainsInSamServer(dce, server_handle)
for domain in resp['Buffer']['Buffer']:
    domainName = domain['Name']
    resp = samr.hSamrLookupDomainInSamServer(dce, server_handle, domainName)
    resp = samr.hSamrOpenDomain(dce, serverHandle=server_handle, domainId=resp['DomainId'])
    domain_handle = resp['DomainHandle']

    # Then we can finally enumerate the groups
    enumeration_context = 0
    groups = list()
    while True:
        resp = samr.hSamrEnumerateAliasesInDomain(dce, domain_handle,
                        enumerationContext=enumeration_context)
        groups += resp['Buffer']['Buffer']

        enumeration_context = resp['EnumerationContext']
        if resp['ErrorCode'] != STATUS_MORE_ENTRIES:
            break

    for g in groups:
        print g.dump()
```

Let me know if it works on your side..

I saw you using `dumpRaw()` instead of `dump()`.. Any particular reason on why you did that?
`dumpRaw()` is definitely more low level and most of the times you'll get by with `dump()`.. Its output is cleaner and gives you a better clue on how to access the items.

Btw.. it's awesome to see people using the library instead of just the examples.. way to go!

cheers

**Comment by the-useless-one** [comment]
Hey @asolino,

again, thanks for you very fast answer! It works indeed, thanks a lot. I'll remember to sniff the network before opening an issue next time ;)

Sorry I took so long to respond, but once you unlocked my problem, I started to work right away on my project (heavily based on your awesome library)! You can expect a release soon!

Cheers,

Yannick

**Comment by asolino** [comment]
Good to know it worked @the-useless-one.

Yup.. let me know whenever you release your code!

**Comment by the-useless-one** [comment]
Alright, as @byt3bl33d3r was looking into it in #176, I thought it would be useful to release it now: https://github.com/the-useless-one/pywerview.

It's still incomplete, but I think it can be useful as is (I've already used it a few times in pentest assignments). Let me know what you think, and thanks for your help!

**Comment by byt3bl33d3r** [comment]
@the-useless-one Dude,  that's freaking awesome! This is the missing piece of the puzzle. 
I'll see if I can help you build out its functionality.

**Comment by the-useless-one** [comment]
@byt3bl33d3r thanks! Hope you'll find it useful. I should have some time this weekend to implement some other functionalities. Of course, any help is appreciated ;)

Cheers,

Yannick
