### ISSUE TITLE
WinNT ADSI Provider Support

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#176]
Hey man,

This one's sort of a question/feature request, was wondering if impacket has support for the [WinNT ADSI Provider](https://msdn.microsoft.com/en-us/library/aa772237(v=vs.85).aspx) ? Looked through the tests and couldn't find any mention of it.
It would be immensly useful allowing us to enumerate local groups with an unprivileged domain user.
PowerView uses this in it's [Get-NetLocalGroup](https://github.com/PowerShellMafia/PowerSploit/blob/master/Recon/PowerView.ps1#L6159) function. More information about it over at @HarmJ0y's blog [here](http://www.harmj0y.net/blog/redteaming/local-group-enumeration/)

Cheers!

**Comment by asolino** [comment]
Hola mate,

I heard several times about ADSI but never got into it. Out of the box there's nothing in impacket about it.. 
In any case.. I'm sure most of the times all those higher level APIs end up calling the native ones ;).
Let me read about it and I'll get back to you..

Now.. wrtg local groups.. what about this? (taken from https://github.com/CoreSecurity/impacket/issues/174)
```python
from impacket.dcerpc.v5 import samr
from impacket.dcerpc.v5 import transport
from impacket.nt_errors import STATUS_MORE_ENTRIES

# We build the DCE RPC
TARGET = '10.0.0.1'
USERNAME = 'yourusername'
PASSWORD = 'yourpassword'
rpctransport = transport.DCERPCTransportFactory(r'ncacn_np:%s[\PIPE\samr]'%TARGET)
rpctransport.set_credentials(USERNAME,PASSWORD)
dce = rpctransport.get_dce_rpc()
dce.connect()
dce.bind(samr.MSRPC_UUID_SAMR)

# We first get a handle to the server
resp = samr.hSamrConnect(dce)
server_handle = resp['ServerHandle']

# Then we enumerate the domains, so as to get a handle to the local domain
resp = samr.hSamrEnumerateDomainsInSamServer(dce, server_handle)
for domain in resp['Buffer']['Buffer']:
    domainName = domain['Name']
    resp = samr.hSamrLookupDomainInSamServer(dce, server_handle, domainName)
    resp = samr.hSamrOpenDomain(dce, serverHandle=server_handle, domainId=resp['DomainId'])
    domain_handle = resp['DomainHandle']

    # Then we can finally enumerate the groups
    enumeration_context = 0
    groups = list()
    while True:
        resp = samr.hSamrEnumerateAliasesInDomain(dce, domain_handle,
                        enumerationContext=enumeration_context)
        groups += resp['Buffer']['Buffer']

        enumeration_context = resp['EnumerationContext']
        if resp['ErrorCode'] != STATUS_MORE_ENTRIES:
            break

    for g in groups:
        print g.dump()
```

**Comment by byt3bl33d3r** [comment]
ha! awesome, I'll give that a go asap.

**Comment by asolino** [comment]
great.. let me know how'd it go.

**Comment by asolino** [comment]
@byt3bl33d3r  did you check this mate?

**Comment by byt3bl33d3r** [comment]
@asolino sorry I didn't get back to you! Yup, works great! closing.
