### ISSUE TITLE
GetSPNUsers.py requesting a single kerberos ticket.

### ISSUE THREAD

**Issue by kaleemshaik7867** [CoreSecurity/impacket#178]
Hello @asolino ,

It would be great if we have functionality for requesting a single kerberos ticket for a specific service account.

can we have a feature such as setspn.exe in python to scan the service accounts before requesting kerberos ticket for single account ?

**Comment by asolino** [comment]
Hey @kaleemshaik7867 

> can we have a feature such as setspn.exe in python to scan the service accounts before 
> requesting kerberos ticket for single account ?

This one I don't get it. If you run the script without the `-request` option it will just scan and output the results without requesting the TGS.
Is this what you are looking for?

**Comment by kaleemshaik7867** [comment]
Ahh got it. I was looking for the same.

**Comment by asolino** [comment]
Hey @kaleemshaik7867 

Take a look at the latest commit and try the `-request-user` switch to verify if it works as expected.

**Comment by kaleemshaik7867** [comment]
@asolino 
Thanks for adding new feature. Tested it working as expected. Huge thanks again.

**Comment by asolino** [comment]
Thanks for the verification!

Closing..
