### ISSUE TITLE
GetSPNUsers.py -outputfile JTR Format issue

### ISSUE THREAD

**Issue by kaleemshaik7867** [CoreSecurity/impacket#179]
Hello @asolino ,

I have requested kerberos ticket for service account and using -outputfile I have saved it to disk. When I feed this output to John the hashes are not recognized. I am using the latest version of john which supports krb5tgs format.

I did the same using timmedin technique and converted the 'kirbi' file using kirbi2john.py forwarded the output to john it recognized the format and able to crack the ticket.

Here is the out put for john when I use -outputfile option

root@kali:~/Desktop/kerberoast/JohnTheRipper/run# ./john '/root/Desktop/kerberoast/kerbi' 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

**Comment by asolino** [comment]
Hey @kaleemshaik7867 

Can you output the first 100 bytes of both output files?.. I cannot reproduce it in here.. Downloading the latest john version an retesting.

**Comment by kaleemshaik7867** [comment]
@asolino 

Attaching the output of both the tools  and kirbi file . Please let me know if you require any more info

[test.zip](https://github.com/CoreSecurity/impacket/files/369349/test.zip)

**Comment by asolino** [comment]
Hey @kaleemshaik7867 

Thanks a lot for the files.. can you please re-test and verify if the issue's solved?

**Comment by kaleemshaik7867** [comment]
@asolino 
AWESOME!! issue has been resolved. John able to recognize the hashes and able to crack the tickets.
Thanks for Quick fix.

**Comment by asolino** [comment]
Great to know @kaleemshaik7867.. Thanks for reporting this!

Closing...
