### ISSUE TITLE
Creating a golden ticket (Not MS14-068)

### ISSUE THREAD

**Issue by swordgardctf** [CoreSecurity/impacket#181]
Would it be possible to add an example on how to create a golden ticket without going through a Windows computer (such as through mimikatz right now) by giving it the krbtgt hash? Right now goldenPac can be used for domain controllers vulnerable to MS14-068 but as far as I can tell there is no example for normal golden tickets.

**Comment by asolino** [comment]
Hey @swordgardctf 

Indeed there's no example of a golden ticket creation script, and we have pretty much everything there already. (i.e. the [makeGolden](https://github.com/CoreSecurity/impacket/blob/master/examples/raiseChild.py#L1062) method).

There's a temporary solution that might work for you, that involves using [raiseChild](https://github.com/CoreSecurity/impacket/blob/master/examples/raiseChild.py#L1062) against a domain, regardless of that domain being a subchild of a forest (in fact, you can throw that script against any DC).
If you specify the `-w` parameter it will save a ticket valid for [10](https://github.com/CoreSecurity/impacket/blob/master/examples/raiseChild.py#L1086) years that can be used later (by means of the KRB5CCNAME variable and the [-k](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L280) and [-no-pass](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L279) parameters in any script). Only problem is you cannot control de ticket's username and other interesting parameters you could play with with a proper tool.

I'll leave this as an enhancement in case somebody's willing to start this before we do (no ETA).

**Comment by asolino** [comment]
Hey @swordgardctf 

In case you haven't noticed, we created [a script](https://github.com/CoreSecurity/impacket/commit/5812bee6f60b1cf4aecad46d304c197ef7e7b051) that is mean exactly for that. Let us know if it's useful for you.
