### ISSUE TITLE
dhcp.py DHCPTool class reviewing (dead-code?)

### ISSUE THREAD

**Issue by franferrax** [CoreSecurity/impacket#187]
We have spotted some code on dhcp.py ([DHCPTool](https://github.com/CoreSecurity/impacket/blob/impacket_0_9_15/impacket/dhcp.py#L204) class) that seems to be dead-code. We suggest a review of this code and remove it if applies.

**Comment by asolino** [comment]
done!

**Comment by franferrax** [comment]
Now, there are some unused imports that may cause issues, mainly for people not having `pcapy` installed. Sorry for the inconvenience!

**Comment by asolino** [comment]
Thanks for letting me know that @franferrax. My fault actually that I didn't review the imports left.

Let me know if there's anything else left to do.
