### ISSUE TITLE
Implement paging in LDAP search

### ISSUE THREAD

**Issue by the-useless-one** [CoreSecurity/impacket#190]
Hey man,

I was just testing pywerview during a pentest assignment, and I got an error while querying the domain users. Since there are more than 1000 users, I get this exception:

```
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/yme/tools/pywerview/pywerview/main.py", line 351, in main
    results = args.func(**parsed_args)
  File "/home/yme/tools/pywerview/pywerview/net.py", line 99, in get_netuser
    for user in domain_connection.search(searchFilter=user_search_filter, attributes=list()):
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 331, in search
    raise LDAPSearchError(error = int(protocolOp['searchResDone']['resultCode']), errorString = 'Error in searchRequest -> %s:%s' % (protocolOp['searchResDone']['resultCode'].prettyPrint(), protocolOp['searchResDone']['diagnosticMessage'] ), answers=answers)
impacket.ldap.ldap.LDAPSearchError: Error in searchRequest -> 'sizeLimitExceeded':
```

I've seen from [your source code](https://github.com/CoreSecurity/impacket/blob/master/impacket/ldap/ldap.py#L17) that it's on your TODO list, but I just wanted to make sure that this issue was known, to raise awareness if people wanted to help implement search paging.

I'll try to take a look at it if I get the time.

Again, thanks for your awesome library!

Cheers,

Y

**Comment by asolino** [comment]
Hey @the-useless-one..

Yep indeed implementing paging your be neat.. Help needed! ;)

A few things to consider tho:
1. Try to restrict the results based on the search query (meaning, adding as many filters as possible to restrict whatever is returned). 
2. If the final result is still big, use the `sizeLimitExceeded` parameter in the `LDAPConnection.search()` method.
3. Check this [commit](https://github.com/CoreSecurity/impacket/commit/60f9fa627b3553e0330cbe543571a9db9ef672f1), in case you don't have the latest impacket dev branch installed. It might be helpful.

**Comment by the-useless-one** [comment]
Ah, this commit should indeed be useful! I'll try/except for now, and try to see what I can do for search paging.

Thanks!

**Comment by the-useless-one** [comment]
So, I took a look at implementing search paging, but I'm kind of having a hard time, since I don't know shit about ASN1 specs and such :p. I did a first try with this commit: daaa39f982c83f6ebe292291b08dc1351016f5a1. It's based on [RFC2696](https://tools.ietf.org/html/rfc2696).

Sending the request seems to work, but when impacket tries to decode the message with the paging control, I get this error:

```
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/yme/tools/pywerview/pywerview/main.py", line 302, in main
    results = args.func(**parsed_args)
  File "/home/yme/tools/pywerview/pywerview/net.py", line 99, in get_netuser
    for user in domain_connection.search(searchFilter=user_search_filter, attributes=list()):
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 356, in search
    resp = self.sendReceive('searchRequest', searchRequest, searchControls)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 414, in sendReceive
    return self.recv()
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 404, in recv
    raise e
pyasn1.error.PyAsn1Error: TagSet(Tag(tagClass=0, tagFormat=0, tagId=4)) not in asn1Spec: {TagSet(Tag(tagClass=0, tagFormat=0, tagId=1)): Boolean('False')}/{}
```

The encoded message is
```python
ldap_message = '3084000002890201046584000000070a010004000400a0840000027330840000026d0416312e322e3834302e3131333535362e312e342e33313904840000024f3084000002490201000484000002400100000040020000ffffffff37c985980f4b9f5f3a70dabb743e865b99c2041fe5c6413118277114358ba1117436333cd12c1b4b8140892f2bdda5320000000001000000000000003814000016000000050000000200000000000000000000000500000043000a00d7070000d6070000d7070000000000000fabe4df66b95d46af066cffa2e13bd10000000002000000010000000000000000000000ffffffff19040000e80300000000000000000000000000000000000000000000000000000000000001000000ffffffff57316cb6b36d343b39b6a9aaae1a8039b6baaf8a6923dafa9f3fb9b74dd415a9000000007f0e990e210e910e990d030d2a0d2a0d2001010101007f80001438000000000000000000ffffffff0000000000000000dd0009000e00000000000000ff000000494e4445585f3030303930304444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000'.decode('hex')
```

If I try to decode it without specifying `LDAPMessage` as an `asn1Spec`, it works:

```python
>>> from pyasn1.codec.der import decoder
>>> decoder.decode(ldap_message)
(Sequence().setComponentByPosition(0, Integer(4)).setComponentByPosition(1, Integer(0)).setComponentByPosition(2, Sequence().setComponentByPosition(0, OctetString('1.2.840.113556.1.4.319')).setComponentByPosition(1, OctetString(hexValue='3084000002490201000484000002400100000040020000ffffffff37c985980f4b9f5f3a70dabb743e865b99c2041fe5c6413118277114358ba1117436333cd12c1b4b8140892f2bdda5320000000001000000000000003814000016000000050000000200000000000000000000000500000043000a00d7070000d6070000d7070000000000000fabe4df66b95d46af066cffa2e13bd10000000002000000010000000000000000000000ffffffff19040000e80300000000000000000000000000000000000000000000000000000000000001000000ffffffff57316cb6b36d343b39b6a9aaae1a8039b6baaf8a6923dafa9f3fb9b74dd415a9000000007f0e990e210e910e990d030d2a0d2a0d2001010101007f80001438000000000000000000ffffffff0000000000000000dd0009000e00000000000000ff000000494e4445585f3030303930304444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000'))), '')
```

Any idea where I went wrong?

**Comment by kacpern** [comment]
Hey folks. I've been trying to dig into this over the weekend. With some success.
The issues are in [ldapasn1.py](https://github.com/CoreSecurity/impacket/blob/master/impacket/ldap/ldapasn1.py)

```python
class Control(Sequence):
    componentType = NamedTypes(
        NamedType('controlType', LDAPOID()),
        NamedType('criticality', Boolean(False)),
        OptionalNamedType('controlValue', OctetString()),
)
```

should be implemented as:
```python
class Control(Sequence):
    componentType = NamedTypes(
        NamedType('controlType', LDAPOID()),
        DefaultedNamedType('criticality', Boolean(False)),
        OptionalNamedType('controlValue', OctetString()),
)
```

I've found some other missing DefaultedNamedType() (e.g. in MatchingRuleAssertion()).

This will make your error go away.

I'll be working this week to hopefully make this happen,

Additionally is there a reason to use the DER decoder? According to [RFC 4511](https://tools.ietf.org/html/rfc4511#section-5.1) it SHALL use BER.

**Comment by the-useless-one** [comment]
Ah, thanks @kacpern, I suspected the problem was with the definition of `criticality`, but didn't know what to fix! as to the use of DER encoding, if you're referring to my code snippet, that's because it is what's used in the [`send` method](https://github.com/CoreSecurity/impacket/blob/master/impacket/ldap/ldap.py#L367). If you're referring in fact to the `send` method, I'll let @asolino answer.

Thanks again!

**Comment by asolino** [comment]
Hey @kacpern and @the-useless-one .. Thanks for taking a look at this..

Just fixed the errors described in here.. let me know if there's anything else left for fixing (or just issue a PR).

cheers guys

**Comment by asolino** [comment]
hey @the-useless-one, please check again after @kacpern addition if your test cases pass. If so please close this one. 

From my side, it's working great.

**Comment by the-useless-one** [comment]
It's also working on my side, thanks @kacpern for the great work!

I was just wondering if LDAP searches shouldn't be made with paging control by default? Right now, you have to give a `searchControls=[ldapasn1.SimplePagedResultsControl()]` parameters to your search, which is easy enough, but making it a default feature would benefit the users, don't you think?

**Comment by kacpern** [comment]
You probably want to call it with keyword arguments, especially the first one set to True (criticality), otherwise the server may silently ignore the control if it's not supported, and you won't even get an error.

I think I'm against making it default, reason is this is an extension to the protocol. You could always use _partial()_ from _functools_ to wrap around it with your default parameters to make it more seamless.

I won't be mad if it's made default :-) Or we could add a helper method like searchPaged _LDAPConnection()_ to the class or something.

**Comment by the-useless-one** [comment]
I see what you mean, your argument makes sense. Anyway, the decision is up to @asolino!

Again, thanks for the PR, I'm closing this.
