### ISSUE TITLE
Infinite loop in ESENT_DB::openTable

### ISSUE THREAD

**Issue by hexadite-virnik** [CoreSecurity/impacket#199]
In ESENT_DB::openTable runs into infinite loop when page.record['FirstAvailablePageTag'] is zero. (and it happens from time to time)

**Comment by asolino** [comment]
Thanks for your report @hexadite-virnik.
Wondering whether [this line](https://github.com/CoreSecurity/impacket/blob/master/impacket/ese.py#L750) should be `< 1` instead of `== 1`.. 
Did you run other similar tools to parse the ESE database?

I'm assuming you cannot share a file that triggers this issue right?

**Comment by hexadite-virnik** [comment]
Thanks for the fast response @asolino  :)
It is true that I can't share the files that triggers this issues.
I change it to `<=` and it fixed the issue. (but honestly I don't know if it sould be `<` or '<=')

**Comment by asolino** [comment]
hey @hexadite-virnik .. now thank you for your fast answer :)
Actually I meant `<=1`.. thanks for pointing that up.
Good to know that fixed the issue.. I'll try to dig deeper to understand whether that's the right fix tho.

thanks!

**Comment by asolino** [comment]
hey again @hexadite-virnik .. I know you cannot share those databases.. but if you could please add the following code *before* [this line](https://github.com/CoreSecurity/impacket/blob/master/impacket/ese.py#L750):
```
page.record.dump()
```
and send me the output that'd be helpful.

**Comment by hexadite-virnik** [comment]
Here is the output:
`ESENT_PAGE_HEADER
CheckSum: {0}
LastModificationTime: {0}
PreviousPageNumber: {0}
NextPageNumber: {0}
FatherDataPage: {0}
AvailableDataSize: {0}
AvailableUncommittedDataSize: {0}
FirstAvailableDataOffset: {0}
FirstAvailablePageTag: {0}
PageFlags: {0}
ExtendedCheckSum1: {0}
ExtendedCheckSum2: {0}
ExtendedCheckSum3: {0}
PageNumber: {0}
Unknown: {0}`

**Comment by asolino** [comment]
Hey @hexadite-virnik. If you can git pull and retest that'd be great. In theory it should work now.

thanks for your help
