### ISSUE TITLE
Removed SMBBackwardCompatibilityTransport class still referenced in transport.py

### ISSUE THREAD

**Issue by franferrax** [CoreSecurity/impacket#203]
In [b4e05b, transport.py](https://github.com/CoreSecurity/impacket/commit/b4e05b5ad1d8f665d54b9a3a833bff498c10c3fd#diff-261110502c4bc6e3e5882fdb7067f4f2L428), the `SMBBackwardCompatibilityTransport` class was removed, but an usage was missed in [line 377](https://github.com/CoreSecurity/impacket/blob/fe705da38e1448819ecd83762cd979950e5e8468/impacket/dcerpc/v5/transport.py#L377). This is only triggered when we instantiate a `SMBTransport` class with an already created _SMBv1_ `SMBConnection`. This is an unlikely use case and I think that this is the reason why the problem was never discovered until now.

**Comment by asolino** [comment]
Thanks for reporting this @franferrax !
