### ISSUE TITLE
Host parameter not set during a SMB authentication

### ISSUE THREAD

**Issue by hegusung** [CoreSecurity/impacket#207]
Hi,
I observered that during an SMB2 authentication the HOST parameter is not set, resulting in a NULL value in the windows event logs.
To be more precise the function getNTLMSSPType3 in ntml.py doesn't set the "host_name" value like it does for "user_name".

**Comment by asolino** [comment]
hey @hegusung!

Yes.. you are correct on your observation. Sending the `host_name` is not enforced by the NTLM protocol.
Are you needing that information for something in particular? I mean.. the library itself is not ready to specify the source host name that is being authenticated unless you programmatically call `getNTLMSSPType1` and `getNTLMSSPType3` (if that's the case, this issue could be easily fixed). On the other hand, sending the hostname of the source machine doesn't sound like a good idea given the nature of this tool. 
Just wondering if I'm missing something.

thanks!

**Comment by hegusung** [comment]
I am using your tool for a pentest mission, however my client caught this strange behavior in his logs. 

What is strange is that you can set the "my_name" parameter in SMB3 class, but it doesn't work... It looks more like a bug than a wanted feature.

I you wish I can submit a merge request to correct it ?

**Comment by asolino** [comment]
> I am using your tool for a pentest mission, however my client caught this strange behavior in his logs.

That's exactly what I wanted to understand @hegusung, thanks!
Good job by your client btw..

Yes.. for SMB3 things are slightly easier... it gets messy when dealing with DCERPC.

May I ask how do you use the library?.. Do you develop your own scripts or you use the example ones?

> I you wish I can submit a merge request to correct it ?

Let me take a quick look myself today and tomorrow. Then your PRs are very welcome ;)

**Comment by hegusung** [comment]
Thanks for your quick answer !

I have my own scripts made based on your examples, this library is absolutely perfect for my needs !

I look forward for your commit ;)

**Comment by asolino** [comment]
Ok.. this a start.. 

Give a try and let me know.. 
It will *not* work for DCE/RPC connections since you can't specify the workstation name. If we want to add this feature to that layer we will need to figure out the right approach.

If you want to do a little hack and force workstation name for every connection (including DCERPC) just change this [line](https://github.com/CoreSecurity/impacket/blob/master/impacket/ntlm.py#L598) to something like this:
```
auth.setWorkstation('BADCLIENT')
```

Let me know if it works on your side.

**Comment by hegusung** [comment]
It works perfectly ! I now got the desired hostname in the logs.

Thanks !
