### ISSUE TITLE
v0.9.15 smbrelayx.py - missing outputToJohnFormat

### ISSUE THREAD

**Issue by benrasper** [CoreSecurity/impacket#212]
Hello!

I am attempting to run smbrelayx.py but am presented with the following error:

# python smbrelayx.py
Traceback (most recent call last):
  File "smbrelayx.py", line 66, in <module>
    from impacket.smbserver import outputToJohnFormat, writeJohnOutputToFile, SMBSERVER
ImportError: cannot import name outputToJohnFormat

I've looked high and low for this but have come up empty handed. I did not see this issue in v0.9.12. Any help is appreciated.

Thank you!

**Comment by asolino** [comment]
Hey @benrasper, can't reproduce your issue.

Just in case.. run python and type the following code:
```
from impacket import version
print version.BANNER
```
 and send me the output please.

**Comment by benrasper** [comment]
Hello asolino,

Here is the output you've requested below. Interestingly enough, it seems that python is still referencing the former version of Impacket rather than the newer version I cloned.

# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from impacket import version
>>> print version.BANNER
Impacket v0.9.12 - Copyright 2002-2014 Core Security Technologies

>>> quit()

Thank you,
Ben

**Comment by asolino** [comment]
That is the problem @benrasper. Are you on Kali?.. I heard that before.

You will need to either remove the python-impacket package (if Kali) and/or manually remove the old version. Go back to python and type:
```
from impacket import version
print version.__file__
```
Now you know where the old impacket version is installed.. just go ahead and remove the whole impacket directory.

Now try again the previous step..

**Comment by benrasper** [comment]
Hello @asolino,

Yes, I'm using Kali 2.0, and I've deleted the old impacket directory. This seems to have done the trick! I am now able to use smbrelayx.py.

# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from impacket import version
>>> print version.BANNER
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

>>> print version.__file__
impacket/version.py
>>> quit()

Thank you so much for your support!

Regards,
Ben
