### ISSUE TITLE
I installed it on RHEL 7 however I get the below error when I use psexec.py

### ISSUE THREAD

**Issue by sandeep239** [CoreSecurity/impacket#221]
Traceback (most recent call last):
  File "/usr/bin/psexec.py", line 29, in <module>
    from impacket.dcerpc.v5 import transport
  File "/usr/lib/python2.7/site-packages/impacket/dcerpc/v5/transport.py", line 21, in <module>
    from impacket.dcerpc.v5.rpcrt import DCERPCException, DCERPC_v5, DCERPC_v4
  File "/usr/lib/python2.7/site-packages/impacket/dcerpc/v5/rpcrt.py", line 23, in <module>
    from Crypto.Cipher import ARC4
ImportError: No module named Crypto.Cipher

**Comment by asolino** [comment]
You need to install pycrypto ( I think it is python-pycrypto in RHEL 7)

**Comment by asolino** [comment]
@sandeep239 did you try installing pycrypto?

**Comment by sandeep239** [comment]
Yes, I did try that I was able to install it afterward by installing 
pycrypto
pyasn1

However now when I am try to connect to any machine it throws error as below.

[*] Requesting shares on clm-pun-012028.....
[*] Found writable share ADMIN$
[*] Uploading file vicvqrfa.exe
[*] Opening SVCManager on clm-pun-012028.....
[*] Creating service tPMF on clm-pun-012028.....
[*] Starting service tPMF.....
Traceback (most recent call last):
  File "psexec.py", line 216, in connectPipe
    self.server = SMBConnection(self.transport.get_smb_connection().getRemoteName(), self.transport.get_smb_connection().getRemoteHost(),
AttributeError: SMBConnection instance has no attribute 'getRemoteName'
[-] Something wen't wrong connecting the pipes(<class '__main__.RemoteStdInPipe'>), try again
[!] Press help for extra shell commands

**Comment by asolino** [comment]
Hey @sandeep239 
What version of impacket are you running? You get that message at the very beginning of the psexec.py execution. Remember you have to run the psexec.py version that matches the impacket version installed. 
Meaning, for example, if you have 0.9.15 installed, you cannot grab psexec.py from github's master branch.

Looks like you have versions mismatch.

**Comment by o-o-x** [comment]
Try:
apt install python-pyasn1 python-crypto

**Comment by asolino** [comment]
No answer.. closing
