### ISSUE TITLE
smbexec via 445 cause "SMBTransport instance has no attribute 'setRemoteHost'"

### ISSUE THREAD

**Issue by QianJin2013** [CoreSecurity/impacket#224]
Hi, I found some source degrade.

when use smbexec.py with 445 port instead of default 135 port, error `[-] SMBTransport instance has no attribute 'setRemoteHost'` occured.

If i comment it, then another error occurs at getRemoteHost.

So pity.

It totally not works on a single SMB, but previously i have fixed the bugs: https://github.com/CoreSecurity/impacket/pull/118

I will fix it again when i have time.

**Comment by asolino** [comment]
Hey @QianJin2013 

I can reproduce the issue. Can you please tell me how are you executing `smbexec.py`? Default port for `smbexec.py` is 445. Port 135 is not used.

**Comment by QianJin2013** [comment]
First, let me explain why i care pure SMB and hate RPC over TCP 135.

The RPC's authentication mechanism is so sucks, it seems use current user's domain identity to talk with target's RPC server, so normally end with the error "Access Denied" unless you are running as a elevated administrator of the target machine.

The SMB protocol have good authentication mechanism, you can specify user/password, or use kerberos ticket. Once authenticated, you can carry RPC payload over the SMB channel without authenticate again, so it's smart.

A long time ago, i'd modified smbexec.py concerned lib, see [this pull request](https://github.com/sjitech/impacket/blob/264ac838c5c75a28cddaa5956c8e68fa419ff496/examples/rpcdump.py
)  and got merged a long time ago. 

`The modified version of Impacket works fine with pure SMB, without 135 port.`

```
smbexec.py` user:pwd@192.168.99.101 445/SMB
```



Now, let's look at what problem of the current version, the steps to reproduce the problem:

1. Please refer https://github.com/CoreSecurity/impacket/pull/118 to disable all ports except 445 on target machine.

2. run smbexec, specify port 445.
```
smbexec.py user:pwd@192.168.99.101 -port 445
```
It fails with "SMBTransport instance has no attribute 'setRemoteHost'" or just hung there.

It fails even i manually fixed setRemoteHost and setRemoteHost etc. I think the reason is same as before: some other common class still using 135 port.

----


**BTW, isn't anyone noticed there is another design degrade of using port number to indicate protocol?**
How can a user specify to use SMB protocol with port 8888, instead of 445?

So the old design 445/SMB was perfect. You can specify 8888/SMB.

**Comment by QianJin2013** [comment]
From Windows Vista, RPC/TCP can cause extra problem such as 20 seconds huang up.
See [Services and RPC/TCP](https://msdn.microsoft.com/ja-jp/library/windows/desktop/dd578505(v=vs.85).aspx)

> Starting with Windows Vista, the service control manager (SCM) supports remote procedure calls over both Transmission Control Protocol (RPC/TCP) and named pipes (RPC/NP). Client-side SCM functions use RPC/TCP by default.

> If the server is running a version of Windows that does not support RPC/TCP, or supports RPC/TCP but is operating behind a firewall which allows only named pipe traffic, the RPC/TCP connection times out and the SCM retries the connection with RPC/NP. This will succeed eventually but can **take some time (typically more than 20 seconds)**, causing the OpenSCManager function to appear blocked.

>**TCP does not carry user credentials specified with a net use command**. Therefore, if RPC/TCP is enabled and sc.exe or an OpenSCManager function call is used to attempt to access the specified service, the command could fail with access denied.

**Comment by asolino** [comment]
Hey @QianJin2013... thanks for your comments. I still can't reproduce your issue tho.

1) Applied the firewall rules you specified and then ran nmap against the target:
```
 Nmap scan report for freefly.net* (172.16.123.170)
 Host is up (0.00055s latency).
 PORT    STATE    SERVICE
 53/tcp  filtered domain
 88/tcp  filtered kerberos-sec
 135/tcp filtered msrpc
 137/tcp filtered netbios-ns
 138/tcp filtered netbios-dgm
 139/tcp filtered netbios-ssn 
 389/tcp filtered ldap
 445/tcp open     microsoft-ds
 464/tcp filtered kpasswd5
```

 2) run smbexec, specify port 445.
```
dummy:examples nobody$ ./smbexec.py Administrator@172.16.123.170 -port 445
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
[!] Launching semi-interactive shell - Careful what you execute
C:\Windows\system32>whoami
nt authority\system

C:\Windows\system32>
```

Can you check what impacket version are you running? It is shown when you run the script.

**Comment by QianJin2013** [comment]
Thank you for your test again.  That's a good news. Seems something i did wrong.  I will test it again.

My version is: Impacket v0.9.14-dev

The source version:
8bb3df2 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1 from CoreSecurity/master

I still get same error, maybe just because i did not run setup? I'v already have an very old version installed into python's lib.

Currently, i run smbexec.py from PyCharm IDE, I will debugged into deep to see where it goes.

**Comment by QianJin2013** [comment]
No problem now. I delete /Library/Python/2.7/site-packages/impacket then it works.

I am sorry, I apologize for my complains. 

Thank you for your great works! This is the fastest tool to use SMB, i like it very much.

**Comment by asolino** [comment]
Great to you know things are working fine @QianJin2013 and thanks for the nice comments about impacket!
