### ISSUE TITLE
'module' object has no attribute "LDAPsearcherror" - GetUserSPNs.py

### ISSUE THREAD

**Issue by InfoSecured** [CoreSecurity/impacket#234]
Everytime I run GetUserSPNs.py, I get the following error message.  I can't seem to figure this out. Any thoughts?

'module' object has no attribute "LDAPsearcherror"

**Comment by asolino** [comment]
Hey @InfoSecured 

I Can't find that text inside impacket, please send me the output (pasted) you receive, and the original command you execute.

Also please tell me what version of pyasn1 you are running. And easy way to check it is:
```
$ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyasn1
>>> pyasn1.__version__
'0.2.2'
>>> 

```

**Comment by asolino** [comment]
Hey @InfoSecured 

Did you try again with the latest changes and pyasn1 new version support?
Let me know please

**Comment by asolino** [comment]
Closing...
