### ISSUE TITLE
struct.error: unpack requires a string argument of length 2

### ISSUE THREAD

**Issue by contactr2m** [CoreSecurity/impacket#235]
There is a another Isilon cifs server that i am working on. 
{{{
> c = SMBConnection("10.1.22.245", "10.1.22.245", preferredDialect=None)
> c.login("user1", "password1", "domain1")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "impacket/smbconnection.py", line 260, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "impacket/smb3.py", line 742, in login
    av_pairs = ntlm.AV_PAIRS(ntlmChallenge['TargetInfoFields'][:ntlmChallenge['TargetInfoFields_len']])
  File "impacket/ntlm.py", line 206, in __init__
    self.fromString(data)
  File "impacket/ntlm.py", line 229, in fromString
    fType = struct.unpack('<H',tInfo[:struct.calcsize('<H')])[0]
struct.error: unpack requires a string argument of length 2

}}}
Negotiation went well.
{{{
>>> c.negotiateSession()
True

}}}

[Isilon_impacket_login.pcap.zip](https://github.com/CoreSecurity/impacket/files/634029/Isilon_impacket_login.pcap.zip)

Trying to get more data..  Just started the day :)

**Comment by asolino** [comment]
Looking into it right now thanks @contactr2m!

**Comment by contactr2m** [comment]
This is what the data is.. 
data= '\x00\x0fD\x00E\x00V\x00\x02\x00\x06\x00D\x00E\x00V\x00\x01\x00\x12\x00I\x00S\x00I\x00L\x00O\x00N\x007\x00-\x001\x00\x04\x00"\x00D\x00E\x00V\x00.\x00C\x00C\x00.\x00A\x00R\x00R\x00I\x00A\x00D\x00.\x00C\x00O\x00M\x00\x03\x002\x00i\x00s\x00i\x00l\x00o\x00n\x007\x00.\x00d\x00e\x00v\x00.\x00c\x00c\x00.\x00a\x00r\x00r\x00i\x00a\x00d\x00.\x00c\x00'

ntlm.AV_PAIRS(data[:len(data)])
Its not been calculated correctly 
"First": COM2isilon7.dev.cc.arriad.c
"Second": ""
"Thirt": Exception raised

**Comment by contactr2m** [comment]
Hrmm ok the issue is incorrect data in TargetInfoFields

>Correct_data = '\x02\x00\x06\x00D\x00E\x00V\x00\x01\x00\x12\x00I\x00S\x00I\x00L\x00O\x00N\x007\x00-\x001\x00\x04\x00"\x00D\x00E\x00V\x00.\x00C\x00C\x00.\x00A\x00R\x00R\x00I\x00A\x00D\x00.\x00C\x00O\x00M\x00\x03\x002\x00i\x00s\x00i\x00l\x00o\x00n\x007\x00.\x00d\x00e\x00v\x00.\x00c\x00c\x00.\x00a\x00r\x00r\x00i\x00a\x00d\x00.\x00c\x00o\x00m\x00\x00\x00\x00\x00'

>ntlm.AV_PAIRS(Correct_data[:len(Correct_data)])
<impacket.ntlm.AV_PAIRS instance at 0x10f844488>

{{{
ntlm.AV_PAIRS(Correct_data[:len(Correct_data]).dump()
0: {(0, '')}
1: {(18, 'I\x00S\x00I\x00L\x00O\x00N\x007\x00-\x001\x00')}
2: {(6, 'D\x00E\x00V\x00')}
3: {(50, 'i\x00s\x00i\x00l\x00o\x00n\x007\x00.\x00d\x00e\x00v\x00.\x00c\x00c\x00.\x00a\x00r\x00r\x00i\x00a\x00d\x00.\x00c\x00o\x00m\x00')}
4: {(34, 'D\x00E\x00V\x00.\x00C\x00C\x00.\x00A\x00R\x00R\x00I\x00A\x00D\x00.\x00C\x00O\x00M\x00')}
}}}

>Incorrect_data = '\x00\x0fD\x00E\x00V\x00\x02\x00\x06\x00D\x00E\x00V\x00\x01\x00\x12\x00I\x00S\x00I\x00L\x00O\x00N\x007\x00-\x001\x00\x04\x00"\x00D\x00E\x00V\x00.\x00C\x00C\x00.\x00A\x00R\x00R\x00I\x00A\x00D\x00.\x00C\x00O\x00M\x00\x03\x002\x00i\x00s\x00i\x00l\x00o\x00n\x007\x00.\x00d\x00e\x00v\x00.\x00c\x00c\x00.\x00a\x00r\x00r\x00i\x00a\x00d\x00.\x00c\x00'

{{{
ntlm.AV_PAIRS(Incorrect_data[:len(Incorrect_data)])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/impacket/ntlm.py", line 206, in __init__
    self.fromString(data)
  File "/usr/local/lib/python2.7/site-packages/impacket/ntlm.py", line 229, in fromString
    fType = struct.unpack('<H',tInfo[:struct.calcsize('<H')])[0]
error: unpack requires a string argument of length 2
}}} 

This boils downs to ntlm.NTLMAuthChallenge() method

**Comment by asolino** [comment]
Weirdness of a protocol @contactr2m. Please take a look at https://github.com/CoreSecurity/impacket/commit/2681d1f5de5c6122883a947bc57d431071f0beb5 and close this issue if it works on your side.

**Comment by contactr2m** [comment]
Working ! 💯 
@asolino great find about NTLMSSP_NEGOTIATE_VERSION and domain_name. 
& thanks for mentioning [MS-NLMP] 2.2.2.10, i couldn't find that document before. 👍

**Comment by asolino** [comment]
Great to know it works @contactr2m!..

Looks like you have a pretty interesting variety of CIFS devices.. keep testing impacket against them please! :)

**Comment by contactr2m** [comment]
Yes i do :)
I've implemented some more functionalities like ACE, ACL, Security descriptor, all sorts of file query information classes, enhanced query directory, sid lookup etc.  i will create prs soon. you may want to take a look at them..  👍

**Comment by asolino** [comment]
Right on! PRs welcomed!

cheers mate!
