### ISSUE TITLE
SessionError exception not populating packet info in SMBConnection wrapper.

### ISSUE THREAD

**Issue by contactr2m** [CoreSecurity/impacket#236]
PS: May not be an issue but not sure if i am using it correctly.

Trying to understand SessionError.

>try :
    c._SMBClient__connection.listPath("share1", "\\")
except Exception as e :e
e
SessionError()
e.getErrorString()
('STATUS_INVALID_PARAMETER', 'An invalid parameter was passed to a service or function.')
e.getErrorCode()
3221225485

These values are useful but what about package.

>e.packet
0
e.getErrorPacket()
0

Its not getting populated. 
If i directly use SMB3 instance then i do see it.

>try :c._SMBClient__connection._SMBConnection.list_path("rohitsim_ntfs", "\\")
except Exception as e:
    e
e.packet
<impacket.smb3structs.SMB2Packet instance at 0x102ffaf80>
e.packet.dump()
SMB2Packet
ProtocolID: {'\xfeSMB'}
StructureSize: {64}
CreditCharge: {1}
Status: {3221225485}
Command: {14}
CreditRequestResponse: {87}
Flags: {1}
NextCommand: {0}
MessageID: {29}
Reserved: {0}
TreeID: {2373}
SessionID: {24912}
Signature: {'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
Data: {'\t\x00\x00\x00\x00\x00\x00\x00\x00'}

I would like to have this info if something fails.
It looks like in SMBConnection wrapper all SessionErrors are raised with only e.get_errorcode()

I think it will have to be changed at all SessionError exceptions. 

Something like raise SessionError(e.get_error_code(), e.get_error_packet()) ?

**Comment by asolino** [comment]
The reason why it is coded that way is because the SMB1 implementation doesn't have the packet information. 
I could still make it available to the consumer just for SMB > 1 tho. Let me see what I can do. In any case, you don't always get the packet in the exception (even in SMB > 1).

**Comment by asolino** [comment]
Mind issuing a PR?

**Comment by asolino** [comment]
bump

**Comment by asolino** [comment]
Fixed by @contactr2m in https://github.com/CoreSecurity/impacket/pull/317. Closing
