### ISSUE TITLE
mmcexec.py problem with DISPATCH_PROPERTYGET

### ISSUE THREAD

**Issue by artkond** [CoreSecurity/impacket#245]
Executing a command with mmcexec doesn't always work correctly. The target was a 2012 r2 server. Here's the trace:

$ python mmcexec.py  pentesto.loc/administrator@192.168.17.130 qwinsta
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] SMBv3.0 dialect used

Traceback (most recent call last):
  File "mmcexec.py", line 127, in run
    iDocument = IDispatch(self.getInterface(iMMC, resp['pVarResult']['_varUnion']['pdispVal']['abData']))
TypeError: string indices must be integers, not str
[-] string indices must be integers, not str_

The issue seems to be with the response to "property get" on "document" object:
 resp = iMMC.GetIDsOfNames(('Document',))
 dispParams = DISPPARAMS(None, False)
 dispParams['rgvarg'] = NULL
 dispParams['rgdispidNamedArgs'] = NULL
 dispParams['cArgs'] = 0
 dispParams['cNamedArgs'] = 0
 resp = iMMC.Invoke(resp[0], 0x409, DISPATCH_PROPERTYGET, dispParams, 0, [], [])**
iDocument = IDispatch(self.getInterface(iMMC, resp['pVarResult']['_varUnion']['pdispVal']['abData']))

**Comment by asolino** [comment]
hey @artkond thanks for the report.

That's interesting. I just tested it against a w2k12r2 and it is working fine on my side. Is there a possibility of getting a pcap capture of that connection? That might help identifying the issue.

thanks!

**Comment by asolino** [comment]
Hey mate.. just managed to repro it against a Windows 10. Can you `git pull` and recheck?

**Comment by artkond** [comment]
Pulled. Seems to work as intended now!

**Comment by asolino** [comment]
Awesome! Closing it. thanks for the report!
