### ISSUE TITLE
Using wmiexec.py imported in to another program

### ISSUE THREAD

**Issue by mgrune** [CoreSecurity/impacket#248]
Obviously I'm a total idiot but I am going in circles here.  It's not something which isn't working but rather me trying to learn how to do things in a more efficient manner in python.  I currently call the command line wmiexec.py from within a class of my own and it works beautifully.  Something like:

`command = "/tools/wmiexec.py {}:{}@{} {}".format(username, password, hostname, r"C:\\reboot.cmd")`
`rc = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`
`out, err = rc.communicate()`

It just seems obvious to me that this isn't the best way to use this class or any similar class if I'm calling it from within another python class.  But I'm totally incapable of getting it to work the way I would expect.  I tried to simply create a reboot.cmd on a windows 7 test machine and then import the wmiexec class in to ipython on my linux box.

`import wmiexec`
`execute = wmiexec.WMIEXEC(command=r"C:\\reboot.cmd", username="myUser", password="myPass")`
`execute.run("mymachine.some.thing.com")`

It does nothing, just sits there trying to execute.  I assume I just need to better format the inputs or add additional arguments when instantiating the object.  Any tips where I'm going wrong would be excellent.

**Comment by asolino** [comment]
hey @mgrune 

You were close.. there's one tiny little detail you need to add to your code:
```
execute = wmiexec.WMIEXEC(command=r"C:\\reboot.cmd", username="myUser", password="myPass", share='ADMIN$')
``` 

That last argument `share='ADMIN$'`  specifies where the program will get the output of the command you just executed. 
If you don't specify it, the results are unknown (never tested it that way).

let me know if this solves your issue.

**Comment by mgrune** [comment]
Thanks @asolino

It works perfectly as you suggested! I'm very happy with that, guess I'm lame but that made my day. 

Thanks so much 😀
