### ISSUE TITLE
not able to log command session with smbserver `helpwanted`

### ISSUE THREAD

**Issue by r0hi7** [CoreSecurity/impacket#249]
The SMB server is not able to log all the command in the session. I even looked in to impacket/smb.py/SMBCommand no such progress ? Any help

**Comment by asolino** [comment]
Hey @r0hi7. I don't understand your report. Please elaborate and give me some examples of the functionality you see not working.

Thanks!

**Comment by r0hi7** [comment]
@asolino . Suppose a user login using smbclient then i wanted to log his entire session. I dont know how to do it. The source code is to big for me to understand. Can you give an insight whether is it possible or not with this ?
It will be great help.

**Comment by nishitm** [comment]
Hi, I also wanted to do the same thing, logging remote client's IP and its commands on server. I think the server code make asynchronous calls that's why it's not easy to log this activity. Any help will be appreciated. Thanx.

**Comment by r0hi7** [comment]
@asolino is it possible to retrieve the command entered by the client ?
``` 
smb> ls
```
can we log this ls ?

**Comment by asolino** [comment]
Hey @r0hi7:
> @asolino is it possible to retrieve the command entered by the client ?
> smb> ls
> can we log this ls ?

No, you can't. Doing an `ls` involves connecting to a share, and depending on the SMB protocol being used, issuing an SMB Command (SMB2_QUERY_DIRECTORY for SMB > 1 or TRANS2_FIND_FIRST2 for SMBv1 although could be more).
I mean, every command involves many SMB requests. You can check that by sniffing the traffic while you connect to a target server.

What can be done (and it is *not* implemented) is to log every SMB command that is being executed, filtered by user. It is not a trivial thing to do tho (Pull requests welcomed :) )
