### ISSUE TITLE
smbrelayx: No module named secretsdump

### ISSUE THREAD

**Issue by ghelm** [CoreSecurity/impacket#253]
On Kali Rolling I did the following:

> git clone https://github.com/CoreSecurity/impacket
> python setup.py install
> cd  /usr/local/bin
> ./smbrelayx.py -h 172.16.60.41 -c "whoami"

> [*] Setting up HTTP Server
> [*] Servers started, waiting for connections
> [*] HTTPD: Received connection from 172.16.60.43, attacking target 172.16.60.41
> [*] Authenticating against 172.16.60.41 as XXX\bob SUCCEED
> [*] bob::XXX:3569de5a83a93628:bb276bd4adaa1f68bca42e0c873bea57:0101000000000000b4549f48658bd2016a4ebb557cc05ae00000000002000c0053004500430049004f004e000100080050004300300031000400180073006500630069006f006e002e006c006f00630061006c000300220050004300300031002e0073006500630069006f006e002e006c006f00630061006c000500180073006500630069006f006e002e006c006f00630061006c0007000800b4549f48658bd20106000400020000000800300030000000000000000100000000200000c0e678033fc4cac72c4a4b9b0d3ed8b7111e6a0f6056b8a516e960a9c96edf140a001000000000000000000000000000000000000900120048005400540050002f007700700061006400000000000000000000000000
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "./smbrelayx.py", line 109, in run
>     from impacket.examples.secretsdump import RemoteOperations, SAMHashes
> ImportError: No module named secretsdump

Python interactive shell:
> Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
> [GCC 6.3.0 20170118] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from impacket.examples.secretsdump import RemoteOperations, SAMHashes
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named secretsdump
> >>>

Any ideas, why it can't import the secretsdump module?

**Comment by asolino** [comment]
Hey @ghelm 

Looks like you still have an old impacket version installed that has priority over the one you installed. This has happened with Kali before. What version are you running?

Please check [this issue](https://github.com/CoreSecurity/impacket/issues/212) and let me know if it solves the problem.

**Comment by ghelm** [comment]
Thanks for your feedback!

The fix on Kali Rolling was the following:

cd /usr/lib/python2.7/dist-packages/
mv impacket impacket-bak

Before:
>>> from impacket import version
>>> version.__file__
'/usr/lib/python2.7/dist-packages/impacket/version.pyc'

After:
>>> from impacket import version
>>> print version.__file__
/usr/**local**/lib/python2.7/dist-packages/impacket/version.pyc

that did the trick.
