### ISSUE TITLE
smbrelayx: Encoding Issue

### ISSUE THREAD

**Issue by ghelm** [CoreSecurity/impacket#254]
I'm running smbrelayx against a german based windows 7:
>./smbrelayx.py -h 172.16.60.41 -c "whoami"

> [*] Servers started, waiting for connections
> [*] Setting up HTTP Server
> [*] HTTPD: Received connection from 172.16.60.43, attacking target 172.16.60.41
> [*] Authenticating against 172.16.60.41 as XXX\bob SUCCEED
> [*] bob::SECION:d34fcb3ac18d0de9:0805d32d0da9ae30beb14659dcca07a3:01010000000000009e99d52e838bd2016e3dec3cc99d257d0000000002000c0053004500430049004f004e000100080050004300300031000400180073006500630069006f006e002e006c006f00630061006c000300220050004300300031002e0073006500630069006f006e002e006c006f00630061006c000500180073006500630069006f006e002e006c006f00630061006c00070008009e99d52e838bd20106000400020000000800300030000000000000000100000000200000c0e678033fc4cac72c4a4b9b0d3ed8b7111e6a0f6056b8a516e960a9c96edf140a001000000000000000000000000000000000000900120048005400540050002f007700700061006400000000000000000000000000
> [*] Service RemoteRegistry is in stopped state
> [*] Starting service RemoteRegistry
> [*] Executed specified command on host: 172.16.60.41
> nt-autorit�t\system

The last line should actually read "nt-autorität\system" with a german a-umlaut.

**Comment by asolino** [comment]
Hey @ghelm 

Try replacing [this line](https://github.com/CoreSecurity/impacket/blob/master/examples/smbrelayx.py#L132) with:
```
print self.__answerTMP.decode('cp850')
```
and let me know if it works on your side.

Note this is not a final solution since this will work for your Windows Code Page but most probably won't work with other Windows versions. We should find a way to detect the target's code page as part of the attack (don't know if that's possible)

**Comment by ghelm** [comment]
You workaround works as intended. You could parse the output from the windows tool "chcp" to get the current codepage (tested on win7/8.1).

C:\Users\alice>chcp
Aktive Codepage: 850.

**Comment by asolino** [comment]
Thanks for checking @ghelm.

Yes.. I'd like to do something automatic, but first I'd like to understand whether there's an easy way for mapping between the codepage and the python encoding (see https://docs.python.org/2.4/lib/standard-encodings.html).

Until then, this will be done manually through the [-codec](https://github.com/CoreSecurity/impacket/commit/6c34701623172c64e61e920c59a79a73eeafd7b7) switch (I'll add it to `smbrelayx.py` soon).

Also, I'm wondering what the output of `chcp` is like for a Chinese version, for example..
