### ISSUE TITLE
ese.py - LV records

### ISSUE THREAD

**Issue by jetProp445** [CoreSecurity/impacket#255]
Hey CoreSecurity,

I am working on a university project around ESE databases and require support for LV records. Can you guys point me to information about how those records are structured? And how would one go about adding LV support to your code? Of course I would commit the code I wrote so you can add it if you want.

Regards,
Jack

**Comment by asolino** [comment]
Hey @jetProp445 

Sorry for the delay.. just in case.. best bet to get that information would be to check [libesedb](https://github.com/libyal/libesedb/) page. Joachim Metz is the guy to follow with regards to ESE DB inner workings. 

Hope this helps!
