### ISSUE TITLE
Secretsdump NTDS.dit - Duplicate rows

### ISSUE THREAD

**Issue by dirkjanm** [CoreSecurity/impacket#256]
I'm running secretsdump locally with a quite large NTDS.dit, and it has been running for almost 20 hours by now. What I notice is that there are a lot of duplicate rows, and there don't seem to be any new unique rows in the output anymore for the last couple of hours (`sort -u output.ntds | wc -l` is constant).
Any idea what might cause this or where I can look in the code to debug this?

**Comment by asolino** [comment]
hey @dirkjanm 
No idea what is happening there. Probably a slightly damaged dit file or a bug in the parser (ese.py). Running secretsdump.py with -debug might help but keep it mind it generates a lot of noise with an ESE database. Did you try parsing it with `esedbexport`?

The loop that reads the dir file records is [here](https://github.com/CoreSecurity/impacket/blob/master/impacket/examples/secretsdump.py#L1945). In order for the loop to stop `record` must be `NULL`.  So maybe there's an issue in [getNextRow()](https://github.com/CoreSecurity/impacket/blob/master/impacket/ese.py#L796). Those two places could be good for debugging.

hope this helps!

**Comment by dirkjanm** [comment]
I do see quite a few `[-] Error while calling getNextRow(), trying the next one`, which might be related to the problem. I'll run it with debug when I have the time to see if I can get some more info.
I haven't had the courage yet to run esedbexport, running it now but I expect it will take some time (days? :p).

Thanks for thinking along, I'll let you know when I have more info!

**Comment by dirkjanm** [comment]
I'm getting the following errors:
> [-] Error while calling getNextRow(), trying the next one
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/impacket/examples/secretsdump.py", line 1952, in dump
>     record = self.__ESEDB.getNextRow(self.__cursor)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 811, in getNextRow
>     return self.getNextRow(cursor)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 813, in getNextRow
>     return self.__tagToRecord(cursor, tag['EntryData'])
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 961, in __tagToRecord
>     record[column] = record[column].decode(stringDecoder)
>   File "/usr/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
>     return codecs.utf_16_le_decode(input, errors, True)
> UnicodeDecodeError: 'utf16' codec can't decode bytes in position 0-1: illegal encoding

And

> [-] Error while calling getNextRow(), trying the next one
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/impacket/examples/secretsdump.py", line 1952, in dump
>     record = self.__ESEDB.getNextRow(self.__cursor)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 811, in getNextRow
>     return self.getNextRow(cursor)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 813, in getNextRow
>     return self.__tagToRecord(cursor, tag['EntryData'])
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 961, in __tagToRecord
>     record[column] = record[column].decode(stringDecoder)
>   File "/usr/lib/python2.7/encodings/utf_16_le.py", line 16, in decode
>     return codecs.utf_16_le_decode(input, errors, True)
> UnicodeDecodeError: 'utf16' codec can't decode bytes in position 0-1: illegal UTF-16 surrogate

So I'm guessing it is the weird encoding in some fields that causes it to break?
esedbexport didn't have problems with the ntds.dit, so I think it isn't corrupted.

**Comment by dirkjanm** [comment]
And now also this one:

> [-] Error while calling getNextRow(), trying the next one
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/impacket/examples/secretsdump.py", line 1952, in dump
>     record = self.__ESEDB.getNextRow(self.__cursor)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 813, in getNextRow
>     return self.__tagToRecord(cursor, tag['EntryData'])
>   File "/usr/local/lib/python2.7/dist-packages/impacket/ese.py", line 961, in __tagToRecord
>     record[column] = record[column].decode(stringDecoder)
>   File "/usr/lib/python2.7/encodings/cp1252.py", line 15, in decode
>     return codecs.charmap_decode(input,errors,decoding_table)
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1: character maps to [undefined]
>

**Comment by 0x6d6178** [comment]
+1

Issue has impact on results. The loop is not breaking.

I did some debugging, this is how far I got:

1. Loop is not breaking so -> secretsdump.py, lines 1678 and 1680 are never evaluating to 'true'
2. In ese.py on line 805 -> page.record['NextPageNumber'] == 0 is never evaluating to 'true'

I tried figuring out where the NextPageNumber was set, but wasn't able to track it down.

Hope this can be resolved :)

**Comment by asolino** [comment]
Thanks for your data @0x6d6178 

> 2. In ese.py on line 805 -> page.record['NextPageNumber'] == 0 is never evaluating to 'true'

Can you print what page.record['NextPageNumber'] is? .. if the loop doesn't end most probably there's a moment when it starts showing the same number.

BTW.. any chance to share the DIT and system files? ;)

**Comment by herrspecks** [comment]
It seems that it loops through the history aswell.
After running for several hours, I now see several krbtgt hashes, where all but one are set to blank.
Could you please check on that?

**Comment by asolino** [comment]
No answer, closing

**Comment by ss23** [comment]
I've also run into this issue. Unfortunately I'm time constrained and can't debug it, but it's still happening on the latest version. I'm also dealing with a very large database.

**Comment by DPeltier** [comment]
Hi,
I still have the same issue. I just run a secretdump.py with debug mode, i will keep you updated
