### ISSUE TITLE
Not a issue: Mimic smb2 dir operation of windows.

### ISSUE THREAD

**Issue by contactr2m** [CoreSecurity/impacket#258]
Hrmm this is just need info kind of request  so not a defect or issue.

I am using [SMBConnection.listPath](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbconnection.py#L403) method. for doing normal dir operation.
There is already a comment about TODO in it.
["we're assuming it's a directory, we should check what the file type is"](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1415)

I will be modifying my code to get as close as actual windows calls for normal dir operation.
After checking pcap it seems windows first do open/close then open /query directory / close
information level = FILE_ID_BOTH_DIRECTORY_INFO

First create is with below options to just know what type of file it is.
desiredAccess=FILE_READ_ATTRIBUTES,
shareMode=FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, 
fileAttributes=0,
creationDisposition=FILE_OPEN,
creationOptions=FILE_OPEN_REPARSE_POINT

Second we get normal create response with file attribute as directory.
In impacket case we return file handle and store relevant information in FileOpen table.
According to [3.3.5.9 Receiving an SMB2 CREATE Request](https://msdn.microsoft.com/en-us/library/cc246776.aspx) this seem to be correct that we are not storing file attributes because dialect is smb2 only and =>3.0

So how do we get to know what kind of file it is ? 
In pcap it shows separate request for first create and close so not a chained request.

Normally windows list contents of given path if its a directory else list it as file. 
I think i can implement this but need some information on above things. 

Thank you.

**Comment by asolino** [comment]
Hey @contactr2m 

Not sure I fully understand what you wanna do but, 

> So how do we get to know what kind of file it is ?
In pcap it shows separate request for first create and close so not a chained request.

We call [queryDirectory](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1422) asking for a `FILE_FULL_DIRECTORY_INFORMATION` record for all the files/dirs inside the opened handle. Inside that [record](https://msdn.microsoft.com/en-us/library/cc232071.aspx) you have:
```
FileAttributes (4 bytes):  A 32-bit unsigned integer that contains the file attributes. Valid attributes are as specified in section 2.6. 
```
If you go to section [2.6](https://msdn.microsoft.com/en-us/library/cc232110.aspx) you have: 
```
FILE_ATTRIBUTE_DIRECTORY (0x10): This item is a directory
```

That's what the [SharedFile.isDirectory()](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb.py#L615) method does. That method is used by [smbclient.py](https://github.com/CoreSecurity/impacket/blob/master/examples/smbclient.py#L378) when printing the result of listPath:
```
# ls
drw-rw-rw-          0  Mon Mar 22 09:22:16 2010 $Recycle.Bin
-rw-rw-rw-        912  Thu Jun 25 21:49:53 2015 ASEC.log
-rw-rw-rw-          0  Tue Feb 21 20:21:55 2017 btobto
drw-rw-rw-          0  Mon Mar 22 09:22:27 2010 Documents and Settings
drw-rw-rw-          0  Tue Nov 30 14:37:07 2010 inetpub
-rw-rw-rw- 1073741824  Fri Mar 17 10:35:59 2017 pagefile.sys
drw-rw-rw-          0  Mon Mar 22 09:22:16 2010 PerfLogs
drw-rw-rw-          0  Thu Feb 23 19:34:57 2017 Program Files
drw-rw-rw-          0  Fri Jul 24 13:59:37 2015 Program Files (x86)
drw-rw-rw-          0  Mon Apr 25 10:26:50 2016 ProgramData
drw-rw-rw-          0  Mon Mar 22 08:25:40 2010 Recovery
-rw-rw-rw-        511  Fri Mar 17 10:37:01 2017 server_corba_server.log
drw-rw-rw-          0  Mon Feb 20 09:42:16 2017 System Volume Information
drw-rw-rw-          0  Sun Mar 19 15:53:15 2017 tmp
drw-rw-rw-          0  Thu Jul  9 17:58:28 2015 Users
-rw-rw-rw-      52730  Fri Mar 17 10:37:00 2017 vbr_server.log
drw-rw-rw-          0  Mon Mar  6 15:07:01 2017 Windows
```

hope this helps!, If not, please clarify.

**Comment by contactr2m** [comment]
Thanks for the reply @asolino 
Looks like i found the solution.

In [listPath](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1404) method we [assume](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1416) that current path is a directory without knowing it is actually a directory or not.
it seems that GetFileAttributes function is called before actually doing querydirectory in windows (smb2) 
And GetFileAttributes is nothing but 
file open
check attribute
file close.

Closing it.
