### ISSUE TITLE
Error in oaut.py#L267

### ISSUE THREAD

**Issue by idiMAN** [CoreSecurity/impacket#260]
When I use national symbols, I get an error :

> [-] 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)

 in https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/dcom/oaut.py#L267

Please replace 
`encoded = letter.encode('utf-16le')`
with
`import sys`
...
`encoded = letter.decode(sys.getfilesystemencoding()).encode('utf-16le')`

**Comment by asolino** [comment]
Hey @idiMAN 

Thanks for the report. What example are you using to repro this issue? I want to be able to repro and test the fix.
Thanks!

**Comment by idiMAN** [comment]
Hey @asolino 

For example:
`mmcexec.py -nooutput domain/usernamepassword@address cmd /S /C "echo 例如，在一些中國或其他語言 ^> c:\test.txt"`

Thanks!

**Comment by asolino** [comment]
Thanks for the update @idiMAN.

Can you test the same with `wmiexec.py`? Does it work with it?

**Comment by idiMAN** [comment]
Hey @asolino

Yes, you fix is work, but error still happen in **mmcexec.py**

```
C:\impacket-master\examples>mmcexec.py domain/username:password@address
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] SMBv2.1 dialect used
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>mkdir 測試

C:\>cd 測試
[-] 'ascii' codec can't decode byte 0x92 in position 0: ordinal not in range(128)
```

and in **wmiexec.py**

```
C:\impacket-master\examples>wmiexec.py domain/username:password@address
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] SMBv2.1 dialect used
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>cd 測試
[-] 'ascii' codec can't decode byte 0x92 in position 3: ordinal not in range(128)
```
and may be in the other places...

**Comment by asolino** [comment]
Thanks again for your reports @idiMAN. However, I cannot reproduce that behavior after the patch.
I'm doing my tests from macOS against a win2k8.
Can you please uncomment [these two lines](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L96) and [these two lines](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L401) in `wmiexec.py` and run it again? I want to understand where it is breaking.

thanks!

**Comment by idiMAN** [comment]
Hey @asolino 

My error report:
```
C:\impacket-master\examples>wmiexec.py domain/username:password@address
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] SMBv2.1 dialect used
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>cd 測試
Traceback (most recent call last):
  File "C:\impacket-master\examples\wmiexec.py", line 94, in run
    self.shell.cmdloop()
  File "C:\Python27\lib\cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python27\lib\cmd.py", line 221, in onecmd
    return func(arg)
  File "C:\impacket-master\examples\wmiexec.py", line 202, in do_cd
    self.__pwd = self.__outputBuffer.strip('\r\n').decode(CODEC)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 3: ordinal not in range(128)
[-] 'ascii' codec can't decode byte 0x92 in position 3: ordinal not in range(128)
```
Thanks!

**Comment by idiMAN** [comment]
Hey @asolino 

I fix my first error:
In https://github.com/CoreSecurity/impacket/blob/master/examples/mmcexec.py#L326
replace
`arg1['_varUnion']['bstrVal']['asData'] = self.__pwd`
with
`arg1['_varUnion']['bstrVal']['asData'] = self.__pwd.decode(sys.stdin.encoding)`

But after several tests, I found another error that arises from the fact that in my operating system the encoding of the parameters passed in the command line is different from the encoding of the commands entered from the console. I decided it this way:
In https://github.com/CoreSecurity/impacket/blob/master/examples/mmcexec.py#L54
replace
`self.__command = command`
with
`self.__command = command.decode(sys.getfilesystemencoding()).encode(sys.stdin.encoding)`

I also found the solution to the second error:
In https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L39
replace
`CODEC = sys.getdefaultencoding()`
with
`CODEC = sys.stdout.encoding`

Thanks!

**Comment by asolino** [comment]
Hey @idiMAN, can you recheck `wmiexec.py` and let me know if everything works as expected? Than I can work on `mmcexec.py` Thanks!

**Comment by idiMAN** [comment]
Hey @asolino

**Comment by asolino** [comment]
`mmcexec.py` doesn't work anymore.. please test `dcomexec.py` and re-open this issue if still there's an error.
