### ISSUE TITLE
Module readline forgotten in setup.py

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#261]
Hello @asolino,

The `mimikatz.py` example uses the `readline` module but that module isn't mentioned in the `setup.py` file :)

Cheers.

**Comment by asolino** [comment]
Hey @maaaaz !

Isn't `readline` coming installed by default with Python? If not I'll add it for sure.

**Comment by maaaaz** [comment]
I can't tell for Linux but with a Windows installation of the latest 2.7 it was missing.
