### ISSUE TITLE
SMB Server: append to file support

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#262]
Hey man!
This is a question/issue, I've noticed that trying to append to a file hosted on Impacket's SMB server simply overwrites the file rather than actually appending to it.

Is this a currently known limitation?

Thanks!

**Comment by asolino** [comment]
Hey mate!

That should be a bug. Is it when doing SMB1? SMB2? In theory it should work. If you can try to dig into `smbserver.py` that'd be great. Especially when it is selecting how to open the file based on the client's options (look for `open()` calls )

cheers!

**Comment by byt3bl33d3r** [comment]
Will do! I'll see what I can dig up this evening. Cheers

**Comment by asolino** [comment]
hey @byt3bl33d3r!
where you able to verify this?

**Comment by asolino** [comment]
bump!

**Comment by asolino** [comment]
No answer... closing
