### ISSUE TITLE
Request to have GetADUsers.py actively output results

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#265]
Unfortunately storing large datasets fails due to RAM contraints and no results are given 👎

**Comment by ropnop** [comment]
Hey mubix, I had this problem too. I believe it's possible with paging results and outputting 1000 at at a time, but I haven't looked how to implement it yet with Impacket's ldap library.

I wrote a tool that does ldap enumeration [here](https://github.com/ropnop/windapsearch) that might be helpful. I got the paging idea from another ldap enumeration tool here that does a nice job handling large domains:

https://github.com/CroweCybersecurity/ad-ldap-enum

**Comment by asolino** [comment]
This should be solved in https://github.com/CoreSecurity/impacket/commit/0d39e84d46e454ba5d6ed4c1641297a9274d3848. Reopen if not working
