### ISSUE TITLE
mssqlclient.py/ tds.py: 'SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match'

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#269]
Hey man,

I noticed the following error while trying to authenticate to SQL Server Express 2014 installed on Windows 7:
```
mssqlclient.py -debug -windows-auth LAB/yomama@192.168.10.25              
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[*] Encryption required, switching to TLS
[-] [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]
```
Same error happens when not using windows auth.

The problem seems to be the cipher list being set in tds.py [here](https://github.com/CoreSecurity/impacket/blob/master/impacket/tds.py#L862)

The weird thing about this is that it was working fine just a couple days ago and if I'm reading the MS-TDS docs correctly the RC4 cipher is still clearly supported.

Let me know if you need any more info and thanks!

**Comment by milo2012** [comment]
The issue seems to be related to pyopenssl 
https://github.com/pyca/pyopenssl/issues/436

pyOpenssl version 17.0.0 should include the patch.  I will test it out in a couple of hours. https://github.com/pyca/pyopenssl/archive/17.0.0.zip

Just thought of sharing this.

**Comment by asolino** [comment]
Hey folks.. thanks very much for researching this.. I'm swamped these days with little time to go over this issue.

you rock!

**Comment by milo2012** [comment]
Just a note, @byt3bl33d3r could be using OSX and RC4 was removed from OS X 10.11 El Capitan.
Lines +635 and +862 uses RC4.

ctx.set_cipher_list('RC4')

Below are a list of available ciphers when I run get_cipher_list()
conn.get_cipher_list()
['ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'DHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305', 'ECDHE-RSA-CHACHA20-POLY1305', 'DHE-RSA-CHACHA20-POLY1305', 'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'DHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-SHA384', 'ECDHE-RSA-AES256-SHA384', 'DHE-RSA-AES256-SHA256', 'ECDHE-ECDSA-AES128-SHA256', 'ECDHE-RSA-AES128-SHA256', 'DHE-RSA-AES128-SHA256', 'ECDHE-ECDSA-AES256-SHA', 'ECDHE-RSA-AES256-SHA', 'DHE-RSA-AES256-SHA', 'ECDHE-ECDSA-AES128-SHA', 'ECDHE-RSA-AES128-SHA', 'DHE-RSA-AES128-SHA', 'RSA-PSK-AES256-GCM-SHA384', 'DHE-PSK-AES256-GCM-SHA384', 'RSA-PSK-CHACHA20-POLY1305', 'DHE-PSK-CHACHA20-POLY1305', 'ECDHE-PSK-CHACHA20-POLY1305', 'AES256-GCM-SHA384', 'PSK-AES256-GCM-SHA384', 'PSK-CHACHA20-POLY1305', 'RSA-PSK-AES128-GCM-SHA256', 'DHE-PSK-AES128-GCM-SHA256', 'AES128-GCM-SHA256', 'PSK-AES128-GCM-SHA256', 'AES256-SHA256', 'AES128-SHA256', 'ECDHE-PSK-AES256-CBC-SHA384', 'ECDHE-PSK-AES256-CBC-SHA', 'SRP-RSA-AES-256-CBC-SHA', 'SRP-AES-256-CBC-SHA', 'RSA-PSK-AES256-CBC-SHA384', 'DHE-PSK-AES256-CBC-SHA384', 'RSA-PSK-AES256-CBC-SHA', 'DHE-PSK-AES256-CBC-SHA', 'AES256-SHA', 'PSK-AES256-CBC-SHA384', 'PSK-AES256-CBC-SHA', 'ECDHE-PSK-AES128-CBC-SHA256', 'ECDHE-PSK-AES128-CBC-SHA', 'SRP-RSA-AES-128-CBC-SHA', 'SRP-AES-128-CBC-SHA', 'RSA-PSK-AES128-CBC-SHA256', 'DHE-PSK-AES128-CBC-SHA256', 'RSA-PSK-AES128-CBC-SHA', 'DHE-PSK-AES128-CBC-SHA', 'AES128-SHA', 'PSK-AES128-CBC-SHA256', 'PSK-AES128-CBC-SHA']

**Comment by byt3bl33d3r** [comment]
@milo2012 thanks for the help! I'm actually using Arch Linux, I'll see if I can dig up any more info

**Comment by asolino** [comment]
Guys.. did you try removing that line?.. I remember I explicitly added that due to an issue in the SSL negotiation but that might be gone now. Just a thought.

**Comment by milo2012** [comment]
I received the below message after commenting out that line. I tried on MSSQL 2008 R2.
#ctx.set_cipher_list('RC4')

[*] Encryption required, switching to TLS
[-] [Errno 54] Connection reset by peer

**Comment by asolino** [comment]
Hey folks:

Cannot reproduce under macOS 10.12.5:
```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: None, New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(2012R2DOMAIN-DC\BETOSQL): Line 1: Changed database context to 'master'.
[*] INFO(2012R2DOMAIN-DC\BETOSQL): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server (120 7208) 
[!] Press help for extra shell commands
SQL> 

```
This is a SQL Server Express 2014 installed in a Windows 2012 R2. I'll try from Kali

**Comment by asolino** [comment]
I can reproduce it in Kali tho:
```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[*] Encryption required, switching to TLS
[-] [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]
```
I [just](https://github.com/CoreSecurity/impacket/commit/754ee112e525ec1842115b9001fa5535e31e403d) added `AES256` as a possible cipher. Please `git pull` and retest. Close this issue if working.

**Comment by byt3bl33d3r** [comment]
That worked! Cheers man.
