### ISSUE TITLE
Python 3: Syntax Error in `smb` module

### ISSUE THREAD

**Issue by teward** [CoreSecurity/impacket#270]
In Python 3, and the version on PyPI (0.9.15) there is a syntax error with the `impacket` during import:

```
/usr/bin/python3.5 /home/ncfta_it/.PyCharm2017.1/config/scratches/scratch.py
Traceback (most recent call last):
  File "/home/ncfta_it/.PyCharm2017.1/config/scratches/scratch.py", line 1, in <module>
    from impacket import smb
  File "/usr/local/lib/python3.5/dist-packages/impacket/smb.py", line 632
    y = t & 0xffffffffL
                      ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

Both on Windows and Linux, this happens.  This makes the `smb` submodule unusable.  (Note that while this run was done within PyCharm, direct command line runs trigger the same syntax error)

**Comment by asolino** [comment]
Hey @teward 

Impacket currently does not support Python 3. There's an [open issue](https://github.com/CoreSecurity/impacket/issues/61) for it already.

Closing this one as duplicate.
