### ISSUE TITLE
Raw LSASecrets secrets with null terminator in their name, coming from the offline registry parsing

### ISSUE THREAD

**Issue by franferrax** [CoreSecurity/impacket#271]
While working with `examples/secretsdump.py` and dumping LSASecrets from the security file (`HKLM\SECURITY` registry key export hive) we've found a case where this hive seems to not being well parsed.

The following snippet generates an output array containing some key names ending with `\x00`.
```python
from impacket import winregistry
r = winregistry.Registry('HKLM_SECURITY_reg_hive')
r.enumKey(r.findKey('\\Policy\\Secrets'))
```
While we get some key names as `'NL$KM'`, others looks like `'SAC\x00'` or `'SCM:{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}\x00'`.

I'll provide the `HKLM_SECURITY_reg_hive` file in private if necessary.

**Comment by asolino** [comment]
Hey @franferrax 

Yep.. please send me the hive since I cannot reproduce it with my target box.

**Comment by franferrax** [comment]
NOTE: I've sent the hive.

If I import and browse  the hive with `regedit` running as System, it shows the keys without null terminators, but they're inaccessible. It seems that this keys have an explicit null terminator in their names, in fact we can enumerate some of them with Impacket using the `\x00` as part of the registry path. Googling for `null registry keys` I've been pointed to some forums saying that this is presumably to hide them from `regedit`. There is also a `RegDelNull` tool in the Sysinternals Suite for deleting this kind of keys.

So `impacket.winregistry` is handling them well, maybe we want to filter this results in `impacket.examples.secretsdump` if their data doesn't contain valid LSA raw secrets at all.

**Comment by asolino** [comment]
Het @franferrax 

> So impacket.winregistry is handling them well, maybe we want to filter this results in impacket.examples.secretsdump if their data doesn't contain valid LSA raw secrets at all.

Good to know. With regards to filtering valid LSA secrets, the problem is that I don't know what LSA Secrets are valid ;). Windows users can set LSA Secrets at their will.

If you don't see anything else to be done with this issue, please close it.
