### ISSUE TITLE
Can't find a valid stringBinding to connect

### ISSUE THREAD

**Issue by goodking-bq** [CoreSecurity/impacket#272]
When I use WMIEXEC to connect a windows(just have an ip like 10.25.33.11) address like 61.55.33.99(External address)
i get error like `Can't find a valid stringBinding to connect`,
i find the code where raise error, but i don't kown how to correct
```
for strBinding in stringBindings:
                    # Here, depending on the get_target() value several things can happen
                    # 1) it's an IPv4 address
                    # 2) it's an IPv6 address
                    # 3) it's a NetBios Name
                    # we should handle all this cases accordingly
                    # Does this match exactly what get_target() returns?
                    LOG.debug('StringBinding: %s' % strBinding['aNetworkAddr'])
                    if strBinding['wTowerId'] == 7:
                        # If there's port information, let's strip it for now.
                        if strBinding['aNetworkAddr'].find('[') >= 0:
                            binding, _, bindingPort = strBinding['aNetworkAddr'].partition('[')
                            bindingPort = '[' + bindingPort
                        else:
                            binding = strBinding['aNetworkAddr']
                            bindingPort = ''

                        if binding.upper().find(self.get_target().upper()) >= 0:
                            stringBinding = 'ncacn_ip_tcp:' + strBinding['aNetworkAddr'][:-1]
                            break
                        # If get_target() is a FQDN, does it match the hostname?
                        elif isTargetFDQN and binding.upper().find(self.get_target().upper().partition('.')[0]) >= 0:
                            # Here we replace the aNetworkAddr with self.get_target()
                            # This is to help resolving the target system name.
                            # self.get_target() has been resolved already otherwise we wouldn't be here whereas
                            # aNetworkAddr is usually the NetBIOS name and unless you have your DNS resolver
                            # with the right suffixes it will probably not resolve right.
                            stringBinding = 'ncacn_ip_tcp:%s%s' % (self.get_target(), bindingPort)
                            break

                LOG.debug('StringBinding chosen: %s' % stringBinding)
                if stringBinding is None:
                    # Something wen't wrong, let's just report it
                    raise Exception('Can\'t find a valid stringBinding to connect')
```

**Comment by asolino** [comment]
Please run the script with -debug and paste the stringbinding output

**Comment by goodking-bq** [comment]
[+] Target system is 104.75.129.142 and isFDQN is False
[+] StringBinding: \\\\WINDOWS2012R2[\\PIPE\\atsvc]
[+] StringBinding: Windows2012R2[49154]
[+] StringBinding: 10.13.76.162[49154]
[+] StringBinding: \\\\WINDOWS2012R2[\\PIPE\\srvsvc]
[+] StringBinding: \\\\WINDOWS2012R2[\\pipe\\SessEnvPublicRpc]
[+] StringBinding chosen: None
[-] Can't find a valid stringBinding to connect,use default!

here is my output and thanks

**Comment by asolino** [comment]
Hey @goodking-bq 
As you can see there, there's an issue at the target that has to do with its configuration. A few questions:

1. Are you behind a NAT device?
2. Did you try targeting `10.13.76.162` instead of `104.75.129.142`?
3. What is the address of `Windows2012R2`

**Comment by goodking-bq** [comment]
1. Yes, this server is a cloud server.
2. I connect use the  public ip(104.75.129.142), but the server just bind a private ip(10.13.76.162) i can't connect.
3. I have no idea what is Windows2012R2, the name of server?

and thanks!!

**Comment by asolino** [comment]
Hey @goodking-bq 

I'm afraid DCOM (the technology used by WMI) will not work with your configuration. Check this post from Microsoft:
https://support.microsoft.com/en-us/help/248809/prb-dcom-does-not-work-over-network-address-translation-based-firewall

I'm wondering what would happen if you change the logic of the stringBinding selection (the code you pasted in this ticket) to just ignore whatever IP is in there and connect to the port specified by the server (in your example `10.13.76.162[49154]` that should end up being `104.75.129.142[49154]`). Maybe that would work but it would be a hack to the DCOM protocol. There's no way I can put that into the library but maybe you can hack your version to work for your particular set up.

If not, I would use another remote execution alternative that doesn't rely on DCOM, for example, [psexec.py](https://github.com/CoreSecurity/impacket/blob/master/examples/psexec.py)

hope this helps

**Comment by goodking-bq** [comment]
Thank you very much. 
I will try psexec.py .

**Comment by asolino** [comment]
Good to know it worked @goodking-bq, thanks for reporting it. Closing now.

**Comment by mubix** [comment]
I know this isn't to spec but this worked for me as well. I think it would be pretty useful to people

**Comment by VakarisZ** [comment]
Worked like a charm to me also

**Comment by HuskyHacks** [comment]
Wanted to format the code snippet above to make it easier for people to paste into Impacket and fix this:

- `husky@ubuntu:~/Desktop/impacket$ nano impacket/dcerpc/v5/dcomrt.py`
- Add the following:
```python
# ...[snip]...

LOG.debug('StringBinding chosen: %s' % stringBinding)
if stringBinding is None:
    # Something wen't wrong, let's just report it
    # raise Exception('Can\'t find a valid stringBinding to connect')
    stringBinding = 'ncacn_ip_tcp:%s%s' % (self.get_target(), bindingPort)
    LOG.info('Can\'t find a valid stringBinding to connect,use default!')
    
dcomInterface = transport.DCERPCTransportFactory(stringBinding)

# ...[snip]...
```
- Save
- Rebuild Impacket: `husky@ubuntu:~/Desktop/impacket$ sudo python3 setup.py install`
- That should do it!

![image](https://user-images.githubusercontent.com/57866415/200885555-81c59450-34e8-445f-b424-5b22a02d76e9.png)
