### ISSUE TITLE
WMI: incorrect result for non-english values

### ISSUE THREAD

**Issue by t33m** [CoreSecurity/impacket#277]
Hi,

if we are define non-english value in Windows Group Policy parameter (for example
`Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Accounts: Rename guest account` we are set `Гость`) we've got incorrect response:
```sh
$ python wmiquery.py domain/username@hostname -namespace //./root/rsop/computer
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

Password:
[!] Press help for extra shell commands
WQL> SELECT Setting FROM RSOP_SecuritySettingString WHERE KeyName = 'NewGuestName' AND precedence = 1
| Setting |
| >ABL |
WQL>
```

We are tested on Windows Server 2008 R2.

Please check encoding for returned values.

Thank you!

**Comment by t33m** [comment]
@asolino , hi! 

Any help?

**Comment by kurzanovvv** [comment]
Also , I've found it returns an utf-16 result for non-english values. This can help.

**Comment by asolino** [comment]
Hey @t33m  and @kurzanovvv ...

And the funny thing is that:
```
>>> str = '\x13\x04>\x04A\x04B\x04L\x04'
>>> print str
>ABL
>>> print str.decode('utf-16le')
Гость
>>> 
```
But I still don't know when I should decode the string and when I should not. There's gotta be something inside the object but they seem all equal.

**Comment by kurzanovvv** [comment]
So , and me too :)
I've not saw an attribute which can tell me in which coding is used .
I've tried use chardet.detect function  , but didn't get a good result for a short strings

**Comment by asolino** [comment]
And this just doesn't help. Using PowerShell:
```
PS C:\Users\Administrator> $query
SELECT Setting FROM RSOP_SecuritySettingString WHERE KeyName = 'NewGuestName' AND precedence = 1
PS C:\Users\Administrator> Get-WmiObject -namespace "root\RSOP\Computer"  -Query $query


__GENUS          : 2
__CLASS          : RSOP_SecuritySettingString
__SUPERCLASS     :
__DYNASTY        :
__RELPATH        :
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
Setting          : ?????
```

**Comment by asolino** [comment]
Hey folks, thanks to @Gifts looks like the problem is solved.. please re-check your configuration and close the issue if solved.

**Comment by kurzanovvv** [comment]
Awesome ! It works! Thank you a lot !

**Comment by t33m** [comment]
@asolino, seems like it's works! Thanks!
