### ISSUE TITLE
secretsdump.py - Error in Crypto package

### ISSUE THREAD

**Issue by OzAven** [CoreSecurity/impacket#283]
Hi,
I have tried downloading and running the "secretsdump,py" script.
*Installed "Impacket" via the setup file.
*Installed and upgraded both PyCrypto and Crypto via pip.

Receiving an error when trying to run "secretsdump.py" - "ImportError: No module named Crypto.hash"
(File "C:\python27\lib\site-packages\impacket\krb5\gssapi.py", line 17)

**Comment by asolino** [comment]
hey @OzAven 

You should verify if you have PyCrypto correctly installed. In my setup:
```
>>> import Crypto
>>> Crypto.__version__
'2.6.1'
>>> from Crypto.Hash import MD5
>>> 
```
On Windows I used easy_install in order to install pycrypto, not pip.
