### ISSUE TITLE
SecretsDump doesn't honor dc-ip in Kerberos auth

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#285]
```
 secretsdump.py -k -aesKey (THEAESKEYHERE) -just-dc -dc-ip 192.168.80.10 sittingduck.info/uberuser@dc1.sittingduck.info
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[-] RemoteOperations failed: [Errno Connection error (dc1.sittingduck.info:445)] [Errno 61] Connection refused
[*] Cleaning up...
```

Externally SittingDuck.info resolves to 127.0.0.1, that's the only reason I noticed this. I tested this through a meterpreter session and got the same result :(

**Comment by mubix** [comment]
:( Now I'm getting:
```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[-] RemoteOperations failed: unpack requires a string argument of length 4
[*] Cleaning up...

```

**Comment by mubix** [comment]
This is due to a failure to lookup some DNS queries for Kerberos :/

**Comment by asolino** [comment]
Hey @mubix 

I can't repro this. The `-dc-ip` option applies to the domain name, from the help:
```
  -dc-ip ip address     IP Address of the domain controller. If ommited it use
                        the domain part (FQDN) specified in the target
                        parameter
```
So in your first example, whatever address you put as `-dc-ip` will apply to  `sittingduck.info` address.
In fact, the error is referring to the target specified:
```
[Errno Connection error (dc1.sittingduck.info:445)] [Errno 61] Connection refused
```
Did you test adding `dc1.sittingduck.info` to your host file?

Maybe we should add a `-target-ip` switch to address the target address as well. I'm not sure how easy is that but I guess it could be done.

**Comment by mubix** [comment]
The `argument of length 4` stuff was when I was finally resolving dc1.sttingduck.info but sttingduck.info was being resolved to another IP (external).

**Comment by mubix** [comment]
I wonder if making `-just-dc` be a trigger where it does everything against `-dc-ip` since you are most likely hitting a DC in that case.. But having a `-target-ip`  might be a better all-round solution

**Comment by asolino** [comment]
Yeah, also to maintain compatibility with other scripts (`psexec.py/smbclient.py/etc`). 
I just added that functionality plus a few tiny things.
Please `git pull` and reinstall impacket (important) and run it again (now specifying `-target-ip` for `dc1.sttingduck.info`) and also with `-debug` that should now also print the tracebacks when there are exceptions.

**Comment by mubix** [comment]
Works perfectly now! Thanks!!
