### ISSUE TITLE
ImportError: No module named smbclient

### ISSUE THREAD

**Issue by Dk0n9** [CoreSecurity/impacket#287]
impacket( 0.9.15 and 0.9.16.dev0 )

python ntlmrelayx.py
Traceback (most recent call last):
  File "ntlmrelayx.py", line 56, in <module>
    from smbclient import MiniImpacketShell
ImportError: No module named smbclient

tested on Windows + Ubuntu;

**Comment by asolino** [comment]
You need [smbclient.py](https://github.com/CoreSecurity/impacket/blob/master/examples/smbclient.py) example installed in the same directory where ntlmrelayx.py is. If you do a ```python setup.py install```  and then just run `ntlmrelayx.py` it should work.

If not, reopen the issue.
