### ISSUE TITLE
Do you have a release that works with python 3.6?

### ISSUE THREAD

**Issue by zhenxue69** [CoreSecurity/impacket#289]
My project env only has python 3.6. Even after running 2to3 for your source tree, the code still does not work because python3 did not support mixed usage of byte and string. Please help.

**Comment by asolino** [comment]
Hey @zhenxue69 

I'm sorry to say impacket does not support Python3 and porting it is nowhere near as straightforward as just running 2to3. Many parts of the library rely on strings and that was a big change in Python 3. An overwall re-architecture, besides the coding itself, would be mostly needed.

Successfully porting it will require some effort that we just don't have at the moment.
