### ISSUE TITLE
hSamrGetAliasMembership not fetching members?

### ISSUE THREAD

**Issue by ropnop** [CoreSecurity/impacket#295]
Hey man -

Probably missing something, but I'm playing around trying to recreate certain `rpcclient` functionality with Impacket and am having trouble getting hSamrGetAliasMembership to return members.

For reference, here is the command in `rpcclient` working:

```
rpcclient $> queryaliasmem builtin 0x220
	sid:[S-1-5-21-2318470451-3930354337-2673945738-500]
	sid:[S-1-5-21-2318470451-3930354337-2673945738-1001]
	sid:[S-1-5-21-2318470451-3930354337-2673945738-1002]
	sid:[S-1-5-21-1301449028-38422301-1166279081-512]
	sid:[S-1-5-21-1301449028-38422301-1166279081-1116]
	sid:[S-1-5-21-1301449028-38422301-1166279081-1110]
```
This is outputting the SIDS of the Local Administrators group (rid: 544)

I'm trying to get it with Impacket. Here's a snipped of what I have:

```python
resp = samr.hSamrLookupDomainInSamServer(dce, serverHandle, 'Builtin')
resp = samr.hSamrOpenDomain(dce, serverHandle = serverHandle, domainId = resp['DomainId'])
domainHandle = resp['DomainHandle']
adminSidResp = samr.hSamrRidToSid(dce, domainHandle, 544)
adminSid = adminSidResp['Sid']
si = samr.PSAMPR_SID_INFORMATION()
si['SidPointer'] = adminSid
sidsArray = samr.SAMPR_PSID_ARRAY()
sidsArray['Sids'].append(si)
resp = samr.hSamrGetAliasMembership(dce, domainHandle, sidsArray)
```
I think the SidArray looks correct:
```
In [3]: sidsArray.dump()
SAMPR_PSID_ARRAY
Count:                           1
Sids:
    [

        SidPointer:
            Revision:                        1
            SubAuthorityCount:               2
            IdentifierAuthority:             '\x00\x00\x00\x00\x00\x05'
            SubAuthority:
                [
                     32,
                     544,
                ] ,
    ]
```
but the final resp from hSamrGetAliasMembership is blank:
```
In [5]: resp.dump()
SamrGetAliasMembershipResponse
Membership:
    Count:                           0
    Element:
        [
        ]
ErrorCode:                       0
```

Am I missing something? I thought it should return a SID ARRAY of the users who belong to that group?

Thanks!

**Comment by asolino** [comment]
Hey @ropnop..

Didn't get the `rpcclient`'s command line.

**Comment by ropnop** [comment]
Sorry..fat fingered a few times and accidentally submitted before I was done. Edited comment should be all good now

**Comment by asolino** [comment]
Thanks.. 
BTW.. quickly looking at the Wireshark for that `rpcclient`'s command I see it's calling not calling SAMR's SamrGetAliasMembership  (opnum 16) but SAMR's [SamrGetMembersInAlias](https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/samr.py#L1940) (opnum 33). There's a helper for that class called [hSamrGetMembersInAlias](https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/samr.py#L2691).

There's also a [testcase](https://github.com/CoreSecurity/impacket/blob/master/impacket/testcases/SMB_RPC/test_samr.py#L2009) for that call that could help you. Haven't looked the rest of your example but this could be a good start.

**Comment by ropnop** [comment]
Thank you! I was following the test cases (super helpful!) but was looking at the wrong Samr call. I should've thought to use Wireshark :/

Works perfect now :)

```

**Comment by asolino** [comment]
Yep.. Wireshark helps a lot, and Network Monitor/Message Analyzer as well (even better but way slower). 

Good to know it's working, closing issue
