### ISSUE TITLE
WMI: Invalid result for non-English list type values

### ISSUE THREAD

**Issue by chaschinsm** [CoreSecurity/impacket#304]
Hi,

If I define value in the Windows Group Policy setting (for example
_Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\User Rights Assignment\Load and unload device drivers_) then for operating systems in Russian, when I try to get the value, I get:

$ python wmiquery.py domain/username@hostname -namespace //./root/rsop/computer
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[!] Press help for extra shell commands
WQL> SELECT AccountList FROM RSOP_UserPrivilegeRight WHERE UserRight = 'seloaddriverprivilege' AND precedence = 1
[-] 'ascii' codec can't encode characters in position 0-13: ordinal not in range(128)
WQL> 
`

I've tested on Windows 10 x64 Rus

Check the output of list-type variables for non-English values

Thank you!

**Comment by asolino** [comment]
Hey @chaschinsm 

Before jumping into this, I want to be sure you have a fully updated impacket-0.9.16-dev since there was a similar issue in the past that was solved. You can check more details in this issue https://github.com/CoreSecurity/impacket/issues/277

**Comment by chaschinsm** [comment]
@asolino 

I already saw this issue and I downloaded and installed impacket-0.9.16-dev yesterday.
Issue [#277](https://github.com/CoreSecurity/impacket/issues/277) solved the problem for the value of type string as a result, but in this case we get a list-type value that is not output

**Comment by asolino** [comment]
thanks for checking @chaschinsm. I'll dig into it then.

**Comment by asolino** [comment]
Hey @chaschinsm 

Take a look at the commit and let me know if it fixed the problem on your side. Please try to test as much as possible to verify there are no side effects. Thanks

**Comment by chaschinsm** [comment]
Hey @asolino

I reinstalled and now it looks like

$ python wmiquery.py domain/username@hostname -namespace //./root/rsop/computer
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

Password:
[!] Press help for extra shell commands
WQL> SELECT AccountList FROM RSOP_UserPrivilegeRight WHERE UserRight = 'seloaddriverprivilege' AND precedence = 1
| AccountList |
| [u'\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u044b'] |
WQL>

**Comment by asolino** [comment]
Hey @chaschinsm 

Are you sure you're using the latest [wmiquery.py]() script? The last commit changed that script as well. You should not be getting a `[` as part of the answer. Here's mine:

```
[!] Press help for extra shell commands
WQL> SELECT AccountList FROM RSOP_UserPrivilegeRight WHERE UserRight = 'seloaddriverprivilege' AND precedence = 1
| AccountList |
| Administrators FREEFLY\admin  FREEFLY\Гость FREEFLY\Гость2 Print Operators  |
WQL> 

```

**Comment by chaschinsm** [comment]
Hey @asolino

You are right, I updated but forgot to update this script, sorry 
Problem solved completely
Thank you

**Comment by asolino** [comment]
Good to know @chaschinsm, closing.
