### ISSUE TITLE
Question: Count property on iEnumWbemClassObject?

### ISSUE THREAD

**Issue by defkev** [CoreSecurity/impacket#307]
Hi,

Is there any way to get the number of instances in `iEnumWbemClassObject` (from a `ExecQuery`) without having to iterate over the whole thing using `Next(0xffffffff,1)`?

Some of my queries are returning a lot of results (500+) and having to go over each instance one-by-one is taking a lot of time to complete.
So the idea is to use something like `Next(0xffffffff,10)` (or 20, or whatever) and kick of a parallel thread for the post processing of each chunk but for this i'd need to know the number of objects in the first place.

Thanks
Cheers

**Comment by asolino** [comment]
Hey @defkev 

Good question.. I really don't know.. 
Based on the [IEnumWbemClassObject](https://msdn.microsoft.com/en-us/library/aa390857(v=vs.85).aspx) it doesn't look like there's a way to know the total amount of objects in the enumerator.

At first thought.. I think you proposed approach `Next(0xfffffff,10)` could make it faster..
