### ISSUE TITLE
SetOf instance has no attribute 'setComponents' - GetUserSPNs.py

### ISSUE THREAD

**Issue by cjdupreez** [CoreSecurity/impacket#310]
Hi CoreSecurity team, first off, thanks for an awesome toolset. I'm running into an issue with the GetUserSPNs.py script where the scripts executes just fine, but the only output I receive is the error: SetOf instance has no attribute 'setComponents'

This may be intended behaviour if there aren't in fact any UserSPNs on the DC, but it looks to me like rather there's an issue with the script or one of its imports.

![screen shot 2017-08-29 at 9 52 32 am](https://user-images.githubusercontent.com/5132774/29825473-861247d0-8ca2-11e7-8e35-cd6054825e57.png)

**Comment by asolino** [comment]
Hey @cjdupreez 

Can you verify what pyasn1 version are you running? I cannot reproduce this issue with pyasn1 0.2.3

thanks.

**Comment by cjdupreez** [comment]
Version: 0.1.7-1

I'll try again after updating here in a minute. Thanks for the quick response!

**Comment by cjdupreez** [comment]
Hi @asolino, I updated pyasn1 to 0.1.9-2 (the most current via apt-get) and re-ran GetUserSPNs.py which produced the following new error:

![image](https://user-images.githubusercontent.com/5132774/29829884-92a3acda-8cae-11e7-9132-79c9cae3583b.png)

Where ref1 is the target domain specified with the user as: domain/user

**Comment by cjdupreez** [comment]
I found the issue, the domain name had to be fully qualified. Thanks for your help!
