### ISSUE TITLE
Signature is REQUIRED - Win 2012

### ISSUE THREAD

**Issue by chacalito** [CoreSecurity/impacket#314]
Hi, 
I'm doing some tests against a Win 2012 server and getting the following msg:

[-] Signature is REQUIRED on the other end, attack will not work
[*] Authenticating against 192.168.0.108 as \Administrator SUCCEED

I'm using the following command line to make a request to attacker machine:

net use \\192.168.0.101\c$ password /USER:\administrator

I made a standard windows installation with no additional settings, but after I face this log I disabled the following options in secpol.msc to disable Signature:

Domain controller: LDAP server signing requirements
Domain member: Digitally encrypt or sign secure channel data (always)
Domain member: Digitally encrypt secure channel data (when possible)
Domain member: Digitally sign secure channel data (when possible)
Microsoft network client: Digitally sign communications (always)
Microsoft network client: Digitally sign communications (if server  agrees)
Microsoft network client: Send unencrypted password to third-party SMB  servers
Microsoft network server: Digitally sign communications (always)
Microsoft network server: Digitally sign communications (if client  agrees)
Microsoft network server: Disconnect clients when logon hours expire
Network security: LDAP client signing requirements

However, I keep getting the same log message (Signature is REQUIRED on the other end, attack will not work). 

Does smbrelayx.py work on Windows 2012 environment?

There is a way to bypass signature required? 

I will be very grateful if someone could help me.

**Comment by asolino** [comment]
Hey @chacalito 

`smbrelayx.py` indeed works against Windows 2012 (I actually tested it against Windows 2016). The issue here has to do with the server's configuration.
If you're targeting a domain controller (meaning, you're trying to relay credentials against the DC) no SMB Relay attack will work since DCs are enforcing SMB signing for any client connecting to them.

This could also happen when targeting other servers in the domain, depending on the GPOs applied in the domain joined workstations. 

The GPOs that need to be changed depends on who's enforcing signing, but in general are these two:
```
Microsoft network client: Digitally sign communications (always)
Microsoft network client: Digitally sign communications (if server agrees)
Microsoft network server: Digitally sign communications (always)
Microsoft network server: Digitally sign communications (if client agrees)
```
If you disabled both, and you're still receiving the `Signature is REQUIRED` message it is because you didn't disable them in the right GPO, or you're still targeting the DC. Getting the Wireshark capture will help me understand who's enforcing it (client or server). You can check that in the first SMB messages exchanged (NEGOTIATE packets).

Hope this helps,

**Comment by chacalito** [comment]
Hi @asolino 
Thank you so much for your help. My delay to reply was because even disabling these GPOs I was keeping receiving the same log message (Signature os REQUIRED), but after disabling it via regetid [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanManServer\Parameter\{EnableSecuritySignature}] it worked.

However I got a new trouble , after few seconds that I compromised the server and the tool executed the payload, the session on metasploit handler dies. The own smbrelayx remove the .exe as the log shows below:

```
[-] 192.168.0.108 is being attacker at the moment, skipping.. 
[*] Service Installed.. CONNECT!
[*] Opening SVCManager on 192.168.0.108.....
[*] Stoping service SItD.....
[*] Removing service SItD.....
[*] Removing file LsetwAWv.exe.....
```

It's so fast that I have no time enough to migrate the session. I saw the possible parameters with --help but I didn't see any parameter to keep the session alive for more time.

There is a way to make it takes longer?

**Comment by asolino** [comment]
Hey @chacalito 

Good to know you solved the signing issue. With regards to your new challenge, I don't think there's something you need to change in smbrelayx.py. Maybe these links would be helpful:

1. https://shellgam3.com/2017/02/07/relaying-netntlmv2-hashes-into-a-meterpreter-shell/
2. https://cqureacademy.com/blog/penetration-testing/smb-relay-attack

Another option is to run `smbrelayx.py` without the `-c` switch. If so, it will automatically try to download the target SAM database including the Administrator's NTLM hashes. Once you have them, you can pass the hash to execute whatever you want.

Let me know how it goes

**Comment by chacalito** [comment]
Hi @asolino 

Thank you so much for your help. I'll write a blog post about this in portuguese language to help others as you helped me. :)

**Comment by asolino** [comment]
Good to know it helped @chacalito!

Please point me out to the blog post once you write it :)

**Comment by chacalito** [comment]
Hi @asolino 
Here it's: https://www.guiadoti.com/2017/09/entendendo-o-ataque-smb-relay-ntlmv2/
I thanked you at the end of the post for your help ;)

**Comment by asolino** [comment]
Nice article @chacalito! Congrats and thanks for the mention!
