### ISSUE TITLE
Issue installing Impacket

### ISSUE THREAD

**Issue by jcboysha** [CoreSecurity/impacket#324]
When trying to run secretsdump.py after install of Impacket, I get the following error message:

Traceback (most recent call last):
  File "/usr/share/doc/python-impacket/examples/secretsdump.py", line 61, in <module>
    from impacket import system_errors
ImportError: cannot import name system_errors

Does anyone have any suggestions about what I may have done wrong? 

The impacket version is 0.9.9.9 and it was installed manually vice pip.

**Comment by asolino** [comment]
Hey @jcboysha 

Impacket 0.9.9.9 is 6 versions old. I'd suggest you to install `0.9.15` or `0.9.16-dev` (development version).

**Comment by jcboysha** [comment]
That fixed it. Thanks. Now I feel silly.
