### ISSUE TITLE
pyasn1-0.3.5: Error: can only concatenate tuple (not "str") to tuple 

### ISSUE THREAD

**Issue by sho-luv** [CoreSecurity/impacket#325]
So when I run the following command
GetUserSPNs.py domain/user:password

Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

ServicePrincipalName                                                     Name           MemberOf                                         PasswordLastSet      LastLogon           
-----------------------------------------------------------------------  -------------  -----------------------------------------------  -------------------  -------------------
<information no problem!>

GetUserSPNs.py domain/user:password -request

ServicePrincipalName                                                     Name           MemberOf                                         PasswordLastSet      LastLogon           
-----------------------------------------------------------------------  -------------  -----------------------------------------------  -------------------  -------------------
<information no problem!>

however I then get this error:

can only concatenate tuple (not "str") to tuple

any ideas as to what sort of data I'm getting back that might cause this?

**Comment by asolino** [comment]
Hey @sho-luv 

What pyasn1 version you have installed in your system? That might be the problem. You can quickly check it from your python console:
```
import pyasn1
pyasn1.__version__
```

**Comment by sho-luv** [comment]
Apparently I'm running 0.3.5

```
pyasn1.__version__
'0.3.5'

```

**Comment by asolino** [comment]
Certainly I can reproduce that in `pyasn1 0.3.5`. While I take a look at it, please install an older version for that library.
`pyasn1-0.3.3` should work.

**Comment by asolino** [comment]
Just tested `pyasn1-0.3.4` and it works as well. Something's wrong with the latest version and our code.

**Comment by sho-luv** [comment]
Thanks. Rolling it back works for me as well. For now I use the workaround
`pip install pyasn1==0.3.3``

**Comment by asolino** [comment]
New `pyasn1` release (`0.3.6`) tagged with this fix. Closing this one. Thanks @sho-luv for reporting it and @etingof for the quick turnaround!. Closing.
