### ISSUE TITLE
Prefer pycryptodome over pycrypto

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#336]
Hello @asolino,

As you may know PyCrypto developement stopped few years ago and some vulns will remained unpatched, for instance [this one](https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/).
[Pycryptodome](https://pypi.python.org/pypi/pycryptodome) is a good transparent replacement (same module namespace `import Crypto.XXX`, same API).

Cheers.

**Comment by maaaaz** [comment]
Hello there,
I might add that when you want to install `impacket` on Windows : 
* while the `pycrypto` requires a local nightmare compilation and you thus need some `Visual C++` (with the infamous error `Visual C++ <version> is required`)...
* ...whereas if you replace `pycrypto` by `pycryptodome` is the `setup.py` or `requirements.txt`, you won't need any compilation, as `pycryptodome` provides a pre-compiled package

All in all, prefer `pycryptodome` :-)

Cheers

**Comment by asolino** [comment]
Fixed in https://github.com/CoreSecurity/impacket/pull/485
