### ISSUE TITLE
Install all dependencies when doing 'pip install impacket'

### ISSUE THREAD

**Issue by maaaaz** [CoreSecurity/impacket#337]
Hello @asolino,

It would be great if all necessary python modules could be installed when doing `pip install impacket`.
You just have to edit your `setup.py` file with the following directive: `install_requires=['pycrypto', etc.]`.

Same for `argparse` dependency for Python < 2.7, you can script it in the install.

Cheers.

**Comment by asolino** [comment]
Hey @maaaaz .. Mind issuing a PR?

**Comment by asolino** [comment]
Any news here @maaaaz?

**Comment by maaaaz** [comment]
Hello @asolino,

I did it:
* you can check the [diff here](https://github.com/CoreSecurity/impacket/commit/1e49818706fc52348a2648b9e812a8c4759f678b)
* you can download the (whole file here](https://github.com/maaaaz/impacket/blob/master/setup.py)

With this every dependency should now be automatically installed (based on the `requirements.txt` file).
If you want to try it:
1. `virtualenv testmaaaazpackage && source testmaaaazpackage\bin\activate`
2. `git clone https://github.com/maaaaz/impacket.git && cd impacket`
3. `pip install .`
4. `cd examples && python wmiquery.py -h`
5. Profit ;)

Cheers !

**Comment by asolino** [comment]
Awesome @maaaaz! Just committed your changes thanks!

**Comment by maaaaz** [comment]
You're welcome !
