### ISSUE TITLE
 SMB_COM_TREE_CONNECT_ANDX Response struct alignment

### ISSUE THREAD

**Issue by tsela85** [CoreSecurity/impacket#342]
Hi 

The _SMB_COM_TREE_CONNECT_ANDX_ Response is specified in [[MS-SMB]](https://msdn.microsoft.com/en-us/library/cc246231.aspx) (2.2.4.6.1 Client Request Extensions) states that the "NativeOS" and "NativeLanMan" variables are aligned to 2

> NativeOS (variable): A string representing the native operating system of the CIFS client ...... If this string consists of Unicode characters, this field MUST be aligned to start on a 2-byte boundary from the start of the SMB header.

In Impacket, the `SMBSessionSetupAndX_Extended_Response_Data` is implemented in the `smb.py` file without any alignment setting on these string fields 

```
class SMBSessionSetupAndX_Extended_Response_Data(AsciiOrUnicodeStructure):
      AsciiStructure = (
        ('SecurityBlobLength','_-SecurityBlob','self["SecurityBlobLength"]'),
        ('SecurityBlob',':'),        
        ('NativeOS','z=""'),
        ('NativeLanMan','z=""'),
    )

    UnicodeStructure = (
        ('SecurityBlobLength','_-SecurityBlob','self["SecurityBlobLength"]'),
        ('SecurityBlob',':'),        
        ('NativeOS','u=""'),
        ('NativeLanMan','u=""'),
    )
```

As a result, the SMB_COM_TREE_CONNECT_ANDX_ Response packet may be invalid in situations were the `SecurityBlob` is of even length (because the length till the SecurityBlob will always be odd)

Any easy way to make sure that `NativeOS `and `NativeLanMan` will be aligned to 2 from the start of the SMB header?

**Comment by asolino** [comment]
Hey @tsela85 

Give it a try and let me know if it works on your side. If so, please close this issue.

**Comment by tsela85** [comment]
Hey @asolino, Thank very much, it is highly appreciated!

Consider performing this small change to commit [28f7c8a](https://github.com/CoreSecurity/impacket/commit/28f7c8a7cf46a2baaa38d6ec153840ffe03f05ab)

```
class SMBSessionSetupAndX_Extended_Response_Data(AsciiOrUnicodeStructure):
    AsciiStructure = (
        ('SecurityBlobLength','_-SecurityBlob','self["SecurityBlobLength"]'),
        ('SecurityBlob',':'),        
        ('NativeOS','z=""'),
        ('NativeLanMan','z=""'),
    )

    UnicodeStructure = (
        ('SecurityBlobLength','_-SecurityBlob','self["SecurityBlobLength"]'),
        ('SecurityBlob',':'),
        ('Pad',':=""'),           
        ('NativeOS','u=""'),
        ('NativeLanMan','u=""'),
    )

    def getData(self):
        if self.structure == self.UnicodeStructure:
            if len(str(self['SecurityBlob'])) % 2 == 0:
                self['Pad'] = '\x00'
        return AsciiOrUnicodeStructure.getData(self)
```

Because the alignment is only needed for Unicode strings, I removed the padding from the AsciiStructure and added a check that the struct is UnicodeStructure

**Comment by asolino** [comment]
Thanks for the clarification @tsela85. 
Please test again and close the issue if working on your side,.

**Comment by tsela85** [comment]
working 👍 
Thanks @asolino
