### ISSUE TITLE
RemoteName value

### ISSUE THREAD

**Issue by aidandamerell** [CoreSecurity/impacket#343]
The remoteName value is not correctly parsed when a password has an "@" symbol. The `if '@' in remoteName:` does not seem to work for this as remoteName is not correct after being generated.

`python /usr/local/bin/secretsdump.py DOMAIN/USERNAME:'R3@lly5Tr0nGP@55w0rd!'@IPADDRESS -just-dc-user "foo/bar"
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[-] RemoteOperations failed: [Errno Connection error (lly5Tr0nGP@55w0rd!@<IPADDRESS>:445)] [Errno 8] nodename nor servname provided, or not known`

**Comment by asolino** [comment]
Hey @aidandamerell 

Yes.. that is a known limitation. You can solve it by not specifying a password and waiting for the application to ask for it. Run the command this way:
```
python /usr/local/bin/secretsdump.py DOMAIN/USERNAME@IPAddress -just-dc-user "foo/bar"
```
and the next thing that will happen is the script asking you the password.
