### ISSUE TITLE
Wmiexec Fails to login if password starts with "!!"

### ISSUE THREAD

**Issue by 5p3c7r3** [CoreSecurity/impacket#347]
It seems that Wmiexec fails to login with Passwords that start with !!

root@HackNetOS:~# impacket-wmiexec Administrator:!!admin@192.168.1.11
impacket-wmiexec Administrator:impacket-wmiexec Administrator:pth-wmisadmin@192.168.1.11admin@192.168.1.11
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

[-] [Errno Connection error (Administrator:impacket-wmiexec:445)] [Errno -2] Name or service not known
root@HackNetOS:~# impacket-wmiexec Administrator:admin@192.168.1.11
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

[*] SMBv3.0 dialect used
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>exit

**Comment by the-useless-one** [comment]
Hi!

"!!" is a special bash commands that means "put here the last executed command". That's why your wmiexec fails. Try to escape them, with something like:

impacket-wmiexec Administrator:'!!admin'@192.168.1.11

**Comment by 5p3c7r3** [comment]
oh Thanks alot
