### ISSUE TITLE
secretsdump.py add OldVal dump to LSA secrets

### ISSUE THREAD

**Issue by Ramzeth** [CoreSecurity/impacket#357]
As it seen from source code
`value = self.getValue('\\Policy\\Secrets\\%s\\CurrVal\\default' % key)`
secretsdump.py dumps only current value of the LSAsecret. But there is a case when the current value is NULL but old value has a meaning. For example: DefaultPassword/OldVal can store actual password after the AutoLogon feature was disabled.

**Comment by asolino** [comment]
Hey @Ramzeth 

Fair point.. that could be added to the `-history` switch. Pull requests welcomed :)

**Comment by Ramzeth** [comment]
done
