### ISSUE TITLE
Validate NTLMv2 via AD through DCE/RPC

### ISSUE THREAD

**Issue by socketpair** [CoreSecurity/impacket#361]
Hello, guys. I want to use you great library to solve this task:

I'm writing HTTP-server that must authenticate clients via NTLMv2. These clients are actually relativaly old Windows clients. Next. I need to validate their authentication data through real ActiveDirectory server. I don't actually know how to exactly. Seems, through DCERPC. Usually (Apache, squid, and so on) this task is done via winbind. I don't want to use winbind by some reason.

Could you advise sekelton of such program that will use you library ? i.e. which DCE/RPC calls to use, in what sequence, and so on.

Also, machine where web-server is run is already joined to domain. Web server run under Linux.

**Comment by asolino** [comment]
Het @socketpair 

If you want to do that, you would need to do [Windows Pass Thru Authentication](https://msdn.microsoft.com/en-us/library/cc237015.aspx?f=255&MSPPError=-2147217396). All the bits to do that are in the library. In fact, I implemented most of the functionality when writing [this](https://www.coresecurity.com/advisories/windows-pass-through-authentication-methods-improper-validation) advisory.
Functionality is implemented in [smbrelayx.py](https://github.com/CoreSecurity/impacket/blob/master/examples/smbrelayx.py), in particular [here](https://github.com/CoreSecurity/impacket/blob/master/examples/smbrelayx.py#L289).
