### ISSUE TITLE
create domain admin fails due to accountExpires validation error

### ISSUE THREAD

**Issue by yonisim** [CoreSecurity/impacket#363]
1. invoke ntlmrelayx.py module
2. make a request with a domain admin and target the dc
3. the module tries to create a domain admin
4. error occures:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/bin/ntlmrelayx.py", line 211, in run
    self.addDA(domainDumper)
  File "/usr/local/bin/ntlmrelayx.py", line 178, in addDA
    res = self.client.connection.add('CN=%s,CN=Users,%s' % (newUser,domainDumper.root),['top','person','organizationalPerson','user'],ucd)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 909, in add
    request = add_operation(dn, attributes, self.auto_encode, self.server.schema if self.server else None, validator=self.server.custom_validator if self.server else None)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/add.py", line 50, in add_operation
    vals.setComponentByPosition(0, prepare_for_sending(validate_attribute_value(schema, attribute, attributes[attribute], auto_encode, validator)))
  File "/usr/local/lib/python2.7/dist-packages/ldap3/protocol/convert.py", line 160, in validate_attribute_value
    raise LDAPInvalidValueError('value \'%s\' non valid for attribute \'%s\'' % (value, name))
LDAPInvalidValueError: value '9223372036' non valid for attribute 'accountExpires'

reason:
in ntlmrelayx.py:
    def addDA(self, domainDumper):
        global addedDomainAdmin
        if addedDomainAdmin:
            logging.error('[%s] DA already added. Refusing to add another' % self.uuid)
            return

        #Random password
        newPassword = ''.join(random.choice(string.ascii_letters + string.digits + string.punctuation) for _ in range(15))

        #Random username
        newUser = ''.join(random.choice(string.ascii_letters) for _ in range(10))

        ucd = {
            'objectCategory': 'CN=Person,CN=Schema,CN=Configuration,%s' % domainDumper.root,
            'distinguishedName': 'CN=%s,CN=Users,%s' % (newUser,domainDumper.root),
            'cn': newUser,
            'sn': newUser,
            'givenName': newUser,
            'displayName': newUser,
            'name': newUser,
            'userAccountControl': 512,
            'accountExpires': 0,
            'sAMAccountName': newUser,
            'unicodePwd': '"{}"'.format(newPassword).encode('utf-16-le')
        }

        res = self.client.connection.add('CN=%s,CN=Users,%s' % (newUser,domainDumper.root),['top','person','organizationalPerson','user'],ucd)

if i change the   'accountExpires': 0,  to    'accountExpires': '0',
it works fine

**Comment by dirkjanm** [comment]
Can you let me know which version of ldap3 and pyasn1 this was with? Haven't seen this one before.

**Comment by asolino** [comment]
Any news @yonisim?

**Comment by yonisim** [comment]
i'm unsure of that currently and can't really reproduce
thanks anyway
will update if i will bump into it again

**Comment by asolino** [comment]
Thanks for your comment @yonisim. I'll close this issue. If you find something please re-open it.

**Comment by dirkjanm** [comment]
For reference, this was fixed in db302a70ff31d54e2e3a2664119efc28b99b79be
