### ISSUE TITLE
Error with GetUserSPN.py: getComponentByPosition

### ISSUE THREAD

**Issue by timbo05sec** [CoreSecurity/impacket#366]
I am getting an error when I run GetUserSPN.py. 
Command: ```GetUserSPNs.py -request -outputfile 20180105_kerberoast.txt -dc-ip <IP> <domain>/<username>```
Error:  ```getComponentByPosition() got an unexpected keyword argument 'default'```

Things I have tried:
 - git cloned the latest impacket repo
 - removed the currently installed version of impacket (kali)
 - ran the setup.py install command
 - found that the getComponentByPosition function is part of ldapasn1.py, which imports stuff from pyasn1; I tried older versions of pyasn1 but that results in a different error message (which I believe is solved by updating pyasn1)
- updated to the latest version of python2.7
- I have tried running against multiple DCs, and tried multiple formats for the domain name

Are there other things to try, or a way to provide you with additional details to help me resolve this error.

**Comment by asolino** [comment]
hey @timbo05sec 

That's probably a `pyasn1`version issue. What version are you running?. Try this:
```
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyasn1
>>> pyasn1.__version__
'0.4.2'
>>> 
```

`pyasn1` >= 0.2.3 should work. Let me know.

**Comment by timbo05sec** [comment]
That is what I assumed...  I tried updating to 0.4.2 first, when that did not work, I tried several prior versions; then, I went back to 0.4.2.
>>> import pyasn1
>>> pyasn1.__version__
'0.4.2'

**Comment by asolino** [comment]
Hey @timbo05sec .. thanks for the info..

You sure you updated impacket?.. in particular this commit and line.. https://github.com/CoreSecurity/impacket/commit/c001138f76075e602f16f7ac143bcb409f1dfef2#diff-712c7b46b17b74c3f09115c8fc3bf105R50
If it still happening, uncomment these [two commented lines](https://github.com/CoreSecurity/impacket/blob/master/examples/GetUserSPNs.py#L421), run again and send me the output.

**Comment by timbo05sec** [comment]
To start, I performed a git clone of the latest... But, to be sure, I looked at the diff you referenced and the changes to the ldapasn1.py file are in there.  
Here is the trace:
Traceback (most recent call last):
  File "./GetUserSPNs.py", line 419, in <module>
    executer.run()
  File "./GetUserSPNs.py", line 228, in run
    ldapConnection.login(self.__username, self.__password, self.__domain, self.__lmhash, self.__nthash)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 320, in login
    bindRequest['authentication']['sicilyNegotiate'] = negotiate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1-0.4.2-py2.4.egg/pyasn1/type/univ.py", line 2052, in __getitem__
    return self.getComponentByName(idx)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1-0.4.2-py2.4.egg/pyasn1/type/univ.py", line 2163, in getComponentByName
    return self.getComponentByPosition(idx, default=default, instantiate=instantiate)
TypeError: getComponentByPosition() got an unexpected keyword argument 'default'
None
getComponentByPosition() got an unexpected keyword argument 'default'

**Comment by asolino** [comment]
Something tells me you have two different Impacket versions running.

Are you running on Kali?.. If so.. there are known issues with that. Looks at this line:
```
File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 320, in login
bindRequest['authentication']['sicilyNegotiate'] = negotiate
```
That line does not have that content under the [latest version](https://github.com/CoreSecurity/impacket/blob/master/impacket/ldap/ldap.py#L320)

I'd suggest you *remove* the `/usr/local/lib/python2.7/dist-packages/impacket/` directory and re-install.

**Comment by timbo05sec** [comment]
Well, drats...  I had tried that earlier, because I knew of the issues with the one installed by kali.  I must have gotten something crossed along the way.  I apologize for wasting your time.

**Comment by asolino** [comment]
did it work?

**Comment by timbo05sec** [comment]
yes, that did work.  thank you.
