### ISSUE TITLE
ntlmrelayx.py doesn't always decode a username from UTF16-LE

### ISSUE THREAD

**Issue by mohemiv** [CoreSecurity/impacket#368]
ntlmrelayx.py doesn't always decode a username from UTF16-LE:

Server: `/impacket/examples/smbserver.py admin ./empty`
Client:
```
/impacket/examples/ntlmrelayx.py -socks --target smb://server-ip:445/ -debug &
curl http://127.0.0.1/ -k -i --ntlm -u 'DOMAIN.LOCAL\admin':12345
proxychains /opt/impacket/examples/smbclient.py admin@server-ip -no-pass
```

Client output:
```
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] Running in relay mode to single host
[*] SOCKS proxy started. Listening at port 1080
[*] Plugin SMB Socks Plugin loaded..
[*] Config file parsed
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] HTTPD: Received connection from 127.0.0.1, attacking target server-ip
[*] Authenticating against server-ip as DOMAIN.LOCAL\admin SUCCEED
[*] admin::DOMAIN.LOCAL:4141414141414141:***
[*] Adding server-ip(445) to active SOCKS connection. Enjoy
[+] SOCKS: New Connection from 127.0.0.1(40092)
[+] SOCKS: Adding server-ip:445 to list of relayConnections
[+] SOCKS: Target is server-ip(445)
[+] Handler for port 445 found impacket.examples.ntlmrelayx.servers.socksplugins.smb.SMBSocksRelay
[-] SOCKS: No session for admin@server-ip(445) available
```

/impacket/ntlmrelayx/servers/socksplugins/smb.py:
```
            authenticateMessage = NTLMAuthChallengeResponse()
            authenticateMessage.fromString(token)

            # Check if we have a connection for the user

            if self.activeRelays.has_key(authenticateMessage['user_name']): # Problem line
                LOG.info('SOCKS: Proxying client session for %s@%s(445)' % (
                authenticateMessage['user_name'].decode('utf-16le'), self.targetHost))
                errorCode = STATUS_SUCCESS
                smbClient = self.activeRelays[authenticateMessage['user_name']]['client']
                uid = smbClient.get_uid()
            else:
                LOG.error('SOCKS: No session for %s@%s(445) available' % (
                authenticateMessage['user_name'].decode('utf-16le'), self.targetHost))
                errorCode = STATUS_ACCESS_DENIED
                uid = 0
```
Condition `self.activeRelays.has_key(authenticateMessage['user_name'])` is false, because self.activeRelays has a index with decoded username, but authenticateMessage['user_name'] has a username in UTF16-LE.

It's not possible to fix it by add `.decode('utf-16le')` to the line, because a lot of other code also incorrectly reads a username.

**Comment by asolino** [comment]
Thanks for the bug report @mohemiv 

Could you please check the [relay-experimental](https://github.com/CoreSecurity/impacket/tree/relay-experimental) branch? I'm almost sure that issue got fixed there and I'll be landing that branch soon.

**Comment by mohemiv** [comment]
Unfortunately, the relay-experimental branch doesn't work:
```
[*] HTTPD: Received connection from 127.0.0.1, attacking target smb://server-ip:445
[-] Exception in HTTP request handler: 'utf16' codec can't decode byte 0x6e in position 4: truncated data
```
It's the output from ntlmrelayx.py after command `curl http://127.0.0.1/ -k -i --ntlm -u 'DOMAIN.LOCAL\admin':12345`

@asolino, Can I ask you one question? Does the relay-experimental branch have support SMB ->HTTP and HTTP->HTTP attacks?

**Comment by asolino** [comment]
Hey @mohemiv 

Give it a try again with the relay-experimental branch. Close the issue if it works.

>> @asolino, Can I ask you one question? Does the relay-experimental branch have support SMB->HTTP and HTTP->HTTP attacks?

Yes it does. In fact, it should also support those scenarios setting up a SOCKS proxy as well

**Comment by mohemiv** [comment]
Thanks @asolino

Attacks SMB->HTTP, HTTP->SMB and HTTP->HTTP work now.
