### ISSUE TITLE
my smbrelayx don't work

### ISSUE THREAD

**Issue by Jumbo-WJB** [CoreSecurity/impacket#371]
hello,
my smbrelayx don't work
my host is macox ,target is windows 10 
this is my test screenshot
`Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] Running in relay mode
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[-] Connection against target 10.98.64.155 FAILED
[-] [Errno 54] Connection reset by peer
[-] processRequest (0x73,[Errno 54] Connection reset by peer)
[-] processRequest (0x72,'SMBClient')
[*] HTTPD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[*] HTTPD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[-] processRequest (0x72,'SMBClient')
[*] HTTPD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[*] HTTPD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[*] HTTPD: Received connection from 10.98.64.155, attacking target 10.98.64.155
[-] Connection against target 10.98.64.155 FAILED
[-] [Errno 54] Connection reset by peer
[-] processRequest (0x72,'SMBClient')`
![wechatimg5](https://user-images.githubusercontent.com/7954518/34814797-e56f2e76-f6e9-11e7-90eb-df09d450f461.jpeg)
Look forward to your reply
thinks

**Comment by mohemiv** [comment]
Unfortunately, this vulnerability was lost with the patch MS08-68.

Now you can get the victim to connect to us and then back to other host (maybe to domain controller), but not to the same host.

**Comment by Jumbo-WJB** [comment]
@mohemiv thinks

**Comment by asolino** [comment]
thanks for clarifying that @mohemiv. Closing.
