### ISSUE TITLE
Is SMB3.1.1 supported? When can we expect it's support?

### ISSUE THREAD

**Issue by codefetcher** [CoreSecurity/impacket#375]

**Comment by asolino** [comment]
Hey @codefetcher 

Currently we just support `SMB 3.0.0`. Neither `SMB 3.0.2` nor `SMB 3.1.1` are supported.
Eventually we will be adding support for those dialects, although it's not high priority now. PRs are welcome :)

**Comment by codefetcher** [comment]
Hi @asolino 

Thanks for the quick response. Yup if I'm able to add code for 3.1 support will create a PR for sure. Thanks again.
