### ISSUE TITLE
Feature Request: - ntlmrelayx relay credentials off different interface than the one captured on.

### ISSUE THREAD

**Issue by thesle3p** [CoreSecurity/impacket#377]
There are certain scenarios where it would be extremely useful to relay NetNTLM credentials off a different interface than the server that captures them (e.g. capture on wlan0 but relay to hosts on eth0) . Is this something that could be supported?

**Comment by asolino** [comment]
Hey @thesle3p 

That should work as it is. You specify the targets IPs that will be routed to the right interface depending on the OS routes.

The servers bind to all the interfaces.

Give it a try and let know.

**Comment by asolino** [comment]
Did you try it @thesle3p?

**Comment by thesle3p** [comment]
I will test this weekend
