### ISSUE TITLE
AttributeError: NTLMRelayxConfig instance has no attribute 'setRunSocks'

### ISSUE THREAD

**Issue by the-squ1d** [CoreSecurity/impacket#378]
I'm trying to run ntlmrelayx with mitm6 to try it out and I'm getting this error. I have installed all the dependencies and updated python today.

My python skills are not the greatest. Any idea what's up with this?

```
./ntlmrelayx.py -6 -socks -wh attacker.apollo.olympus.rt -t smb://192.168.206.103 -debug
Impacket v0.9.16-dev - Copyright 2002-2017 Core Security Technologies

[*] Running in relay mode to single host
[*] SOCKS proxy started. Listening at port 1080
[*] Plugin SMB Socks Plugin loaded..
Traceback (most recent call last):
  File "./ntlmrelayx.py", line 473, in <module>
    c.setRunSocks(options.socks)
AttributeError: NTLMRelayxConfig instance has no attribute 'setRunSocks'
```

**Comment by asolino** [comment]
Hey @the-squ1d 

Looks like you haven't installed the latest impacket's version. 

First, remove the version you currently have installed, by gathering the directory where it is installed. For example, from Python run this:
```
from impacket import version
print version.__file__
```
Remove all the files under that directory (all the path, except the filename).

Then, download the latest impacket and install it:
```
git clone https://github.com/CoreSecurity/impacket.git
cd impacket
python setup.py install
```
finally, try again `ntlmrelayx.py`

**Comment by the-squ1d** [comment]
Got it running, thank you. There was an issue where the Kali default installed impacket library was getting called instead of the updated version.
