### ISSUE TITLE
UnicodeStructure of class SMBOpen_Data is wrong

### ISSUE THREAD

**Issue by derekchentrendmicro** [CoreSecurity/impacket#380]
I think it should be like this
    UnicodeStructure = (
        ('FileNameFormat','"\x04'),
        ('FileName','u'),    <-- u instead of z
    )
and openFile['Data']['Pad'] in smb.open() is of no use and should be removed.

**Comment by asolino** [comment]
Hey @derekchentrendmicro .. 

thanks for the report.. can you send a PR?

**Comment by asolino** [comment]
Fixed in https://github.com/CoreSecurity/impacket/pull/384, closing.
