### ISSUE TITLE
Does impacket support SMB3? 

### ISSUE THREAD

**Issue by munirajtomar** [CoreSecurity/impacket#382]
we are going to use content-fetch and delete action on remote files from a smb3 devices. Still there is an open questions around impacket support for SMB3. Can you please confirm. Thanks in advance.

**Comment by asolino** [comment]
Impacket supports `SMB 3.0.0` dialect. It does *not* support `3.0.2` and `3.1.1`.
In any case, coverage for `3.0.0` is not complete. You should check yourself if the library provides what you need, for your specific use cases.
