### ISSUE TITLE
NamedTypes can cast only scalar values

### ISSUE THREAD

**Issue by intrd** [CoreSecurity/impacket#385]
Im getting this pyasn1 error on every module that uses kerberos..

```
psexec.py ASD.LOCAL/user@dc.asd.local -k -debug
Impacket v0.9.13 - Copyright 2002-2015 Core Security Technologies
Password:
[*] Trying protocol 445/SMB...
[-] PyAsn1Error('NamedTypes can cast only scalar values',)

```

**Comment by intrd** [comment]
Sorry, I was using impacket 0.9.13, updating to current fixed the problem.

**Comment by edermi** [comment]
Hi,

first of all, thanks for your awesome work!
Unfortunately, this problem still exists and I stumbled across it in several different environments during the last few months and found time to submit an issue:

```
PS C:\Users\med_test_1\Desktop> .\GetUserSPNs.exe
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

usage: GetUserSPNs.exe [-h] [-request] [-request-user username] [-save]
                       [-outputfile OUTPUTFILE] [-debug]
                       [-hashes LMHASH:NTHASH] [-no-pass] [-k]
                       [-aesKey hex key] [-dc-ip ip address]
                       target

Queries target domain for SPNs that are running under a user account

positional arguments:
  target                domain/username[:password]

optional arguments:
  -h, --help            show this help message and exit
  -request              Requests TGS for users and output them in JtR/hashcat
                        format (default False)
  -request-user username
                        Requests TGS for the SPN associated to the user
                        specified (just the username, no domain needed)
  -save                 Saves TGS requested to disk. Format is
                        <username>.ccache. Auto selects -request
  -outputfile OUTPUTFILE
                        Output filename to write ciphers in JtR/hashcat format
  -debug                Turn DEBUG output ON

authentication:
  -hashes LMHASH:NTHASH
                        NTLM hashes, format is LMHASH:NTHASH
  -no-pass              don't ask for password (useful for -k)
  -k                    Use Kerberos authentication. Grabs credentials from
                        ccache file (KRB5CCNAME) based on target parameters.
                        If valid credentials cannot be found, it will use the
                        ones specified in the command line
  -aesKey hex key       AES key to use for Kerberos Authentication (128 or 256
                        bits)
  -dc-ip ip address     IP Address of the domain controller. If ommited it use
                        the domain part (FQDN) specified in the target
                        parameter
PS C:\Users\med_test_1\Desktop> .\GetUserSPNs.exe contoso.com/med_test_1
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

Password:
PyAsn1Error('NamedTypes can cast only scalar values',)
```

In this case I used a selfmade Windows executable built with pyinstaller, but I can assure that under a fully patched kali with all depedencies installed, the problem is still there.

It would be nice if you could take a look at it / test it again in your environments. My pyasn Version is 0.4.3.

**Comment by asolino** [comment]
Hey @edermi 
Impacket `0.9.15` is not compatible with pyasn1 `0.4.3`. I'd recommend you to install the master (currently `0.9.17-dev`) impacket version (either doing a `git pull https://github.com/CoreSecurity/impacket.git` or download the zipped file and then run `python setup.py install`). 
The end result is that you should see the `0.9.17-dev` banner when running any script.
If you don't see that, that might mean there's an old impacket version installed that needs to be removed (check [this comment](https://github.com/CoreSecurity/impacket/issues/378#issuecomment-359545552)). 

Then re-test and let me know.

**Comment by edermi** [comment]
Hi asolino,

thanks for your fast reply. Indeed, using impacket from github and making sure that the 0.9.17-dev is in use, everything works fine now. Thank you!

**Comment by latundetoks** [comment]
Solved it for me also.
