### ISSUE TITLE
Running wmiexec.py from bash gives error:  [ - ] decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by CryptomaticSquirrel** [CoreSecurity/impacket#394]
Hello.

I found that when the wmiexec.py is run **FROM** a bash file then it gets sys.stdin.encoding as None.
This results in:   [ - ] decode() argument 1 must be string, not None

If the script is run directly by user from Bash or Bash script then the value for sys.stdin.encoding is UTF8 and there are no problems.

The issue is present at Lines 205, 265 in /examples/wmiexec.py. When I removed the sys.stdin.encoding the problem resolved for me. For the time being.

**Comment by reinaldo-gomes** [comment]
It means that your script is not getting the proper environment variable.

In my case, it worked when I wrote the following on my service unit file:

[Service]
[...]
Environment=PYTHONIOENCODING=utf8
