### ISSUE TITLE
examples/nmapAnswerMachine.py using os_ident

### ISSUE THREAD

**Issue by xambroz** [CoreSecurity/impacket#404]
Hello,
The example script examples/nmapAnswerMachine.py is using os_ident as a import, but the file gets installed as a script to /usr/bin/os_ident.py

I guess the os_ident.py should go to impacket/examples/os_ident.py and the dependency in nmapAnswerMachine.py should change to:
from impacket.examples import os_ident

Thank you
Michal Ambroz

**Comment by asolino** [comment]
Merged, thanks @xambroz!

**Comment by suhyeonjin** [comment]
@xambroz 
Can I use os_ident and nmapMachine to probing about os fingerprint?

Currently, I am supposed to emulating the fingerprint, but I do not understand. Why not send a probing package like nmap? I tried to make a probing pack with a little modifications, but the Ethernet Frame Checksum Sequence does not fit.
