### ISSUE TITLE
wmiexec.py creating temp file on remote server

### ISSUE THREAD

**Issue by aniketprajapati** [CoreSecurity/impacket#411]
In some environment's(windows servers) where we do not have access to write permissions, yet we want to execute the command and get back the output. Need an option that will not alter remote server.

**Comment by asolino** [comment]
That could be achieved by implementing the [SERVER MODE](https://github.com/CoreSecurity/impacket/blob/master/examples/smbexec.py#L20) functionality already available in [smbexec.py](https://github.com/CoreSecurity/impacket/blob/master/examples/smbexec.py). This will require `root` privileges at the client machine tho, in order to launch a [SMBSERVER](https://github.com/CoreSecurity/impacket/blob/master/impacket/smbserver.py#L4531).

I'll leave this open in case the is somebody willing to implement this feature.

**Comment by aniketprajapati** [comment]
Thanks for the response @asolino  but I tried smbexec.py as well, but I could not execute a command from the client machine(Centos) and get the data back in a single command rather than using an interactive shell(cmd.exe), I executed with root user(Linux) as stated in the documentation, yet no success. Please provide an example if it worked for you.

**Comment by asolino** [comment]
I'm not saying you should use `smbexec.py` @aniketprajapati . I'm saying `wmiexec.py` could support the `SERVER MODE` that is already implemented in `smbexec.py`.

You might not be able to run `smbexec.py` in your environment if you cannot create Windows Services.

Are you Administrator in the target Windows machines?

**Comment by aniketprajapati** [comment]
@asolino  I am a Local user, not an Administrator and yes, it could support SERVER mode in wmiexec.py, but currently I reckon the support is not there, correct me if i am wrong

**Comment by asolino** [comment]
So are you sure you can execute WMI queries not being an Administrator @aniketprajapati?

That is correct, `wmiexec.py` currently does *not* support `SERVER` mode. What I said is that implementing it should be similar to what's already done in `smbserver.py`

**Comment by aniketprajapati** [comment]
@asolino I am able to run WMI queries, but the output for certain commands like netstat/arp/route print is very crucial for my use case. I want to execute all those commands from Linux terminal, with local user privileges. And yes, implementing SERVER mode would be the best solution here or we have any other options?

**Comment by asolino** [comment]
Hey @aniketprajapati 
I'm not aware of any implementation that can achieve this.
