### ISSUE TITLE
ticketer.py creates a PAC from scratch instead of modifying the current ticket

### ISSUE THREAD

**Issue by machosec** [CoreSecurity/impacket#421]
Hi @asolino,
I have noticed that `ticketer.py` will always create a PAC from zero regardless of the `request` flag, as both `createBasicPac` and `createBasicValidationInfo` functions don't use the current ticket's information (except encryption type). I thought the initial purpose of requesting a ticket for the current user is to use his PAC as a base for alteration. So unless I haven't missed something, U2U is not necessary for this scenario, and it shouldn't be a problem to obtain the user's authentic PAC by decrypting and parsing the ticket retrieved from `getKerberosTGT`. Currently, I got stuck trying to extract the PAC portion from the ticket (`kdcRep`) in a compatible form (`pacInfos`).

Any help will be appreciated :)

**Comment by asolino** [comment]
Hey @machosec 

Makes sense what you say.. Indeed we're just honoring whatever encryption method is used by the original ticket, and that's pretty much it.

>Currently, I got stuck trying to extract the PAC portion from the ticket (kdcRep) in a compatible form (pacInfos).

Have you played with [getPac.py](https://github.com/CoreSecurity/impacket/blob/master/examples/getPac.py)?

**Comment by asolino** [comment]
Also, [this](https://github.com/CoreSecurity/impacket/blob/master/examples/raiseChild.py#L844) method might be what you're looking for.

**Comment by machosec** [comment]
Yes, the `makeGolden` is what I was looking for. However, I still have an odd issue.
I managed to modify the ticket and I verified its validity by performing a DCsync with that ticket (no password provided).
But when I try to save that ticket as ccache, I get `InvalidChecksum: ciphertext integrity failure` error when calling `ccache.fromTGT`.

Any thoughts?

**Comment by machosec** [comment]
Ok, I found my problem. I didn't put the right `sessionKey`. Confusing stuff..
If you want I can make a commit in ticketer.py to use a similar approach like `makeGolden` when specified with `-request`.

Thanks for the help!

**Comment by asolino** [comment]
Good to know @machosec.
Yup.. if you could issue a PR with this functionality that'd be great. thanks!
