### ISSUE TITLE
Feature Request - ntlmrelayx.py support for SMB 2.1, 3.0, 3.1?

### ISSUE THREAD

**Issue by wintermute4316** [CoreSecurity/impacket#425]
Dude you're awesome and Impacket is one of the best and most useful pentest tools out there - definitely in my top 5 of all time and up there with Metasploit, Mimikatz, and nmap.  Just wondering if SMB 2.1, 3.0, and 3.1 support are on the roadmap at some point for ntlmrelayx.py and smbrelayx.py.  Currently the smb2support experimental option seems to only support SMB 2.002 dialect.  Keep up the awesome work and great job!

**Comment by asolino** [comment]
Support for 2.1 and 3.0 are in the roadmap. 3.1 will probably won't work since (finally) MSFT added decent relay protection mechanisms.
