### ISSUE TITLE
ImportError: No module named tcpshell

### ISSUE THREAD

**Issue by ivanov21** [CoreSecurity/impacket#437]
Hello everyone sorry for my english,

I get this error when executing ntlmrelayx.py. Can anybody help me to solve this problem?

**Comment by asolino** [comment]
Hey @ivanov21 
You seemed to be running an outdated impacket (or incorrectly installed) version with a newer ntlmrelayx.py version. Make sure to install the latest library version  (and remove the old ones installed), and try again. 

Closing this issue, reopen if problem persists.

**Comment by ivanov21** [comment]
Thanks for your help, i'll try a newer version
