### ISSUE TITLE
RPC Access Denied despite all services running on target

### ISSUE THREAD

**Issue by pkaramol** [CoreSecurity/impacket#449]
I have a `Windows 10 Pro` machine running.

The `wmiexec.py` example script when run on Ubuntu seems to have the following issue:

(using `python 2.7.12`)

```
    python wmiexec.py username:password@<windows_10_IP> -debug
    Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies
    
    [+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
    Download it from https://www.dlitz.net/software/pycrypto
    [*] SMBv3.0 dialect used
    Traceback (most recent call last):
      File "wmiexec.py", line 83, in run
        iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
      File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1056, in CoCreateInstanceEx
        iInterface = scm.RemoteCreateInstance(clsid, iid)
      File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1837, in RemoteCreateInstance
        resp = self.__portmap.request(request)
      File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 837, in request
        answer = self.recv()
      File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1299, in recv
        raise DCERPCException(rpc_status_codes[status_code])
    DCERPCException: rpc_s_access_denied
    [-] rpc_s_access_denied

```

However the RPC service is __running__ in Windows and connection to port `135`
succeeds.

All the following services are running on the target (Windows) host actually:

> Remote Procedure Call (RPC)
> 
> Computer Browser
> 
> Server
> 
> Remote Registry
> 
> Windows Management Instrumentation
> 
> Netlogon
> 
> Remote Desktop Services
> 
> Windows Remote Management (WS-Management)

File / Printer sharing is enabled also.

**Comment by asolino** [comment]
Hey @pkaramol 

Are you using the `Administrator` account?

**Comment by pkaramol** [comment]
Νοp. using a user that __belongs__ to the __Administrators__ group however.

**Comment by asolino** [comment]
Can you  `secretsdump` against the target, get the Administrator hashes and pass those hashes to `wmiexec`?

**Comment by asolino** [comment]
No answer, closing
