### ISSUE TITLE
GetADUsers.py Feature Request

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#454]
Would be nice to output only enabled accounts, or have output for enabled/disabled

**Comment by asolino** [comment]
Makes sense.... You gave two options.. Which one you prefer?

**Comment by mubix** [comment]
@asolino I would say if you can save bandwidth or time with only getting "enabled" then I would say have it as a flag, if it's the same amount of traffic either way then have it output enabled/disabled as a field.

**Comment by asolino** [comment]
Let me know if this works for you @mubix. Close this issue if so.

**Comment by asolino** [comment]
No answer, closing.
