### ISSUE TITLE
rpc_s_access_denied when attempting to use wmiexec.py

### ISSUE THREAD

**Issue by jmdamiane** [CoreSecurity/impacket#457]
Hi,

My target machine is running Windows 10 Home version, and I'm running wmiexec.py on Kali with Python version 2.7.15. I am logged into an Administrator account, I have confirmed the following services are running, and I'm able to connect to port 135 on the target using Telnet. 

**Services:**

Remote Procedure Call (RPC)
Computer Browser
Server
Remote Registry
Windows Management Instrumentation
Netlogon
Remote Desktop Services
Windows Remote Management (WS-Management) 
File and Printer Sharing

I keep getting the following error:

```
python wmiexec.py -debug user:pass@<ip_address>
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

[+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
[*] SMBv3.0 dialect used
Traceback (most recent call last):
  File "wmiexec.py", line 83, in run
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/dcomrt.py", line 1056, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/dcomrt.py", line 1837, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/rpcrt.py", line 837, in request
    answer = self.recv()
  File "build/bdist.linux-x86_64/egg/impacket/dcerpc/v5/rpcrt.py", line 1299, in recv
    raise DCERPCException(rpc_status_codes[status_code])
DCERPCException: rpc_s_access_denied
[-] rpc_s_access_denied
```

Running secretsdump.py throws the same error:

```
python secretsdump.py -debug user:pass@<ip_address>
Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

[+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
[-] RemoteOperations failed: DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied 
[+] Exiting NTDSHashes.dump() because rpc_s_access_denied
[*] Cleaning up... 
[+] Your pycrypto doesn't support AES.MODE_CCM. Currently only pycrypto experimental supports this mode.
Download it from https://www.dlitz.net/software/pycrypto
```

I know there is a similar thread posted a few weeks back, but wanted to post a separate one with my specific info. 
Thanks in advance!

**Comment by asolino** [comment]
Hey @jmdamiane 

Can you connect to C$ using `smbclient.py`? Something tells me that user doesn't have enough privileges. Did you configure the [LocalAccountTokenFilterPolicy](https://msdn.microsoft.com/en-us/library/aa826699(v=vs.85).aspx) correctly?

**Comment by jmdamiane** [comment]
Update: I haven't tried your suggestion yet as it seems like the target machine is not properly configured to handle RPC. When the issue gets resolved I'll go over the whole process again, if it's still not working I'll try what you've mentioned. Thanks!

**Comment by reinaldo-gomes** [comment]
I've had this problem and it was solved by the windows server administrator - nothing wrong with impacket.

**Comment by asolino** [comment]
Thanks for your comment!.. Closing this one.

**Comment by deedee1378** [comment]
Hi,

I also having the same issue. rpc_s_access_denied error. I am trying to connect to windows 10 machine. User has admin privilege. could you please tell me what needs to be done in windows 10 machine to resolve the issue.

**Comment by Wall1e** [comment]
> Hi,
> 
> I also having the same issue. rpc_s_access_denied error. I am trying to connect to windows 10 machine. User has admin privilege. could you please tell me what needs to be done in windows 10 machine to resolve the issue.
> 
> I tried connecting using smbclient.py and I am able to login to the machine but when I tried to access C drive I am getting access denied error

same question
