### ISSUE TITLE
garbled Chinese character

### ISSUE THREAD

**Issue by soulfy** [CoreSecurity/impacket#460]
`classObject, _ = self.iWbemServices.GetObject('Win32_Process')`
`obj = classObject.Create('cmd.exe /Q /c echo 你好 世界 1>mylog.txt 2>&1', "c:\\", None)`
`handle = obj.getProperties()`
`print handle["ProcessId"]["value"]`

I get the garbled Chinese character on the remote host.
What can I do to get the right result?

the same problem
`wmiexec.py administrator:xxx@192.168.11.63`
`c:\> echo “你好 世界"`
`"??o? êà??"`

**Comment by asolino** [comment]
Hey @soulfy 

Have you tried using `-codec` parameter?

```
  -codec CODEC          Sets encoding used (codec) from the target's output
                        (default "UTF-8"). If errors are detected, run
                        chcp.com at the target, map the result with
                        https://docs.python.org/2.4/lib/standard-
                        encodings.html and then execute wmiexec.py again with
                        -codec and the corresponding codec
```

**Comment by soulfy** [comment]
After updating to v0.9.17, all the Chinese character problems I encountered were resolved. 
Thanks. :-)
