### ISSUE TITLE
VARIANT_ARRAY: __init__() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by soulfy** [CoreSecurity/impacket#462]
C:\Python27\Lib\site-packages\impacket\dcerpc\v5\dcom\oaut.py

1. `# 2.2.30.5 SAFEARR_VARIANT`
2. `class VARIANT_ARRAY(NDRUniConformantArray):`
3. `   # In order to avoid the lack of forward declarations in Python`
4. `    # I declare the item in the constructor`
5. `    #item = VARIANT`
6. `    def __init__(self, data = None, isNDR64 = False):`
7. `        NDRUniConformantArray(self, data, isNDR64)`
8. `        self.item = VARIANT`

line 7, Why does the first parameter 'self' need to be? This result in the error: 
`__init__() takes at most 3 arguments (4 given)`

**Comment by asolino** [comment]
Hey @soulfy 

> line 7, Why does the first parameter 'self' need to be? 

Because that's how you should call the parent's __init__ method in Python :). I could be done with `super()` as well but I decided to do it in the old fashioned way.

What Impacket version are you using? Are you sure you have the latest one installed?

**Comment by soulfy** [comment]
@asolino  Isn't there an implicit ‘self’ as the first parameter in the python class member function. The expicity 'self' isn't an extra parameter?

**Comment by asolino** [comment]
Hey @soulfy:

> @asolino Isn't there an implicit ‘self’ as the first parameter in the python class member function. The expicity 'self' isn't an extra parameter?

That doesn't apply for the `__init__()` method (and other ones as well).

There are newer impacket versions available, check [here](https://pypi.org/project/impacket/)
