### ISSUE TITLE
invalid dep: ldap3-2.5.0

### ISSUE THREAD

**Issue by blshkv** [CoreSecurity/impacket#466]
https://github.com/CoreSecurity/impacket/blob/master/requirements.txt#L4
there is no 2.5.0 releasel, it must be 2.5

**Comment by asolino** [comment]
Hey @blshkv thanks for the bug report.
Interestingly I'm not getting that error when running the impacket's test cases with `tox`:
```
py27 installdeps: -rrequirements.txt
WARNING:Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
py27 inst: /Users/beto/src/impacket/.tox/dist/impacket-0.9.18.dev0.zip
py27 installed: asn1crypto==0.24.0,cffi==1.11.5,click==6.7,cryptography==2.2.2,dnspython==1.15.0,enum34==1.1.6,Flask==1.0.2,idna==2.7,impacket==0.9.18.dev0,ipaddress==1.0.22,itsdangerous==0.24,Jinja2==2.10,ldap3==2.5,ldapdomaindump==0.8.6,MarkupSafe==1.0,pyasn1==0.4.3,pycparser==2.18,pycrypto==2.6.1,pyOpenSSL==18.0.0,six==1.11.0,Werkzeug==0.14.1
py27 runtests: PYTHONHASHSEED='1720347480'
py27 runtests: commands[0] | ./runall.sh py27 > /dev/null
```

As can be seen there, the `ldap3==2.5` package gets downloaded and installed. 

Please help me understand better where the issue is. thanks

**Comment by blshkv** [comment]
It's all about version interpretation. In our system, the number 2.5.0 is bigger than 2.5, similar with 2.5.1 and 2.5. For more examples, see https://leetcode.com/problems/compare-version-numbers/description/
So when I blindly add the current ```ldap3>=2.5.0``` statement, it is unable to find any package because 2.5 is smaller.

The next thing, I'm not sure if impacket is able to find ldap3 during runtime.

So I think it's easier for fix the issue instead of guessing all day.
