### ISSUE TITLE
error: unpack requires a string argument of length 4 (secretsdump.py)

### ISSUE THREAD

**Issue by lolsen4** [CoreSecurity/impacket#477]
Hello,

I am trying to use secretsdump.py to retreive the NT hashes of a ntds.dit file for an internal password audit for a company I am interning for. I keep getting the error mentioned in the title and I do not know what the issue is. I have successfully retrieved hashes from practice .dit and system files, but I can't get the real ones to work. 

Here is the command I am running: 

<pre>python secretsdump.py -ntds ntds.dit -system system -outputfile final local -debug</pre>

here is the debug info:
<pre>Traceback (most recent call last):
  File &quot;secretsdump.py&quot;, line 112, in dump
    bootKey = localOperations.getBootKey()
  File &quot;build/bdist.linux-x86_64/egg/impacket/examples/secretsdump.py&quot;, line 2458, in getBootKey
    currentControlSet = winreg.getValue(&apos;\\Select\\Current&apos;)[1]
  File &quot;build/bdist.linux-x86_64/egg/impacket/winregistry.py&quot;, line 454, in getValue
    key = self.findKey(regKey)
  File &quot;build/bdist.linux-x86_64/egg/impacket/winregistry.py&quot;, line 372, in findKey
    res = self.__findSubKey(parentKey, subKey)
  File &quot;build/bdist.linux-x86_64/egg/impacket/winregistry.py&quot;, line 311, in __findSubKey
    nk = self.__getBlock(res)
  File &quot;build/bdist.linux-x86_64/egg/impacket/winregistry.py&quot;, line 202, in __getBlock
    data = sizeBytes + self.fd.read(unpack(&apos;&lt;l&apos;,sizeBytes)[0]*-1-4)
error: unpack requires a string argument of length 4
[-] unpack requires a string argument of length 4
[*] Cleaning up... 
</pre>

Any help would be greatly appreciated! Thanks!

**Comment by asolino** [comment]
Hey @lolsen4 

What impacket version are you using? In particular, take a look at the initial banner you get when executing `secretdump.py`.

What I can see from the output is an error trying to parse the SYSTEM registry hive. It could be a corrupted hive or a bug. How did you extract the hive?

**Comment by lolsen4** [comment]
Hi @asolino,

I am using Impacket v0.9.17 - Copyright 2002-2018 Core Security Technologies, which I believe is the latest version. I extracted the files after making a shadow copy of the c drive for domain controller where our active directory login info is stored.

**Comment by asolino** [comment]
Hmm.. try saving the SYSTEM hive using `reg` command like  `reg.exe save hklm\security  security.hive`

**Comment by lolsen4** [comment]
I actually just got it to work. I replaced the .dit file and SYSTEM file with some new copies and it ended up working. They must have gotten corrupted some how. Thanks for the help!

**Comment by lolsen4** [comment]
I just want to confirm, if the boot key shows up then the process is working? There's around 450 hashes to crack so i'm guessing it'll take a 30 minutes or so to get them all.

**Comment by lolsen4** [comment]
A few reasons. First, since I am just an intern I did not have the privileges to even access the domain controllers. I actually sat down with our lead systems engineer and he showed me the process of creating a shadow copy of the C drive and copying the necessary files.

Also since we are a financial institution, I don't think my manager wanted me to directly run anything against the domain controller. Plus we have a ton of security (Bit9, SEP) it would have been a super big hassle to get secretsdump.py to run.

That said, I would consider myself still a beginner in this space so there is probably a better way of going about this then my method lol.

**Comment by lolsen4** [comment]
@asolino lol its been almost two hours and the hashes still haven't showed up. I think I'm gonna try to run esedbexport to extract the ntds.dit data.

Since I do have the boot key from the SYSTEM file, would it be possible to pass it to the ntds.dit file with the -bootkey command ?

**Comment by asolino** [comment]
Sorry to hear hashes are not being shown.. maybe the NTDS.DIT file is also corrupted. Have you tried pulling the data this way?:
```
ntdsutil “ac i ntds” “ifm” “create full c:\temp” q q
```
You will have the DIT and SYSTEM hives inside the temp directory (under subdirectories). That is the safest way I found to extract this data. 

If that doesn't work, there must be something else.

**Comment by asolino** [comment]
Great to know it worked @lolsen4, thanks for the heads up, closing.
