### ISSUE TITLE
ntlmrelayx.py -socks MSSQL Port

### ISSUE THREAD

**Issue by SecureThisShit** [CoreSecurity/impacket#483]
Hi,

i just tried to relay Hashes to a MSSQL-Database Server on a high Port (49xxx). The Credentials are relayed successfully. But i get an Error by trying to see the active socks connections:

[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser SUCCEED
[*] SOCKS: Adding CONTOSO\Testuser@x.x.x.x:(49xxx) to active SOCKS connection. Enjoy

The Error is following:

ntlmrelayx>socks
[-] Exception on /ntlmrelayx/api/v1.0/relays [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 246, in get_relays
    protocol = server.socksPlugins[port].PLUGIN_SCHEME
KeyError: 49xxx

Seems like there is a problem with highports??

Greetings

**Comment by dirkjanm** [comment]
I think the error occurs because you specified a non-default port, which the socks command doesn't know how to deal with.
Looking at the code I don't think that any non-default ports are currently supported for SOCKS relaying. This is something we should address in an update.

**Comment by asolino** [comment]
Nice catch @SecureThisShit thanks for reporting this. 

I'll be adding support for non default ports for any protocol. Stay tuned.

**Comment by asolino** [comment]
Hey @SecureThisShit 

Please `git pull` and recheck. Let me know how it goes.

**Comment by SecureThisShit** [comment]
Hi,

I just removed the old impacket version, pulled the new version and installed it. The error is still the same.

Impacket v0.9.18-dev - Copyright 2002-2018 Core Security Technologies

[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client MSSQL loaded..
[*] Running in relay mode to hosts in targetfile
[*] SOCKS proxy started. Listening at port 1080
[*] HTTPS Socks Plugin loaded..
[*] IMAPS Socks Plugin loaded..
[*] HTTP Socks Plugin loaded..
[*] SMB Socks Plugin loaded..
[*] SMTP Socks Plugin loaded..
[*] IMAP Socks Plugin loaded..
[*] MSSQL Socks Plugin loaded..
[*] Setting up SMB Server
[*] Setting up HTTP Server

[*] Servers started, waiting for connections
Type help for list of commands
ntlmrelayx>
ntlmrelayx> socks
[*] No Relays Available!
ntlmrelayx> [*] HTTPD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[*] HTTPD: Client requested path: /
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\TestUser SUCCEED
[*] SOCKS: Adding CONTOSO/TestUser@x.x.x.x(49xxx) to active SOCKS connection. Enjoy
[*] SMBD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser2 SUCCEED
[*] SOCKS: Adding CONTOSO/Testuser2@x.x.x.x(49xxx) to active SOCKS connection. Enjoy
[*] SMBD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser2 SUCCEED
[*] Relay connection for CONTOSO/Testuser2 at x.x.x.x(49xxx) already exists. Discarding
[*] SMBD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser2 SUCCEED
[*] Relay connection for CONTOSO/Testuser2 at x.x.x.x(49xxx) already exists. Discarding

ntlmrelayx> [*] SMBD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser2 SUCCEED
[*] Relay connection for CONTOSO/Testuser2 at x.x.x.x(49xxx) already exists. Discarding
[*] SMBD: Received connection from x.x.x.x, attacking target mssql://x.x.x.x:49xxx
[*] Authenticating against mssql://x.x.x.x:49xxx as CONTOSO\Testuser2 SUCCEED
[*] Relay connection for CONTOSO/Testuser2 at x.x.x.x(49xxx) already exists. Discarding

ntlmrelayx> socks
[-] Exception on /ntlmrelayx/api/v1.0/relays [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 250, in get_relays
    return jsonify(relays)
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 4; 2 is required
[-] ERROR: HTTP Error 500: INTERNAL SERVER ERROR

**Comment by asolino** [comment]
Hey @SecureThisShit 

That is not the same error as your original report. Please let me know the command line arguments you're using. I'm gonna try to reproduce this one.

**Comment by asolino** [comment]
and btw, what is your `flask` version?
you can quickly check it by running inside a Python interpreter the following:
```
import flask
flask.__version__
```

**Comment by SecureThisShit** [comment]
Hey @asolino ,

thank you for the fast support. After Upgrading the Flask Version, it Works! :-)
I am now using Flask version 1.0.2. The Issue is fixed now.

Greetings

**Comment by asolino** [comment]
That is great to know @SecureThisShit .

Besides the `socks` command working, please confirm you can successfully use some of the active sessions (in particular the ones on non-default ports) through SOCKS.

If that works, we can close this issue.

**Comment by SecureThisShit** [comment]
I just verified, that the socks sessions to the MSSQL Database are successfully working! 
Thank you for the fast support!
