### ISSUE TITLE
smbexec error: rpc_x_bad_stub_data on Windows XP

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#58]
hey man,
Was playing around with smbexec.py today and noticed that it throws this exception when run against Windows XP. Works fine on Windows 7, 8. 
any thoughts? 

```
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
Traceback (most recent call last):
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 160, in run
    self.shell = RemoteShell(self.__share, rpctransport, self.__mode, self.__serviceName)
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 205, in __init__
    self.do_cd('')
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 237, in do_cd
    self.execute_remote('cd ' )
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 269, in execute_remote
    resp = scmr.hRCreateServiceW(self.__scmr, self.__scHandle, self.__serviceName, self.__serviceName, lpBinaryPathName=command)
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/impacket/dcerpc/v5/scmr.py", line 1256, in hRCreateServiceW
    return dce.request(createService)
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/impacket/dcerpc/v5/rpcrt.py", line 820, in request
    answer = self.recv()
  File "/home/byt3bl33d3r/.local/lib/python2.7/site-packages/impacket/dcerpc/v5/rpcrt.py", line 1227, in recv
    raise Exception(rpc_status_codes[status_code])
Exception: rpc_x_bad_stub_data
[!] rpc_x_bad_stub_data
Traceback (most recent call last):
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 332, in <module>
    executer.run(address)
  File "/home/byt3bl33d3r/.local/bin/smbexec.py", line 168, in run
    self.shell.finish()
AttributeError: CMDEXEC instance has no attribute 'shell'
```

**Comment by asolino** [comment]
Hey mate:

Service Pack? Do you have a packet capture?

thanks!

**Comment by byt3bl33d3r** [comment]
@asolino from systeminfo: ```5.1.2600 Service Pack 3 Build 2600```
pcap
/home/byt3bl33d3r/winxp.pcap

**Comment by byt3bl33d3r** [comment]
gahh github..
pcap here:
https://mega.co.nz/#!FNJ0DLbb!ZZFh2-0GIbY8uzw3wdNsVUyPms3AuMMVKXpseWGCTGc

**Comment by asolino** [comment]
hmmm.. can't reproduce it on my side:

```
wmiexec.py Administrator:admin@192.168.97.161 'systeminfo | findstr /C:"2600"'
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] SMBv1 dialect used
OS Version:                5.1.2600 Service Pack 3 Build 2600
```
and
```
smbexec.py Administrator:admin@192.168.97.161
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[!] Launching semi-interactive shell - Careful what you execute
C:\WINDOWS\system32>mem


    655360 bytes total conventional memory
    655360 bytes available to MS-DOS
    634416 largest executable program size

   1048576 bytes total contiguous extended memory
         0 bytes available contiguous extended memory
    941056 bytes available XMS memory
           MS-DOS resident in High Memory Area

C:\WINDOWS\system32>

```
The packet you sent me is the same package generated when I type `cd ` (useless for this script btw).

Did you try other scripts like `wmiexec.py` or `psexec.py`?

I will try on other images.. :s

**Comment by byt3bl33d3r** [comment]
I tried wmiexec.py and the script just hangs... I'll try to run it against another XP image, just to triple check

**Comment by asolino** [comment]
hmm.. DCOM might be blocked. (high ports).. either `psexec.py` or `services.py` (list, create, start services).. English language?

**Comment by byt3bl33d3r** [comment]
@asolino DCOM was open, it was allowed through the firewall (tried it also with the firewall disabled). I've also tried the scripts on a different XP image with the same results.

Tried psexec.py which also through an error:
```
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...

[*] Requesting shares on 192.168.20.30.....
[*] Found writable share SharedDocs
[*] Uploading file qzLdseJr.exe
[*] Opening SVCManager on 192.168.20.30.....
[*] Creating service ZITK on 192.168.20.30.....
[*] Starting service ZITK.....
[!] Press help for extra shell commands
[*] Process   finished with ErrorCode: 1, ReturnCode: 0
[*] Opening SVCManager on 192.168.20.30.....
[*] Stoping service ZITK.....
[*] Removing service ZITK.....
[*] Removing file qzLdseJr.exe.....
```

```services.py``` also just hangs when run..

If you want packet captures just let me know.

If you want the actual VM, I'm using the one from here https://www.modern.ie/en-us/virtualization-tools

**Comment by asolino** [comment]
@byt3bl33d3r many thanks for the link!.. I'm downloading now!..

btw... did you execute `psexec.py` with `cmd.exe` as the last parameter?..  That is the same output I get when no program to execute was specified in the command line (yes.. `wmiexec.py` is different. that should be changed).

For example:
`psexec.py Administrator:admin@172.16.123.179 cmd.exe``

Packet captures are welcomed as well :)

**Comment by asolino** [comment]
@byt3bl33d3r I downloaded and used IE6.XP.For.Mac.VMware.zip.

I had to:
* Set the Administrator password (to admin)
* Enable NetBIOS over TCP/IP (port 445 was refusing connection from me)
* Disable firewall (for the sake of testing)

`wmiexec.py` - `OK`:
```
wmiexec.py Administrator:admin@172.16.123.180
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] SMBv1 dialect used
[!] Launching semi-interactive shell - Careful what you execute
[!] Press help for extra shell commands
C:\>
```
`psexec.py` - `OK`:
```
python psexec.py Administrator:admin@172.16.123.180 cmd.exe
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...

[*] Requesting shares on 172.16.123.180.....
[*] Found writable share SharedDocs
[*] Uploading file DwfwhjlM.exe
[*] Opening SVCManager on 172.16.123.180.....
[*] Creating service CGGa on 172.16.123.180.....
[*] Starting service CGGa.....
[!] Press help for extra shell commands
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\WINDOWS\system32>
```

`smbexec.py` - `FAIL`:
```
python smbexec.py Administrator:admin@172.16.123.180
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[-] rpc_x_bad_stub_data
```

Indeed failing as you were describing. Just found the problem was on that specific script. Fixed at: https://github.com/CoreSecurity/impacket/commit/9c85ee047a8be00ae22858b43bd13516a261e18a

Running it again after the changset:
```
python smbexec.py Administrator:admin@172.16.123.180
Impacket v0.9.13-dev - Copyright 2002-2015 Core Security Technologies

[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[!] Launching semi-interactive shell - Careful what you execute
C:\WINDOWS\system32>
```

Let me know if you can reproduce the same things.

Thanks for reporting this!

**Comment by byt3bl33d3r** [comment]
@asolino awesome! 
Just tried ```smbexec.py``` and works perfectly !
```psexec.py``` was working previously, forgot that the syntax was different (oops). ```wmiexec.py``` and ```services.py``` are back in action! (might have been some misconfiguration on my part) 

Closing! ;)
