### ISSUE TITLE
mssqlclient.py target agrument parsing

### ISSUE THREAD

**Issue by Berestoff** [CoreSecurity/impacket#60]
Please consider change target host format in line 120 mssqlclient.py from user:password@host to smothing like "user:password"@host or similar due microsoft accept symbol @ for passwod.
In case we face default password like P@ssw0rd we cannot connect to host due incorrect host name extraction.
Example

user:P@ssword@host - extracted hostname ssword@host 

Thanks.

**Comment by asolino** [comment]
Thanks for your report. Yes, that's a limitation of calling the script with the username and password directly from the command line. I actually don't recommend calling this script explicitly setting the password, unless you know the risks associated with that.

Do you know you can call the script as user@host and then the password will be prompted to the user?

I find that use case better.

Let me know if that solves your problem.

**Comment by Berestoff** [comment]
Thanks for tip. There are few workarounds found, but it helps too.
