### ISSUE TITLE
DCOMRT failure

### ISSUE THREAD

**Issue by deniskhodus** [CoreSecurity/impacket#66]
When trying **WMIQUERY** example, have:
Traceback (most recent call last):
  File "./test2.py", line 162, in <module>
    iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python2.7/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1058, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python2.7/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1848, in RemoteCreateInstance
    if securityBindings != '' and securityBindings[0] == '\x00' and securityBindings[1] == '\x00':
IndexError: string index out of range

**HOW TO FIX**:
/impacket/dcerpc/v5/dcomrt.py, starting from line 1847, instead of:
       while not done:
            if securityBindings[0] == '\x00' and securityBindings[1] == '\x00':
                done = True
            else:
                secBinding = SECURITYBINDING(securityBindings)
                securityBindings = securityBindings[len(secBinding):]

**PUT**:
    while not done:
            if len(securityBindings) < 2:
                done = True
            elif securityBindings[0] == '\x00' and securityBindings[1] == '\x00':
                done = True
            else:
                secBinding = SECURITYBINDING(securityBindings)
                securityBindings = securityBindings[len(secBinding):]

This fixed the error and WMIQuery works fine ;)

**Comment by asolino** [comment]
I couldn't reproduce it on my side but that check doesn't hurt.
Can you tell me what the target operating system was on your side?

thanks!
