### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by MrTchuss** [CoreSecurity/impacket#67]
README file is renamed to README.md, but setup.py does not reflect this modification, causing install to fail:
`# python setup.py install`
`[...]`
`error: can't copy 'README': doesn't exist or not a regular file`

`# grep -Rn README`
`setup.py:24:      data_files = [(os.path.join('share', 'doc', PACKAGE_NAME), ['README', 'LICENSE']+glob.glob('doc/*')),`

Where it sould be : 
`setup.py:24:      data_files = [(os.path.join('share', 'doc', PACKAGE_NAME), ['README.md', 'LICENSE']+glob.glob('doc/*')),`

Thanks

**Comment by asolino** [comment]
Good catch!.. Fixing.. thanks a lot!
