### ISSUE TITLE
Consistency between IP and IP6 objects

### ISSUE THREAD

**Issue by jimbo1023** [CoreSecurity/impacket#69]
Would it be possible to make the attributes of impacket.IP6.IP6 and impacket.ImpactPacket.IP more consistent? There are probably several examples, but the one that tripped me up is getting the IP addresses.

For IP, it's `get_ip_src()` and `get_ip_dst()`
For IP6, it's `get_source_address()` and `get_destination_address()`

Can it only be one or the other? It'd save developers like me an if-statement.

**Comment by asolino** [comment]
Yep, it would be easier to have same method's name.

Any soul willing to correct this and issue a PR?

I would add the IPv4 methods (more used) as aliases for the IPv6 ones.

**Comment by martinuy** [comment]
At 37e40a732e5592b43f5678ef8e8bed7ffff66e81:
 * IPv6 interface aligned to IPv4 interface.

Interface change is now a suggestion but will be enforced soon.

**Comment by martinuy** [comment]
At 6a49832e2b8fad4e5238b7d35bc8eb057e31eef8:

 * Import was missing.
