### ISSUE TITLE
atexec.py fails with with Windows Server 2012 R2 target

### ISSUE THREAD

**Issue by sshock** [CoreSecurity/impacket#70]
The atexec.py example is working well for me with most machines, but not with Windows Server 2012.  It returns error 50 (ERRunsup) when trying to use port 445, which should work.

Here's an example output:

    sshock@sshock:~/git/impacket/examples$ ./atexec.py DOMAIN/user@hostname dir
    Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies
    [!] This will work ONLY on Windows >= Vista
    [*] Trying protocol 445/SMB...
    [-] ATSVC SessionError: unknown error code: 50
    [*] Trying protocol 139/SMB...
    [-] SMB SessionError: STATUS_INVALID_PARAMETER(An invalid parameter was passed to a service or function.)

**Comment by asolino** [comment]
Hey there.. Just to reproduce this on my side... Title states target should be 2012R2 but description says 2012. Please confirm.

I'm in the process of creating the [MS-TSCH] interfaces with the new DCERPC library (dcerpc/v5) so it will be a good opportunity for checking this out. Stay tuned.

Until then, [wmiexec](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py), [psexec](https://github.com/CoreSecurity/impacket/blob/master/examples/psexec.py) or [smbexec](https://github.com/CoreSecurity/impacket/blob/master/examples/smbexec.py) could be good replacements (in that order IMHO ;) ).

**Comment by sshock** [comment]
Thanks for the quick reply.  It's 2012R2.  Let me know when the new v5 is going and I'll be happy to retest atexec.

Yeah, I'm using psexec for now and it is working nicely on all targets.  I tried smbexec, but it only support interactive, whereas I need to pass a command.

wmiexec never seems to work for me; I always get "[Errno -2] Name or service not know" or "[-] DCOM SessionError: unknown error code: 0x800706ba".

**Comment by asolino** [comment]
I will definitely let you know so you can help me testing.

I'm worried about `wmiexec` since it's the stealthier method for executing commands, and I never experienced that error. Would you mind executing it again with the `-debug` flag and create a different issue for it?

thanks!

**Comment by sshock** [comment]
Sure.

**Comment by asolino** [comment]
@sshock, could you please test the new `atsvc.py`? By using ITaskSchedulerService interface it seems to fix the issue. It should still work from Vista on.
Thanks!

**Comment by sshock** [comment]
Sure thing.  I just did a pull and tried it and it works now, thanks!

**Comment by asolino** [comment]
Thanks! Closing this one.
