### ISSUE TITLE
DRSUAPI dump doesn't work on Windows 2003

### ISSUE THREAD

**Issue by rdubourguais** [CoreSecurity/impacket#78]
When I run secretsdump.py against an Active Directory based on Windows 2003 , I get the following error:

     [*] Using the DRSUAPI method to get NTDS.DIT secrets
     [!] rpc_x_bad_stub_data
     [...]

The error comes from the following call (line 324 in secretsdump.py) :

        stringBinding = epm.hept_map(self.__smbConnection.getRemoteHost(), drsuapi.MSRPC_UUID_DRSUAPI, protocol='ncacn_ip_tcp')

The underlying stacktrace is the following:

       File " [...]/impacket/dcerpc/v5/epm.py", line 964, in hept_map
            resp = dce.request(request)
       File  "[...]/impacket/dcerpc/v5/rpcrt.py", line 837, in request
            answer = self.recv()
       File " [...]/impacket/dcerpc/v5/rpcrt.py", line 1253, in recv
            raise DCERPCException(rpc_status_codes[status_code])
       DCERPCException: rpc_x_bad_stub_data

**Comment by asolino** [comment]
Yup.. that's a known issue with the endpoint mapper and Windows 2003. Nice catch btw.

Since DRSUAPI is listening at a dynamic port we need to ask the remote port mapper for that info.

In the meantime, you can bypass that `hept_map` call by manually setting the `stringBinging` variable. You will need to:
1) run `rpcdump.py` against the target.
2) Look for the DRSUAPI UUID (`E3514235-4B06-11D1-AB04-00C04FC2DCD2`)
3) copy the `ncacn_ip_tcp` string binding you find there (e.g. `ncacn_ip_tcp:172.16.123.170[49155]`) into the `stringBinding` variable

**Comment by asolino** [comment]
Btw, Windows 2003 SP?

**Comment by rdubourguais** [comment]
I tried on Windows 2003 SP2.

Thanks for your mitigation ;)

**Comment by rdubourguais** [comment]
Using your workaround which correctly fix the port mapper issue (thanks for that), I trigger another bug:

      [*] Using the DRSUAPI method to get NTDS.DIT secrets
      Traceback (most recent call last):
        File "./examples/secretsdump.py", line 1600, in dump
             self.__decryptHash(userRecord, user['RelativeId'])
        File "./examples/secretsdump.py", line 1468, in __decryptHash
             for attr in record['pmsgOut']['V6']['pObjects']['Entinf']['AttrBlock']['pAttr']:
         TypeError: string indices must be integers, not str

After some quick investigations, it seems that Windows 2003 SP2 doesn't return objects in the linked list `record['pmsgOut']['V6']['pObjects']`, the following statement returns True:

        record['pmsgOut']['V6']['cNumObjects'] == 0

As I just started to dig into the MS-DRSR specifications, I'm not enough comfortable yet to quickly find the source of the issue... :). Do you any ideas from your side?

**Comment by asolino** [comment]
Inside the `cObjects` linked list are the AD Attributes. We should be doing something wrong against that OS.
Can you dump the answers returned so we can inspect them better? In particular `crackedName` and `userRecord`. You have to call the `dump` and that's it. Here's the code with those calls starting at line 1585:

```Python
# Let's crack the user name into DS_FQDN_1779_NAME
try:
    crackedName = self.__remoteOps.DRSCrackNames(drsuapi.DS_NT4_ACCOUNT_NAME_SANS_DOMAIN, name = userName)
    crackedName.dump()
except DCERPCException, e:
    logging.warning(str(e))
    crackedName = None

if crackedName is not None:
    if crackedName['pmsgOut']['V1']['pResult']['cItems'] == 1:
        userRecord = self.__remoteOps.DRSGetNCChanges(crackedName['pmsgOut']['V1']['pResult']['rItems'][0]['pName'][:-1])
        userRecord.dump()
    else:
        logging.warning('DRSCrackNames returned %d items for user %s, skipping' %(crackedName['pmsgOut']['V1']['pResult']['cItems'], userName))
```

I'm particularly interested in the `userRecord['pmsgOut']['V6']['ulExtendedRet']` field. I guess it is not returning success (1). The error codes is one of the following [MS-DRSR], section 4.1.10.2.17:
```
EXOP_ERR_SUCCESS (0x00000001) 
EXOP_ERR_UNKNOWN_OP (0x00000002) 
EXOP_ERR_FSMO_NOT_OWNER (0x00000003) 
EXOP_ERR_UPDATE_ERR (0x00000004) 
EXOP_ERR_EXCEPTION (0x00000005) 
EXOP_ERR_UNKNOWN_CALLER (0x00000006) 
EXOP_ERR_RID_ALLOC (0x00000007) 
EXOP_ERR_FSMO_OWNER_DELETED (0x00000008) 
EXOP_ERR_FSMO_PENDING_OP (0x00000009) 
EXOP_ERR_MISMATCH (0x0000000A) 
EXOP_ERR_COULDNT_CONTACT (0x0000000B) 
EXOP_ERR_FSMO_REFUSING_ROLES (0x0000000C) 
EXOP_ERR_DIR_ERROR (0x0000000D) 
EXOP_ERR_FSMO_MISSING_SETTINGS (0x0000000E) 
EXOP_ERR_ACCESS_DENIED (0x0000000F) 
EXOP_ERR_PARAM_ERROR (0x00000010)
```

This would be a good starting point to understand what's going on. I'm gonna try to configure a w2k3 sp2 DC. 
Did you try on other OS?

In any case, we should test `ulExtendedRet` before calling `__decryptHash` to avoid the script failing the way you described. I'll change that. 

thanks for helping on this mate. We are all learning this protocol.. it's kind of big ugh? ;)

**Comment by rdubourguais** [comment]
Good catch, something is going wrong, `ulExtendedRet` contains `EXOP_ERR_PARAM_ERROR`:

       DRSCrackNamesResponse
       pdwOutVersion:                   1
       pmsgOut:
           tag:                             1
           V1:
               pResult:
                   cItems:                          1
                   rItems:
                       [

                           status:                          0
                           pDomain:                         u'mydomain.local\x00'
                           pName:                           u'CN=Guest,CN=Users,DC=mydomain,DC=local\x00' ,
                       ]
       ErrorCode:                       0


       DRSGetNCChangesResponse
       pdwOutVersion:                   6
       pmsgOut:
           tag:                             6
           V6:
               uuidDsaObjSrc:                   ']\x17y\xc0@\xb1\xb0C\xae\x8c\xfb\xdc\xba\xcf\xc4\xbf'
               uuidInvocIdSrc:                  '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
               pNC:
                   structLen:                       130
                   SidLen:                          0
                   Guid:                            '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                   Sid:                             '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                   NameLen:                         36
                   StringName:                      'CN=Guest,CN=Users,DC=mydomain,DC=local\x00'
               usnvecFrom:
                   usnHighObjUpdate:                0
                   usnReserved:                     0
                   usnHighPropUpdate:               0
               usnvecTo:
                   usnHighObjUpdate:                0
                   usnReserved:                     0
                   usnHighPropUpdate:               0
               pUpToDateVecSrc:                 NULL
               PrefixTableSrc:
                   PrefixCount:                     39
                   pPrefixEntry:
                       [

                           ndx:                             0
                           prefix:
                               length:                          2
                               elements:
                                   [
                                        'U',
                                        '\x04',
                                   ] ,
        [...]
               ulExtendedRet:                   16
               cNumObjects:                     0
               cNumBytes:                       0
               pObjects:                        NULL
               fMoreData:                       0
               cNumNcSizeObjectsc:              0
               cNumNcSizeValues:                0
               cNumValues:                      0
               rgValues:                        NULL
               dwDRSError:                      0
       ErrorCode:                       0

I only tried on Windows 2008 R2 (where it works like a charm) and Windows 2003 SP2. The bug probably affect Windows 2003 SP2 and earlier.

**Comment by asolino** [comment]
Thanks for the quick answer!. Look what I just found. From `4.1.10.1.3 Extended Operations`:

> Replicate Single Object including Secret Data (EXOP_REPL_SECRETS): Adds any changes to the 
> specified object to the response. In addition, it also adds the secret attribute values of the specified 
>  object to the response, regardless of whether they have recent changes. See the IsSecretAttribute 
> procedure in section 4.1.10.3.12 for a list of these attributes.<24>
 
and then if you follow the link it says:

> <24> Section 4.1.10.1.3: The Replicate Single Object including Secret Data extended operation is 
> supported by Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, and Windows 
> Server 2012 R2.

Which makes sense with this problem.

Now, let's give it a try without that extended operation and let's see what happens. I thought I needed that for the secret attributes to be included in the answer, but I just tested it w/o it and it still works.

Replace this line https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py#L406 for:
```
request['pmsgIn']['V8']['ulExtendedOp'] = drsuapi.EXOP_REPL_OBJ 
```
and retest

thanks!

**Comment by rdubourguais** [comment]
Ok, that's a good start indeed. I still have the same error `EXOP_ERR_PARAM_ERROR`. There is probably another flag issue. I'm gonna check it out.

**Comment by asolino** [comment]
btw, https://github.com/CoreSecurity/impacket/commit/fb7e250d75c269ad1754bf5e52950bff5e9cdb64 fixes (hopefully) the portmapper issue. You can now run `secretsdump.py` w/o the mitigation I described before

**Comment by asolino** [comment]
More data here: https://lists.samba.org/archive/cifs-protocol/2008-July/000191.html

Something tells me [MS-DRSR] is wrong and this capability is not supported if DC < w2k8

**Comment by asolino** [comment]
Fixed in  https://github.com/CoreSecurity/impacket/commit/e6ec7297eb4b4799a6e048222a7e27dc03a2d1fa 
Let me know if it worked!
