### ISSUE TITLE
wmi class RSOP_UserPrivilegeRight wrong result

### ISSUE THREAD

**Issue by tsmall888** [CoreSecurity/impacket#79]
Hi!

Following wmi query must be return 'AccountList' as array of groups like ['Administrators', 'Authenticated Users'] or array of SIDs like ['S-1-5-32-544', 'S-1-5-11'], but as you can see returns array of int values - [33].

```
./wmiquery.py -namespace //./root/RSOP/computer domain/username:password@host
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

[!] Press help for extra shell commands
WQL> select * from RSOP_UserPrivilegeRight WHERE UserRight = 'SeNetworkLogonRight'
| id | precedence | name | GPOID | SOMID | creationTime | Status | ErrorCode | UserRight | AccountList |
| ${someId} | 1 | 0 | $someGPOID | 3 | 0 | 1 | 0 | SeNetworkLogonRight | [33] |
WQL>
```

Can you explain this? It's a bug or feature?

Kind regards,
Timur

**Comment by asolino** [comment]
Hey Timur:

Definitely looks like a bug, not a feature. Looking into it

**Comment by asolino** [comment]
Timur, please update your repository and let me know if this issue got fixed. Thanks.

**Comment by tsmall888** [comment]
Alberto, many thanks for your earliest attention. Now everything works fine.

**Comment by asolino** [comment]
Great to know mate. Let me know if you find anything else with `wmiquery.py` since it's a very complex protocol (`RPC/DCOM/WMI`) and it's not easy to test.
Cheers!
