### ISSUE TITLE
samrdump.py fails to retrieve account details 

### ISSUE THREAD

**Issue by byt3bl33d3r** [CoreSecurity/impacket#81]
This is the output of samrdump.py targeting a box with an account lockout threshold set to 5 and  a user description filled in on every user :
```
python samrdump.py drugcompany:crackmeumofo@172.16.206.132
Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies

[*] Retrieving endpoint list from 172.16.206.132
[*] Trying protocol 445/SMB...
Found domain(s):
 . drugcompany-PC
 . Builtin
[*] Looking up users in domain drugcompany-PC
Found user: Administrator, uid = 500
Found user: drugcompany, uid = 1000
Found user: drugdealer, uid = 1003
Found user: drugdealerboss, uid = 1005
Found user: Guest, uid = 501
Found user: HomeGroupUser$, uid = 1002
Found user: n00bdrugdealer, uid = 1004
Administrator (500)/FullName: 
Administrator (500)/UserComment: 
Administrator (500)/PrimaryGroupId: 513
Administrator (500)/BadPasswordCount: 0
Administrator (500)/LogonCount: 0
drugcompany (1000)/FullName: 
drugcompany (1000)/UserComment: 
drugcompany (1000)/PrimaryGroupId: 513
drugcompany (1000)/BadPasswordCount: 0
drugcompany (1000)/LogonCount: 0
drugdealer (1003)/FullName: drugdealer
drugdealer (1003)/UserComment: 
drugdealer (1003)/PrimaryGroupId: 513
drugdealer (1003)/BadPasswordCount: 0
drugdealer (1003)/LogonCount: 0
drugdealerboss (1005)/FullName: drugdealerboss
drugdealerboss (1005)/UserComment: 
drugdealerboss (1005)/PrimaryGroupId: 513
drugdealerboss (1005)/BadPasswordCount: 0
drugdealerboss (1005)/LogonCount: 0
Guest (501)/FullName: 
Guest (501)/UserComment: 
Guest (501)/PrimaryGroupId: 513
Guest (501)/BadPasswordCount: 0
Guest (501)/LogonCount: 0
HomeGroupUser$ (1002)/FullName: HomeGroupUser$
HomeGroupUser$ (1002)/UserComment: 
HomeGroupUser$ (1002)/PrimaryGroupId: 513
HomeGroupUser$ (1002)/BadPasswordCount: 0
HomeGroupUser$ (1002)/LogonCount: 0
n00bdrugdealer (1004)/FullName: n00bdrugdealer
n00bdrugdealer (1004)/UserComment: 
n00bdrugdealer (1004)/PrimaryGroupId: 513
n00bdrugdealer (1004)/BadPasswordCount: 0
n00bdrugdealer (1004)/LogonCount: 0
[*] Received 7 entries.
```
The accounts are successfully retrieved, but the account details are always blank and the BadPassword/LogonCount are always 0, tested on all systems windows 7 +

**Comment by asolino** [comment]
Hey..

I cannot reproduce this.. I mean.. Yes.. I get BadPassword/LogonCount as 0, but I think that's what hSamrQueryInformationUser2() (https://msdn.microsoft.com/en-us/library/cc245786.aspx) is returning.  I quickly checked what WireShark is parsing and the results we're printing back. 
Did you check that? I just wanna be sure it's not a parsing issue. 

Btw, if you wanna see the full user record returned, add a `info.dump()` after https://github.com/CoreSecurity/impacket/blob/master/examples/samrdump.py#L141

**Comment by byt3bl33d3r** [comment]
@asolino ok so it def isn't  a bug, just did a packet capture with wireshark and the information returned is correct.
It seems that if you ask for this info via the ```QueryUserInfo2``` samr request, the information returned is incorrect (??) .
I compared the traffic with Metasploit's ```smb_enumusers``` aux module and  they seem to be using the ```QueryDomainInfo``` SAMR request and the information returned is accurate.

Here's a packet capture of the ```smb_enumusers``` module https://mega.nz/#!nIAHHR5Z!pnxc7zCQJ9djh5Xm7h-5jtWpV4qXDc0KGoILb2xXC2M

**Comment by asolino** [comment]
I found the problem..  I wasn't opening the user with enough permissions for gather all the data. Now it seems to work. Please re check!

**Comment by byt3bl33d3r** [comment]
@asolino yep!  that seems to have helped! the BadPassword count for some reason still seems to be always 0, don't know whats going on there lol

**Comment by asolino** [comment]
I bet that has to do with the permissions used to open the domain and or the user.

Why don't you run samr.py test cases? The are located at https://github.com/CoreSecurity/impacket/blob/master/impacket/testcases/SMB_RPC/test_samr.py.
Don't forget first to fill up https://github.com/CoreSecurity/impacket/blob/master/impacket/testcases/SMB_RPC/dcetests.cfg. Then run the test and inspect its output. Look for `BadPasswordCount`

That will help speeding up the process instead of reading the whole [MS-SAMR] standard :P

**Comment by asolino** [comment]
Btw.. just did a quick check and with the latest changes I can see the `BadPasswordCount` updated.

Do this:
1) Run samrdump.py authenticating using one user (e.g. `normaluser`) and specify the wrong password. You can do this twice. You should get `STATUS_LOGON_FAILURE` 
2) Run samrdump.py using the Administrator user, with the right password. Now check `normaluser` `BadPasswordCount` record. It should say 2. 

Remember that next time you log in as `normaluser` successfully his `BadPasswordCount` field will reset to 0.

**Comment by byt3bl33d3r** [comment]
@asolino will do ! thanks !
 I actually got the ```LockoutThreshold ``` number by just doing:
```python
resp = samr.hSamrQueryInformationDomain(dce, domainHandle)
print resp['Buffer']['General2']['LockoutThreshold']
```
right after line 125 https://github.com/CoreSecurity/impacket/blob/master/examples/samrdump.py#L125

**Comment by byt3bl33d3r** [comment]
@asolino seems I was confusing the LockoutThreshold with BadPassword , my bad!
