### ISSUE TITLE
"Killed"

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#83]
When running secretsdump.py, I got to the DRSUAPI portion, and after about 20 hashes it just said "Killed" and quit

Possibly memory usage?

**Comment by mubix** [comment]
Yup, pegged through the roof (47% is all available memory)
```
 11.3 47.8   0:04.88 python
```

**Comment by asolino** [comment]
Fully updated impacket I assume right? DC target OS?

**Comment by mubix** [comment]
Yes, fully updated, just did a fresh build OS (Debian 8)/Impacket on a box w/ 4 GB of RAM, still pegged out. Target OS: Windows Server 2008 R2 Standard 7601 Service Pack 1 (English)

**Comment by asolino** [comment]
Didn't mean to close it. Whenever possible a retest would be desired. At least test the process `blew past` the user it was killing the script before.
Then please close it

**Comment by asolino** [comment]
I was told the script finished successfully after the changes made. Closing
