### ISSUE TITLE
Feature Request - secretsdump resume

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#85]
With large NTDS based dumps, connectivity may break and having the ability to resume halfway through a pull would be awesome

**Comment by mubix** [comment]
Another probably easy bolt on here is to identify how many objects total that will be dumped. Would be nice to know if I'm gonna have to sit around all day due to network lag for a million accounts to dump

**Comment by asolino** [comment]
I like them both mate.. trying to find some time off work to code these ones.. stay tuned.

**Comment by asolino** [comment]
> Another probably easy bolt on here is to identify how many objects total that will be dumped

Did you find a way to quickly do this? The only way I found (using DCE-RPC) is to ask the list of all users and then count them before starting dumping its info. Something that is actually not that efficient IMHO.
Note that the current approach doesn't know the total amount of users until the dump finishes:
```
            while status == STATUS_MORE_ENTRIES:
                resp = self.__remoteOps.getDomainUsers(enumerationContext)

                for user in resp['Buffer']['Buffer']:
                    userName = user['Name']
[...]
                    try:
                        self.__decryptHash(userRecord, user['RelativeId'],
                                           userRecord['pmsgOut']['V6']['PrefixTableSrc']['pPrefixEntry'],
                                           hashesOutputFile)
                        if self.__justNTLM is False:
                            self.__decryptSupplementalInfo(userRecord, userRecord['pmsgOut']['V6']['PrefixTableSrc'][
                                'pPrefixEntry'], keysOutputFile, clearTextOutputFile)

                    except Exception, e:
                        #import traceback
                        #traceback.print_exc()
                        logging.error("Error while processing user!")
                        logging.error(str(e))

[...]
                enumerationContext = resp['EnumerationContext']
                status = resp['ErrorCode']
```

I haven't found a DCE-RPC call that will tell me that total amount of users in AD.

Let me know if you want anything.

**Comment by asolino** [comment]
no update.. closing.

**Comment by mubix** [comment]
@asolino sorry I didn't get back to you. I didn't find a way either
