### ISSUE TITLE
Kali 2.0 smbserver.py

### ISSUE THREAD

**Issue by rvrsh3ll** [CoreSecurity/impacket#87]
Fresh Kali 2.0 install + updates

python smbserver.py --help
Traceback (most recent call last):
  File "smbserver.py", line 24, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'

**Comment by asolino** [comment]
Kali 2.0 impacket version is `0.9.12`.

Current impacket version is `0.9.14-dev` (and `0.9.13` stable).

In either way, you should install the latest version. Just run `python setup.py install` inside the impacket directory and try again.

**Comment by asolino** [comment]
Closing

**Comment by DanMcInerney** [comment]
dan@kali-64:~/$ pip freeze | grep impacket
impacket==0.9.13

dan@kali-64:~/$ python wmiquery.py 
Traceback (most recent call last):
  File "wmiquery.py", line 114, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'

Same problem.

**Comment by asolino** [comment]
I'm reopening it and testing. 

I can't reproduce it with a plain vanilla Kali 2.0. I'm upgrading packages now to see if there's something weird.

Did you install impacket besides the Kali installed one?

**Comment by asolino** [comment]
Dan:

Just updated Kali and indeed it updates impacket:
```
root@kali-beto:/tmp# dpkg -l | grep impacket
ii  python-impacket                        0.9.13-0kali1                        all          Python module to easily build and dissect network protocols
```
Now, I think what you did was to grab `wmiquey.py` from impacket's trunk version (https://github.com/CoreSecurity/impacket/blob/master/examples/wmiquery.py). If I do that and execute that script I get:
```
root@kali-beto:/tmp# python wmiquery.py
Traceback (most recent call last):
  File "wmiquery.py", line 114, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'
```
The reason why that happens is because a the `logger` class has been changed after `impacket-0.9.13`. In general, you should **always use** the examples of the corresponding installed version.

For `impacket-0.9.13` you have two options:
1. Grab examples from github [0.9.13 tag](https://github.com/CoreSecurity/impacket/tree/impacket_0_9_13/examples)
2. Use the examples installed in Kali:
```
root@kali-beto:/tmp# dpkg -L python-impacket
/.
/usr
[..]
/usr/share/doc/python-impacket
/usr/share/doc/python-impacket/examples
/usr/share/doc/python-impacket/examples/rdp_check.py
/usr/share/doc/python-impacket/examples/opdump.py
/usr/share/doc/python-impacket/examples/split.py
/usr/share/doc/python-impacket/examples/registry-read.py
/usr/share/doc/python-impacket/examples/sniffer.py
/usr/share/doc/python-impacket/examples/wmiexec.py
/usr/share/doc/python-impacket/examples/rpcdump.py
/usr/share/doc/python-impacket/examples/smbrelayx.py
/usr/share/doc/python-impacket/examples/ntfs-read.py
/usr/share/doc/python-impacket/examples/mssqlinstance.py
/usr/share/doc/python-impacket/examples/psexec.py
/usr/share/doc/python-impacket/examples/wmiquery.py
/usr/share/doc/python-impacket/examples/samrdump.py
/usr/share/doc/python-impacket/examples/smbtorture.py
/usr/share/doc/python-impacket/examples/smbserver.py
/usr/share/doc/python-impacket/examples/loopchain.py
/usr/share/doc/python-impacket/examples/sniff.py
/usr/share/doc/python-impacket/examples/smbclient.py
/usr/share/doc/python-impacket/examples/uncrc32.py
/usr/share/doc/python-impacket/examples/ping6.py
/usr/share/doc/python-impacket/examples/mssqlclient.py
/usr/share/doc/python-impacket/examples/wmipersist.py
/usr/share/doc/python-impacket/examples/karmaSMB.py
/usr/share/doc/python-impacket/examples/lookupsid.py
/usr/share/doc/python-impacket/examples/os_ident.py
/usr/share/doc/python-impacket/examples/esentutl.py
/usr/share/doc/python-impacket/examples/secretsdump.py
/usr/share/doc/python-impacket/examples/ping.py
/usr/share/doc/python-impacket/examples/goldenPac.py
/usr/share/doc/python-impacket/examples/atexec.py
/usr/share/doc/python-impacket/examples/services.py
/usr/share/doc/python-impacket/examples/smbexec.py
/usr/share/doc/python-impacket/examples/nmapAnswerMachine.py
/usr/share/doc/python-impacket/examples/ifmap.py
/usr/share/doc/python-impacket/examples/netview.py
/usr/share/doc/python-impacket/examples/tracer.py
```
Let me know if it works on your side so I close this issue.

**Comment by DanMcInerney** [comment]
You are 100% correct and I appreciate every word of it.

**Comment by asolino** [comment]
Thanks for the quick update Dan!

Closing.

**Comment by sho-luv** [comment]
I know this was closed however I just ran:
```
git clone https://github.com/CoreSecurity/impacket.git
cd impacket
python setup.py install
```
then attempted to use the installed examples  
```
psexec.py 
Traceback (most recent call last):
  File "/usr/local/bin/psexec.py", line 404, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'
```
I was hopping the new install would overwrite any old instances. Is there a way to uninstall it completely without just hunting for installed examples? Or is there a way to download all the examples in 0.9.13? as downloading psexec.py from https://github.com/CoreSecurity/impacket/tree/impacket_0_9_13/examples seems to work.
What I would like to do is just blow aways any remnants of impacket and start from scratch.

**Comment by asolino** [comment]
hey @sho-luv:

New install does not overwrite old instance, and that's a Kali configuration issue (nothing I can do about it I think). 

> Is there a way to uninstall it completely without just hunting for installed examples?

Try running:
```
sudo apt-get remove python-impacket
````

> Or is there a way to download all the examples in 0.9.13?

You have them all installed at `/usr/share/doc/python-impacket/examples/` 

I'd recommend tho, to uninstall 0.9.13 and use the development version since it adds a lot of new functionality and bug fixes. 

Let me know how it goes.

**Comment by sho-luv** [comment]
My over thinking of the solution was:
```
ls examples/ | xargs -t -I file curl -o /usr/local/bin/file https://raw.githubusercontent.com/CoreSecurity/impacket/impacket_0_9_13/examples/file
```
which got it working for me. Thanks for addressing this. I just uninstalled it and reinstalled it and works perfectly thanks.

**Comment by asolino** [comment]
Great to know it's working @sho-luv. Closing.

Cheers mate!

**Comment by ad0nis** [comment]
Any way to fix this without ripping out half of kali in the process?

> sudo apt-get remove python-impacket 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-distlib python-pycryptopp python-pysnmp4 python-pysnmp4-apps python-pysnmp4-mibs smitools
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  enum4linux kali-linux-full keimpx patator polenum python-impacket set smbmap sparta wol-e
0 upgraded, 0 newly installed, 10 to remove and 1394 not upgraded.
After this operation, 59.1 MB disk space will be freed.
Do you want to continue? [Y/n] n 
Abort.

**Comment by asolino** [comment]
Hey @ad0nis, maybe [this](http://askubuntu.com/questions/17745/how-to-remove-a-deb-without-removing-its-dependencies) could help. I haven't used the latest Kali but as I commented before there's nothing much I can do since the new install (when you run `python setup.py install`) does not overwrite the previous install (original Kali package). That's a OS configuration thing. You should get in touch with the Kali folks.

Let us know if that link worked out for you.

**Comment by yotabytes** [comment]
I was experiencing this same issue in version 0.9.19-dev, and after upgrading to 0.9.29-dev, both from a fresh git clone into /opt and from the default kali installation example files. After trying a number of things that didn't work it finally worked after I did the following:

go into the impacket folder (where the requirements.txt and setup.py are), and run 
# python -m pip install .

**Comment by b3twiise** [comment]
> I was experiencing this same issue in version 0.9.19-dev, and after upgrading to 0.9.29-dev, both from a fresh git clone into /opt and from the default kali installation example files. After trying a number of things that didn't work it finally worked after I did the following:
> 
> go into the impacket folder (where the requirements.txt and setup.py are), and run
> # python -m pip install .



Fixed fro me `pip install -m .`
