### ISSUE TITLE
Feature Request - Support for invalid user and ID

### ISSUE THREAD

**Issue by mubix** [CoreSecurity/impacket#88]
slides 42 and 48 - http://www.slideshare.net/gentilkiwi/abusing-microsoft-kerberos-sorry-you-guys-dont-get-it

**Comment by mubix** [comment]
Not really useful in the context of Impacket, it's part of the ticket

**Comment by asolino** [comment]
Oh really?.. I was thinking on how to do pacEdit.py a few days ago
actually...
