### ISSUE TITLE
secretsdump.py error after update

### ISSUE THREAD

**Issue by williamcaput** [CoreSecurity/impacket#99]
kali:secretsdump.py

Traceback (most recent call last):
  File "/usr/local/bin/secretsdump.py", line 61, in <module>
    from impacket.examples import logger
ImportError: No module named examples

**Comment by asolino** [comment]
You're probably using examples from the old library. 

Grab the examples from the 0.9.13 (assuming you just upgraded Kali) tag located here: https://github.com/CoreSecurity/impacket/tree/impacket_0_9_13/examples

or, you might have the the examples from the Kali's impacket version installed located at `/usr/share/doc/python-impacket/examples`

Please confirm you fixed the issue and close this ticket. Or, let's keep trying ;)

**Comment by williamcaput** [comment]
Not working.
Nothing located at /usr/share/doc/python-impacket/examples

I didn't do a Kali update, just ran the git clone and install script.

**Comment by asolino** [comment]
Gotcha.

run `python`  and type the following command:
```
from impacket import version
version.__file__
version.BANNER
```
and paste the output please.

thanks

**Comment by williamcaput** [comment]
>>> version.BANNER
'Impacket v1.0-dev - Copyright 2002-2012 Core Security Technologies\n'
>>> version.__file__
'/usr/lib/pymodules/python2.7/impacket/version.pyc'
>>>

**Comment by asolino** [comment]
wow.. are you using kali 1?? Don't know what impacket version is that.

Okey.. first of all you should remove that version.

`rm -rf /usr/lib/pymodules/python2.7/impacket*`

then:

```
git clone https://github.com/CoreSecurity/impacket.git
cd impacket
python setup.py install
```
and run again:
```
from impacket import version
version.__file__
version.BANNER
```

**Comment by williamcaput** [comment]
We are working!

>>> from impacket import version
>>> version.__file__
'/usr/local/lib/python2.7/dist-packages/impacket/version.pyc'
>>> version.BANNER
'Impacket v0.9.14-dev - Copyright 2002-2015 Core Security Technologies\n'

**Comment by asolino** [comment]
Excellent!

now you should have all the example scripts located in `/usr/local/bin`. Please confirm the issue is solved and you close this ticket.

thanks mate!

**Comment by williamcaput** [comment]
Thanks for your help!
